- README.md
current clone instruction won't works because  git clone doesn't download submodules  like 'nailgun-server'
therefore it seems like 
'git clone --recursive -j8 https://github.com/scalacenter/bloop.git' should be used (for git >= 1.9)
> fix cloning part at installation section at README

- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/tasks/TestTasks.scala
- frontend/src/test/scala/bloop/tasks/TestTaskTest.scala
This makes it more convenient to run the tests. It's still possible
to specify the `-test` suffix.
> Select test project with suffix when running tests

- frontend/src/main/scala/bloop/engine/Interpreter.scala
Otherwise we were just returning the projects that have been cleaned,
completely discarding the projects that were untouched.
Fixes #94
> Fix #94: Add projects + cleaned projects in clean

- frontend/src/main/scala/bloop/tasks/TestTasks.scala
- frontend/src/main/scala/bloop/testing/TestInternals.scala
We were not sufficiently strict in our consideration of what may be a
test suite. This made us check the fingerprints against many more
objects than necessary.
Also, improve the logging to only show that as tests the definitions
that have been recognized as such by test frameworks.
> Include only top level `ClassLike` as tests suites

- backend/src/main/scala/bloop/logging/AbstractLogger.scala
- backend/src/main/scala/bloop/logging/BufferedLogger.scala
- backend/src/main/scala/bloop/logging/Log4JLogger.scala
- backend/src/main/scala/bloop/logging/Logger.scala
It was very tedious to define new subclasses of `Logger`. We now have a
`Logger` base trait, and an `AbstractLogger` that defines all the
basic functionalities, making it much easier to add a new subclass of
`Logger`.
The old `Logger` is renamed to `Log4JLogger`.
> Improve logging abstraction, Hide L4J better

- backend/src/main/scala/bloop/ScalaInstance.scala
When creating a `ScalaInstance`, we check that the JARs that we're given
all exist. However, we don't handle the case where the array may be
empty. In this case, they all exist, but we'll create a `ScalaInstance`
with no JARs, which will crash the compiler down the road.
This commit fixes this issue by making us resolve the `ScalaInstance` if
we're given no JARs.
> Don't crash with empty `allJars` in ScalaInstance

- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/cli/CommonOptions.scala
- frontend/src/main/scala/bloop/engine/ExecutionContext.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/State.scala
- frontend/src/test/scala/bloop/engine/InterpreterSpec.scala
The `Configure` command is supposed to allow you to set up the global state
of the bloop server, variables like, say, the number of threads.
In the future, I expect this command to grow bigger and support other
global parameters that are similar to the one supported now.
> Fix #75: Add configure command to set up global state

- backend/src/main/scala/bloop/logging/BloopLogger.scala
- frontend/src/main/resources/log4j2.properties
- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/State.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/engine/InterpreterSpec.scala
- frontend/src/test/scala/bloop/logging/BloopLoggerSpec.scala
- frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
- frontend/src/test/scala/bloop/tasks/ProjectHelpers.scala
This commit makes us define the streams that should be used by an
instance of `BloopLogger` when constructing the logger. As a result, we
have a clearer relation between each CLI invocation and the assigned
logger, making it easier to have output be written to the correct
stream.
It also solves issues that we had with repeated output (output would be
written to the console as many times as we had loggers created).
> Allow to specify where `BloopLogger` should write

- backend/src/main/scala/bloop/logging/BloopLogger.scala
- frontend/src/test/scala/bloop/logging/BloopLoggerSpec.scala
Using Nailgun, we re-use loggers with the same name. This means that
between sessions, the old appenders will continue to exist for that
logger. Finally, Log4J will not add the appenders that we create if
appenders with the same name already exist for a given logger.
As a result, we were not adding the right appenders when re-using an
existing logger. This commit fixes that by removing all the current
appenders when creating a new instance of `BloopLogger`.
> Fix logging with Nailgun

- sbt-bloop/src/main/scala-sbt-0.13/bloop/DiscoveredSbtPlugins.scala
- sbt-bloop/src/main/scala-sbt-1.0/bloop/DiscoveredSbtPlugins.scala
- sbt-bloop/src/main/scala/bloop/SbtBloop.scala
This task always triggers compilation, because it doesn't rely on a
dynamic task as it should. This commit replaces the implementation of
this task in sbt-bloop by the same implementation that is used in sbt
1.0 (which is correct and uses a dynamic task).
Because this task is used in a resource generator that is present by
default, we would always trigger compilation when inspecting the
generated resources. This is no longer the case (except if the project
is an sbt plugin).
> Replace `discoveredSbtPlugins` in sbt 0.13

- frontend/src/test/resources/projects/with-resources/build.sbt
- frontend/src/test/resources/projects/with-resources/project/build.properties
- frontend/src/test/resources/projects/with-resources/src/main/resources/my-compile-resource.txt
- frontend/src/test/resources/projects/with-resources/src/main/scala/Main.scala
- frontend/src/test/resources/projects/with-resources/src/test/resources/my-test-resource.txt
- frontend/src/test/resources/projects/with-resources/src/test/scala/Test.scala
- frontend/src/test/scala/bloop/tasks/CompilationTaskTest.scala
- frontend/src/test/scala/bloop/tasks/ProjectHelpers.scala
- frontend/src/test/scala/bloop/tasks/RunTasksSpec.scala
- frontend/src/test/scala/bloop/tasks/TestResourcesSpec.scala
- project/BuildPlugin.scala
- project/TestPlugin.scala
- project/build.sbt
- sbt-bloop/src/main/scala-sbt-0.13/bloop/DiscoveredSbtPlugins.scala
- sbt-bloop/src/main/scala/bloop/SbtBloop.scala
The sbt plugin is adapted to run `copyResources` when generating the
configuration, which will copy the resources to the classes directory
(thus making them available when running and testing).
Our scripted setup is adapted to copy the generated sources and the
resources out of the scripted environment (scripted tests are run inside
a temporary directory).
Fixes #134
> Add support for resources in `run` and `test`

- frontend/src/main/scala/bloop/Cli.scala
```
[W]  [E1] /src/main/scala/bloop/Cli.scala
[W]       match may not be exhaustive.
[W]       It would fail on the following input: Right(Configure(_, _))
[W]       L88:             command match {
[W]                        ^
[E] /src/main/scala/bloop/Cli.scala: L88 [E1]
```
> Handle configure in Cli pattern matching

- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/cli/CliParsers.scala
- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/cli/ReporterKind.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/reporter/ReporterConfig.scala
I found `scalacstyle` a little bit confusing. Using `--reporter=scalac`
or `--reporter=bloop` is better IMO.
> Replace scalacstyle by `reporter` option

- README.md
- frontend/src/main/scala/bloop/Server.scala
@olafurpg has correctly pointed out in
https://github.com/scalacenter/bloop/issues/173 that if the user doesn't
write the right alias, Nailgun will throw at it a weird message.
We fix this by setting the default nail class, so that if the alias or
fqn that the user types is incorrect we automatically redirect to our
entrypoint `Cli`.
This should finally fix all usability issues that Nailgun places on us.
> Set the default nail class in case alias is incorrect

- project/BuildPlugin.scala
The Advisory Board does not provide or apportion funding. It merely
provides recommendations to the Scala Center on how to spend their
funds. There is an important legal distinction.
> Remove `Advisory Board` from banner message

- frontend/src/main/scala/bloop/testing/TestInternals.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/tasks/TestLoggingSpec.scala
- integration-tests/integration-projects/with-tests/src/test/scala/hello/WritingTest.scala
Otherwise, the output produced by tests on stdout and stderr is not
captured by the logger, and would get intertwined with other concurrent
test runs.
Fixes #158
> Use `MultiplexedStreams` for in-process testing

- README.md
As suggested here,
https://github.com/scalacenter/bloop/issues/100
Even if there's a better long-term solution, it would be good to merge
this so that nobody else hits the same problems I did.
> Change the `bloop` alias suggested in the installation instructions

- .drone.yml
It looks like we were no longer building PRs, only cloning.
> Build PRs in the CI

- project/GitUtils.scala
- project/ReleaseUtils.scala
It's easier and more reliable to pass the GitHub token via Drone than to
depend on a key that may or may not be present.
> Push Homebrew formula over HTTPS

- benchmarks/src/main/scala/bloop/ProjectBenchmark.scala
- frontend/src/test/scala/bloop/tasks/ProjectHelpers.scala
- project/BuildPlugin.scala
I don't remember why we don't write them to the default location. It just makes it annoying when testing with Nailgun afterwards.
> Write config to .bloop-config in integration tests

- build.sbt
- project/BuildPlugin.scala
- project/build.sbt
Bintray is so much nicer and faster. The slugishness of sbt-sonatype is
unbearable. We still publish to sonatype the sbt-bloop plugin because Bintray
does not allow to sync to Maven Central repositories that use the sbt plugin
repository layout.
> Use bintray to release everything

- bin/install.py
This is the repository where lsp4s lives. We need to tell coursier to
use it, otherwise we won't find this artifact.
Also, make the installation script executable.
> Add scalameta bintray repo in installation script

- project/ReleaseUtils.scala
Because we download coursier in `install.py`, it was installed along
with the rest of Bloop in our Homebrew formula.
The easiest solution is to just remove it before copying the files. The
harder would be to have a build dependency on coursier, and use a
different installations script that wouldn't download coursier.
> Remove `coursier` after building Homebrew formula

- frontend/src/main/scala/bloop/engine/State.scala
Otherwise, we would reuse an old logger, which had an extremely strange
impact on verbose mode.
> Set logger when loading cached State

- project/build.sbt
This is required for correctness. It turns out that Ivy fails to
download the `pom` for Zinc; probably because of the `+` in the version
number that gets escaped.
> Add `sbt-coursier` to our build

- build-integrations/sbt-0.13/build.sbt
This commit changed the structure of the projects to make it easier to
integrate with the rest of our benchmarking suite.
Currently, the benchmarks are broken because the scalac benchmark won't find the sources for the `library` project.
> Change commit to test for scala

- frontend/src/main/scala/bloop/Bloop.scala
This bug was undiscovered because we didn't have a `xxx.config` in any
of our benchmarks before, but now we do and Bloop tries to load it.
> Fix config directory in Bloop shell

- build-integrations/sbt-1.0/build.sbt
The change just removes sbt-whitesource, that cannot be resolved when
coursier is installed as a global plugin.
> Change commit to test for sbt

- build-integrations/sbt-1.0/build.sbt
Currently, sbt fails to load the project because of a bug in either
coursier or sbt. This changes the sha to apply a workaround.
> Fix commit sha for guardian/frontend

- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/reporter/ConfigurableReporter.scala
- frontend/src/main/scala/bloop/reporter/Reporter.scala
- frontend/src/main/scala/bloop/reporter/ReporterFormat.scala
Also, relativize the compilation error messages to the base of the build
instead of the base of the project.
Fixes #263
> Better shortening of path in compilation errors

- .drone.yml
- website/content/docs/developer-documentation.md
- website/content/docs/getting-started-sbt.md
The following sync adds the following changes:
1. Prettier button for "View on Github".
2. Reorganisation of "Edit on Github".
3. Use of labels instead of marks.
4. Decrease of font size for title (was too big).
5. Better `code` and `pre` style (more similar to GitHub's)
> Sync up with style changes in kube

- bin/install.py
Otherwise users cannot install the version until the release has hit
Maven Central.
> Add bintray repository to `install.py`

- README.md
- website/content/docs/bloop-basics.md
- website/content/docs/how-to-use-bloop.md
Link to our online documentation and only give a brief explanation of what
bloop is in the README. Shorter is better. In the future we can add more
specific developer docs in the README, but for now it's not necessary.
> Shorten and improve README

- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/test/scala/bloop/nailgun/BasicNailgunSpec.scala
- frontend/src/test/scala/bloop/nailgun/NailgunTest.scala
- website/content/docs/commands-reference.md
- website/content/docs/developer-documentation.md
This is probably not the best patch this repository has seen, but I'm
quite happy with being able to do it at all so I won't complain.
The CLI handling in bloop has to fundamentally change because it's
introducing a lot of complexity, but for now we can deal with this
complexity since there are more important blockers on the road to
success.
The issue in this commit is that, because case-app derives the CLI
parsers from case classes, we have to turn projects into an optional
argument and set it in our CLI interpreter if the `-p` or `--project`
flags have not been passsed.
This introduces the problem that we, as maintainers, could be creating
instances of these case classes with no specified project at all, but
there is no short-term solution to this problem rather than rewriting
the whole …
> Infer projects from cli remaining args

- frontend/src/main/scala/bloop/Server.scala
- project/Dependencies.scala
Two PRs got merged:
1. https://github.com/scalacenter/nailgun/pull/4
2. https://github.com/scalacenter/nailgun/pull/3
Accessible in https://github.com/scalacenter/nailgun/commits/bloop.
Release ebe7ab23 is already out.
> Upgrade to latest nailgun master ebe7ab23

- bin/install.py
- project/ReleaseUtils.scala
We used to put the variables that we insert at the very beginning of the
script, but we can no longer do this because this breaks with
`__future__` in Python that must appear before any actual code.
Fixes #334
> Fix versioned installation script

- bin/install.py
This PR removes the dependency on `future` and using only python standard library modules.
This should solve the install issue in https://github.com/scalacenter/bloop/issues/318#issuecomment-372673415
> Use only python stdlib in install.py

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- project/BuildPlugin.scala
- website/content/docs/getting-started-sbt.md
Fixes https://github.com/scalacenter/bloop/issues/341.
> Rename `installBloop` to `bloopInstall`

- .gitignore
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/logging/BloopLogger.scala
- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/Server.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/cli/CommonOptions.scala
- frontend/src/main/scala/bloop/engine/ClientPool.scala
- frontend/src/main/scala/bloop/engine/ExecutionContext.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/State.scala
- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/test/scala/bloop/logging/RecordingLogger.scala
- frontend/src/test/scala/bloop/nailgun/BasicNailgunSpec.scala
- frontend/src/test/scala/bloop/nailgun/NailgunTest.scala
Nailgun has this great concept of client listeners: closures that are called
whenever the nailgun server thinks that the client has disconnected. These
closures receive the kind of event that the nailgun server got, and executes
some logic.
This concept allows bloop to register callbacks that are run to clean
resources. Cleaning resources is paramount to keep the right behaviour of
long-running tasks like file watching and bsp servers.
This PR does three things:
1. Exposes the client listeners to the state, in a new abstraction called `ClientPool`.
2. It uses client listeners to cancel tasks, whenever the tasks accept cancellation.
3. Redesigns file watching in a Monix idiomatic style, with observables and
consumers that help us reason about file watching events more reasonably.
Fixes …
> Redesign file watching and add client listeners

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
Fixes https://github.com/scalacenter/bloop/issues/344.
We don't do what the ticket describes yet because that's something left
for the future. So far, reusing the `.bloop` directory (which should
already be in .gitignore) for the target makes sense.
In the future, we'll get the sbt integration to talk to the bsp server
of bloop and compile to that directory, making the experience of
switching from sbt to bloop and back and forth smooth.
> Use different classes directory than sbt

- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/test/scala/bloop/engine/InterpreterSpec.scala
- frontend/src/test/scala/bloop/nailgun/BasicNailgunSpec.scala
Now, the "Projects loaded from" is hidden behind the verbose flag.
Fixes https://github.com/scalacenter/bloop/issues/338.
> Pretty print projects to be script friendly

- frontend/src/main/scala/bloop/cli/ExitStatus.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
As the compilation task does not throw an exception, but rather we model
failures in the DAG, we need to propagate the error down the task
dependency chain so that tasks that depend on compilation do not continue
if compilation has failed.
In this vein, this commit aligns the codebase to behave like this, and then
avoid testing a project that has not correctly compiled.
> Propagate error to avoid downstream execution

- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/caches/StateCache.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- project/BuildPlugin.scala
Nailgun shuts down the executor service running the "server code"
whenever an exception is catched. This usually takes around 1000s after
the execption has been thrown.
This exception is thrown after a SIGKILL or SIGINT, for example. The
problem is that in 1000s our bloop tasks do not have time to return, and
that means that the `Await.result` in `Interpreter` never finishes.
Therefore, the logic never reaches `Cli` back, and the state is not
saved. This code is a temporary workaround thought to overcome this
limitation. It fixes the current problem in which the compilations that
happen in file watching are thrown away. Now they are cached, and
subsequent compile commands won't trigger compile afresh.
> Update the build in every watch iteration

- frontend/src/main/scala/bloop/engine/ExecutionContext.scala
Let's add one more core because the monix infrastructure steals us one
blocking. Blocking is something that computers can easily put on timers,
so this way we won't waste one core that could be used to compile.
> Add one more core to the available processors

- bin/install.py
It wouldn't prepend `v` when downloading the completions.
> Fix installation script for released versions

- website/content/docs/installation.md
Changes the installation instructions for other platforms to use generic `python` now that install scripts support both python 2 and 3.
This appears to be the last reference to `python2` in the project.
> Change python2 to python in install instructions

- frontend/src/main/scala/bloop/io/SourceWatcher.scala
This is causing misbehaviours in the terminals, because it sometimes
cleans the screen right after the compilation logs are outputted, and
therefore they are lost.
Fixes https://github.com/scalacenter/bloop/issues/379.
> Remove clean terminal before file watching

- frontend/src/main/scala/bloop/io/SourceWatcher.scala
Reverts scalacenter/bloop#381.
This wasn't the real reason apparently. Don't merge yet.
> Revert "Remove clean terminal before file watching"

- frontend/src/main/scala/bloop/engine/ExecutionContext.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/caches/StateCache.scala
- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/main/scala/bloop/monix/FoldLeftAsyncConsumer.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
Previously, `cancel` would not complete the task. This refactoring makes
sure that the task is cancelled and that the completion returns the last
state processed by the consumer.
Such improvement makes sure that there's no hanging task listening to file
watching events.
Fixes #379.
> Ensure that file watching task exits

- build.sbt
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
The main issue with source deps in Bloop arises from the fact that, by
design, `bloopConfigDir` is build dependent, which means that it changes
across different source deps.
We don't want this to be the case for source dependencies though, since
Bloop needs all the project dependencies to be in the same directory.
For that reason, this flag aggregates the bloop config files to be
written to the same bloop configuration directory, and hence have it
work nicely with bloop.
Fixes #375.
> Add flag to support source dependencies

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
> Shorten generation logs in sbt

- website/content/docs/how-to-use-bloop.md
- website/content/docs/installation.md
Adds improvements in nailgun that fix https://github.com/scalacenter/bloop/issues/320.
> Add support for `bloop server`

- bin/stream-jenkins-log.sh
- frontend/src/test/scala/bloop/nailgun/BasicNailgunSpec.scala
This fails spuriously on Windows and it's quite annoying. I want to
disable it for now until we get perfect support for concurrent clients.
> Disable spurious test

- frontend/src/main/scala/bloop/Project.scala
- frontend/src/test/scala/bloop/logging/RecordingLogger.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
1. Prettify exception reporting.
2. Stringify `null` in `RecordingLogger` to catch spurious test errors in CI.
3. Use build base directory to shorten paths.
4. Tell users to regenerate configuration files if `classpathOptions` is missing.
All has been tested locally.
> Add batch of last minute improvements

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- project/BuildPlugin.scala
I detect this problem when using bloop. The configuration of the project
reference is important because a classpath dependency may point to an
arbitrary project dependency. An example of this is the "compile->test"
dependency to frontend from our `benchmark` project.
To solve this issue, we need to select the right name from the
configuration of the project ref, and only fallback to the configuration
of the scoped running task when that one is empty.
> Detect "compile->test" configurations in sbt

- build-integrations/global/plugins.sbt
- build-integrations/global/src/main/scala/bloop/build/integrations/IntegrationPlugin.scala
- build-integrations/sbt-1.0/.sbtopts
- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/cli/CliOptions.scala
- frontend/src/test/scala/bloop/bsp/BspClientTest.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/nailgun/NailgunTest.scala
- frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
- frontend/src/test/scala/bloop/tasks/ProjectHelpers.scala
- integrations/maven-bloop/src/main/java/bloop/integrations/maven/BloopMojo.java
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- project/BuildPlugin.scala
- website/content/docs/commands-reference.md
- website/content/docs/installation.md
- website/content/faq/_index.md
I noticed that our `integrationSetUpBloop` was displaying logs with the
paths shortened, when they shouldn't because all the configuration files
are written in the staging sbt directory (because they are source deps).
This commit fixes it.
> Add improvements to sbt plugin and migrate to `.bloop`

- README.md
Hi! Small nitpick: clicking on Gitter badge goes to the badge, instead of joining the room.
> Setup link on Gitter badge

- .drone.yml
- build.sbt
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/stale-projects/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/stale-projects/changes/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/stale-projects/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/stale-projects/test
- project/BuildPlugin.scala
- project/build.sbt
- website/content/faq/_index.md
Fixes #104.
* Use `transformState` to remove configuration files at the very end.
* Test with scripted that we remove stale configuration files.
* Change signature of `bloopGenerate` to return the path of configuration file that it writes to.
* Add a faq to the docs.
> Remove stale configuration files

- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/Server.scala
- frontend/src/main/scala/bloop/engine/State.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- project/Dependencies.scala
\+ update to latest nailgun.
Previously, bloop would persist the analysis file on `shutDown`.
However, this hook has been removed upstream in
https://github.com/facebook/nailgun/pull/131.
As a result, we take another (more resilient) strategy to persist the
analysis file. We persist analysis file on the io pool after every
`Interpreter` execution, without blocking the return of the request.
All the logs are redirected to the nailgun server output.
> Persist analysis files on the background & in parallel

- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/main/scala/bloop/Project.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
Our project abstraction only accepted source directories. This
limitation is unfounded and makes it difficult to support build tools
whose project definitions have no source directories. One example of
such a build tool is Bazel, whose `Target`s only know about source
files.
This patch:
1. Renames `sourceDirectories` in the source code.
2. Makes the rest of the code (`Tasks` and `SourceWatcher`) aware that
sources does not strictly mean directories.
3. Build upon @rberenguel's work to show the same "Watching ..." message
in every watch iteration.
> Generalize `sourceDirectories` to `sources`

- project/ReleaseUtils.scala
Our homebrew formula download Coursier from the installation script.
Sometimes, this fails because it looks like some versions of MacOS have
an outdated version of Python 2 with a faulty SSL module (or something
along those lines).
This commit forces Python3 to be used for running the installation
script from the Homebrew formula, so that downloading Coursier no longer
fails.
> Use Python3 in Homebrew formula

- etc/bash/bloop
- etc/zsh/_bloop
This will hide the error if attempting a tab completion to bloop while
the bloop server has not been started, and will offer the single
completion of `bloop server` instead.
Someone might like to do the same thing for bash....
> Simple improvement to zsh completion when server is not started

- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/cli/validation/Validate.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/testing/TestInternals.scala
- frontend/src/test/scala/bloop/cli/validation/ValidateSuite.scala
- frontend/src/test/scala/bloop/nailgun/BasicNailgunSpec.scala
- frontend/src/test/scala/bloop/testing/TestOptionsSpec.scala
1. Resolve test agent jars lazily.
2. Allow to pass in test options via CLI.
3. Handle NPE in bsp CLI validator.
> Improve deficiencies in test infrastructure

- backend/src/main/scala/bloop/reporter/DefaultReporterFormat.scala
- backend/src/main/scala/sbt/internal/inc/bloop/ZincInternals.scala
- frontend/src/main/scala/bloop/logging/BspLogger.scala
The trick to get access to this info was in downcasting to the internal
position in Zinc's land that exposes `startPosition` and `endPosition`,
meaning the start and end of the column count.
With this information, Intellij is now able to show the red squigglies
in the editor.
I couldn't resist, thanks @olafurpg for the reminder and @jastice for getting
my excitement up with the comment on red squigglies.
> Use range positions in bsp if Zinc returns them

- frontend/src/main/scala/bloop/Project.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- project/Dependencies.scala
1. Fixes a bug in loading analysis files at server startup. 
2. Add project dependencies to build targets (to get the language server working).
3. Add `ScalaBuildTarget` to the build target bytes so that Intellij knows what Scala SDK to use for each project.
> Add `ScalaBuildTarget` and project deps to bsp

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
The conflicting plugin appears to be sbt-metals 🌵 See https://github.com/scalameta/metals/pull/266 :trollface: 
/cc @Duhemm
> Fix reference to the bloop Compat which gets mixed up with sbt.Compat

- etc/bash/bloop
- etc/zsh/_bloop
- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/cli/completion/Mode.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
> Improve autocompletion for zsh to be more context-aware for #356

- frontend/src/main/scala/bloop/Project.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
The first time the server starts up is a little bit slow (2s for the bloop
project, 3s for the spark project) because Bloop needs to load up the analysis
file from disk. This process was sequential. This patch makes it parallel, and
also runs the whole load process in the io executor which is thread-unbounded.
> Speed up first bloop server load

- bin/install.py
- etc/systemd/bloop.service
- website/content/docs/installation.md
Adds a user service file for systemd and makes `install.py` download it
automatically to `~/.bloop/systemd/bloop.service`.
Updates the documentation with steps needed to enable this service.
Fixes systemd part of #337. A Desktop Entry solution will follow (most likely).
> Add systemd service file

- build-integrations/sbt-1.0/.sbtopts
- build-integrations/sbt-1.0/build.sbt
- build-integrations/sbt-1.0/project/Integrations.scala
- build-integrations/sbt-1.0/project/build.properties
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/bar/src/test/scala/BTest.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/baz/src/main/scala/C.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/foo/src/main/scala/A.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/foo/src/test/scala/ATest.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/test
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/woo/src/test/scala/D.scala
- project/BuildPlugin.scala
- project/build.properties
Use `Classpaths.mapped` from sbt to parse classpath configuration dependencies
*only* for compile/test dependencies.
> Add akka and detect 'test->compile' and 'compile->test' better

- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
If users want the non-existing directories to be picked up by bloop they
need to run `bloop compile blabla -w` again.
> Filter out directories that don't exist

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/StraySourceFile.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/test
We are supporting all kind of source files and dirs in main bloop, but
we were not adding source files to our sources field in the json config.
Fixes #428.
> Add source files to bloop config from sbt

- config/src/main/scala-2.10/bloop/config/ConfigEncoders.scala
- config/src/main/scala-2.12/bloop/config/ConfigDecoders.scala
- config/src/main/scala-2.12/bloop/config/ConfigEncoders.scala
- config/src/main/scala/bloop/config/Config.scala
- config/src/test/scala-2.12/bloop/config/JsonSpec.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- website/static/bloop-schema.json
The compile order is important because many projects define their own
compile order and that changes the semantics of compilation.
Let's add this option under a `CompileOptions` field in our bloop config
file. This new field will in the future, before 1.0.0, host
`classpathOptions` which seems kinda out of place. But for now, we
abstain ourselves from making this breaking change.
> Add compile order option to the bloop config

- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
I have no idea why this hasn't been caught sooner, but
https://ci.scala-lang.org/scalacenter/bloop/3062/11 seems to point out
that as 6 directories don't exist within `with-tests`, we only print
that we're watching 2.
So let's see what happens with two.
> Make sure we always create source dirs in tests

- frontend/src/main/scala/bloop/cli/completion/Case.scala
We were not kebabizing the name of the arguments, only the extra names,
which lead to wrong completion (like `--configDir` for instance).
This commit changes that behavior, so that we kebabize the name and the
extra names of the arguments of commands.
> Kebabize arg names

- website/content/docs/developer-documentation.md
- website/content/docs/installation.md
#472 introduced a new `install.py` parameter: `--coursier` (or `-c`).
> Mention --coursier in developer documentation [DOCS]

- website/content/docs/commands-reference.md
Under the run command, the description and example says test, when it should say run.
> Fix typo in commands-reference

- build.sbt
- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/cli/CliParsers.scala
- project/Dependencies.scala
Strategy:
* Cache expensive implicits that are generated by implicit search.
* Replace by custom version of shapeless and case-app that are faster.
> Speed up compilation speed of `frontend` by 8x

- integrations/maven-bloop/src/main/java/bloop/integrations/maven/BloopMojo.java
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
Fixes one part of https://github.com/scalacenter/bloop/issues/507, the exception in Maven. (#507 is also about the generated bloop files, which should not depend on non-scala projects.)
I'd love to also provide a (integration) test case for this fix, but unfortunately creating the ground for integration tests in sbt is beyond my current scope. (@tues offered to look into that.)
> Early abort execution when no supported scala plugin was found

- build-integrations/global/src/main/scala/bloop/build/integrations/IntegrationPlugin.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-configurations/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-configurations/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-configurations/test
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/lagom-compat/.sbtopts
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/lagom-compat/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/lagom-compat/hello-impl/src/test/resources/logback.xml
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/lagom-compat/project/build.properties
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/lagom-compat/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/lagom-compat/test
To make use of this, one needs to add something along these lines:
```
import bloop.integrations.sbt.BloopDefaults
inConfig(IntegrationTest)(BloopDefaults.configSettings)
```
to project-local settings (preferably a .gitignored `local.sbt`).
TODO:
Closes #505.
> Sbt: Export custom configurations

- website/content/docs/sbt.md
- website/content/faq/_index.md
Add the docs for #512:
* Update links to `bloopTargetDir` in the FAQ
* Add new page "Advanced sbt configuration" and describe how to export custom sbt configurations
* Add a FAQ entry about custom sbt configurations
> Docs: Advanced sbt configuration

- backend/src/main/scala/bloop/ScalaInstance.scala
- build.sbt
- config/src/main/scala/bloop/config/Config.scala
- config/src/test/scala-2.12/bloop/config/JsonSpec.scala
- frontend/src/main/scala/bloop/Project.scala
- frontend/src/test/scala/bloop/engine/LoadProjectSpec.scala
- project/BuildPlugin.scala
This commit allows Bloop to load up projects that don't have any Scala
setup. This can happen when build tools like Maven want to generate
configuration files for java-only projects.
This could have been workarounded by creating default scala options from
the build tool side, but that's uglier and slower than just setting all
the fields of the `Scala` setup to empty because if there is no default
scala instance defined it would need to be resolved to fill in the `scalaJars`
field. 
This is a quick fix to unblock @lefou.
The ideal would be to modify the configuration file format to allow for
an optional scala setup, but that change would be quite breaking and
would conflict with some contributors' efforts that are already
undergoing. I think it's something we need to do anyway, so I'll …
> Allow the project load of non-Scala projects

- build-integrations/sbt-0.13/project/Integrations.scala
- integrations/sbt-bloop/src/main/scala-sbt-1.0/bloop/integrations/sbt/Compat.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/meta-builds/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/meta-builds/changes/set-sources.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/meta-builds/project/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/meta-builds/test
This means that if you add the plugin as a global plugin OR as a plugin of
your meta project, Bloop will automatically generate the bloop
configuration files when it reloads.
This generation is super fast because meta projects are usually really
small and they only have one build.
> Export configurations of sbt meta builds automatically

- project/BuildPlugin.scala
- website/content/docs/developer-documentation.md
It's not that obvious how to run Bloop server directly from sbt and how to enable debugging for forked processes. Hopefully these instructions will save people some time figuring things out.
> Add debugging instructions to developer documentation [DOCS]

- build.sbt
- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
- project/BuildPlugin.scala
- project/Dependencies.scala
Adds a `bloop.integrations.mill.BloopModule` mill external module that can be used to generate bloop config from mill. The support is limited to JVM modules at the moment, and does not fill the "resolution" configuration element.
See https://www.lihaoyi.com/mill/page/modules.html#external-modules
1. add ```import $ivy.`ch.epfl.scala::mill-bloop:$bloopVersion` ``` to the build.sc of a project (it's probably possible to add it to a `~/.mill/ammonite/predef.sc` or a similar file instead)
2. run `mill bloop.integrations.mill.BloopModule/install` from the directory of the mill project.
Due to some [obscure bug](https://gitter.im/scalacenter/bloop?at=5b1ba015144c8c6fea8223c9) that prevents me from safely running non-brewed bloop, I'm only able to run `1.0.0-M10`, which fails to run the tests on …
> Add basic mill integration

- build.sbt
I've manually published `mill-bloop` for M11.
> Publish `mill-bloop` when doing `releaseBloop`

- backend/src/main/scala/bloop/logging/BloopLogger.scala
- benchmarks/src/main/scala/bloop/logging/BloopLoggerBenchmark.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/cli/CliOptions.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/engine/InterpreterSpec.scala
- frontend/src/test/scala/bloop/logging/BloopLoggerSpec.scala
> Add the possibility to disable color 

- project/Dependencies.scala
The new version includes a fix for a linking error in JDK10.
Fixes #584.
/cc @rom1dep
> Upgrade to NuProcess 1.2.4

- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
Fixes https://github.com/scalacenter/bloop/issues/578.
This commit does not implement `--cascade`, a new ticket is open for
that and will be added in 1.1.0
https://github.com/scalacenter/bloop/issues/589.
> Remove `--isolated` and add `--propagate` / `--include-dependencies`

- build-integrations/global/plugins.sbt
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/test
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/yay/src/test/scala/D.scala
Fixes https://github.com/scalacenter/bloop/issues/599.
The fix is just obvious: it doesn't use `configuration` when no
configuration is used, and instead relies on the default `Compile`.
> Remove default dependency between test sources

- bin/run-benchmarks.sh
The previous projects were not being benchmarked after the experiments with
pipelined compilation. Let's get a solid baseline with these projects and then
improve bloop from there.
> Enable old project in benchmarks again

- project/ReleaseUtils.scala
Alright, I think that the issue that was causing so many problems is that I was doing chmod 0777 on `log/bloop` but not on `log`. This should fix it.
> Fix permissions in Brew formula

- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/logging/PublisherLogger.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
- project/Dependencies.scala
Does three things:
1. Updates to another version of directory-watcher that exposes an
internal method. We use this internal method to fix the linked
ticket; Bloop now watches the parent directories of source files in a
non-recursive way.
2. Re-engineers the tests for file watching using the Task APIs and
making it easier to test.
3. Adds a new test to make sure that https://github.com/scalacenter/bloop/issues/598 is fixed.
> Watch changes in single files

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
This avoids an exception when an extension method in syntax.scala tries to look up the JavaPluginConvention for a project that doesn't have one.
> Ignore non-Scala and non-Java project dependencies

- frontend/src/main/scala/bloop/engine/Interpreter.scala
Adding a clear screen just before forcing the first execution of file watch task
> Make compile watch clear screen before first run

- project/ReleaseUtils.scala
Fixes #629, #646. At least unless someone removes these files manually
and then restarts Bloop service.
> Homebrew: Touch log files to ensure correct owner

- bin/install.py
Hopefully this will make it easier to diagnose issues such as #650 in the future.
Also update `COURSIER_URL`: both http://get-coursier.io and https://github.com/alexarchambault/coursier redirect to https://github.com/coursier/coursier.
> Print error if download fails in install.py

- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/test/scala/bloop/tasks/CleanTaskSpec.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
- website/content/docs/commands-reference.md
Also add `CleanTaskSpec`, fix documentation and remove some unused variables/parameters.
Closes #593.
> Clean all projects by default

- website/content/docs/developer-documentation.md
Just making it very explicit that you need to `git clone --recursive https://github.com/scalacenter/bloop.git` in this section, since it tripped me up.
> [DOCS] add git clone instructions to 'Opening up our sbt build' section

- bin/install.py
- build.sbt
- project/BuildPlugin.scala
- project/ReleaseUtils.scala
- website/content/docs/developer-documentation.md
After this change, we generate a local homebrew formula in the `install`
sbt command so that we can install local bloop versions with homebrew.
> Add support for local homebrew formulas

- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
Fixes https://github.com/scalacenter/bloop/issues/662
> Apply system properties to all test framworks

- backend/src/main/scala/bloop/CompileMode.scala
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/CompilerOracle.scala
- backend/src/main/scala/bloop/JavaSignal.scala
- backend/src/main/scala/sbt/internal/inc/bloop/BloopZincCompiler.scala
- backend/src/main/scala/sbt/internal/inc/bloop/CompileMode.scala
- backend/src/main/scala/sbt/internal/inc/bloop/JavaSignal.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopHighLevelCompiler.scala
- benchmarks/src/main/scala/bloop/HotBloopBenchmark.scala
- benchmarks/src/main/scala/bloop/ParallelUtestBenchmark.scala
- build-integrations/sbt-0.13/project/Integrations.scala
- build-integrations/sbt-1.0/project/Integrations.scala
- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/Dag.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileResult.scala
- frontend/src/test/scala/bloop/engine/DagSpec.scala
- frontend/src/test/scala/bloop/tasks/CleanTaskSpec.scala
- frontend/src/test/scala/bloop/tasks/CompilationTaskTest.scala
- frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
- frontend/src/test/scala/bloop/tasks/TestTaskTest.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
- project/BuildPlugin.scala
To make scalac and javac independent, we pass the transitive java
sources of a project to the scalac compiler so that it populates the
symbol table from source instead than from class files.
As a plus, thanks to this independence between scala and java
compilation in the same target, when javac does not depend on the scala
sources (java->scala), we can run scalac and javac in parallel.
The approach taken in this PR is still less than optimal because we're
passing all the transitive java sources to scalac. A better approach
that I'll try later is to pass only the transitive java sources of those
javac compilers that have not yet finished, removing any kind of
overhead.
This change has only required two changes in our community build: one in
akka and the other one in apache/spark, and those …
> Make scalac and javac independent under pipelining

- bin/run-benchmarks.sh
And compile all guardian/frontend and akka/akka (we were not compiling
their test suites before).
This will take a long time to run.
> Enable benchmarks for more projects

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
We took the easy route before and returned the normal Scala version in
lieu of the proper Scala binary version.
Fixes #677.
> Return the scala binary version via bsp

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/bsp/BspServer.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/main/scala/bloop/logging/BspClientLogger.scala
- frontend/src/main/scala/bloop/logging/BspServerLogger.scala
- frontend/src/main/scala/bloop/reporter/BspReporter.scala
- frontend/src/main/scala/bloop/testing/TestSuiteEvent.scala
- frontend/src/test/scala/bloop/ClasspathHashingTest.scala
- frontend/src/test/scala/bloop/bsp/BspClientTest.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- project/Dependencies.scala
This pull request upgrades to 1.0.0 to implements its new methods, which we didn't implement because Intellij didn't implement us yet. However, as they start to be implemented in IntelliJ and other clients, we add the implementations so that the existing clients, like IntelliJ or [Metals](https://github.com/scalameta/metals/), can start benefiting from them.
We miss the following items to be fully implementing BSP 1.0.0:
Alongside these missing items, I'd like to implement request buffering in bloop so that the clients can indiscriminately send request without taking into account whether they finished or not. I suspect this is not going to be easy.
I'm not sure yet how I'm going to organize my work to implement the missing entrypoints, but it's likely I will not do everything in this PR. …
> Use bsp 1.0.0 and implements its new methods

- frontend/src/main/scala/bloop/cli/ExitStatus.scala
- frontend/src/test/scala/bloop/tasks/CompilationTaskTest.scala
- frontend/src/test/scala/bloop/tasks/RunTasksSpec.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
Fix an issue where bloop would run `test` or `run` even if `compile`
failed. This issue happened because of a bad initialization error in the
`ExitStatus` object that was causing `codeToName` not to work. This
affected the following logic in `Interpreter`:
```
runCompile(cmd, state, project, deduplicateFailures, excludeRoot).flatMap { compiled =>
if (compiled.status != ExitStatus.CompilationError) next(compiled)
else Task.now(state.withDebug(s"Failed compilation for $project. Skipping $nextAction..."))
}
```
After the change to the exit status, the test passes.
> Initialize internal exit status list after sourcecode

- frontend/src/main/scala/bloop/logging/BspClientLogger.scala
I assumed scribe loggers couldn't trace messages, as trace is only used
for exception in sbt loggers (which we implement in bloop). Now we
redirect to debug instead of error.
> Don't error on trace message

- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- project/Dependencies.scala
With the introduction of bsp4j, we've realized that the dependency sources params didn't have the correct name for one of the fields, causing an error at runtime. By upgrading to a version of bsp4s that fixes it, we can keep on with our lives.
> Upgrade to latest bsp version

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/sbt-plugin-build/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/sbt-plugin-build/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/sbt-plugin-build/project/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/sbt-plugin-build/test
I knew about the possibility of failing in builds of single sbt plugins,
but however didn't protect us against them because I hoped sbt would
expose an entry point to know for real if a project is a meta build or
not. As this hasn't been the case, I've implemented a simple heuristic
to know whether a build is a meta-project or not: check if the cwd is
the same as the root of the build.
Kudos to @olafurpg for finding this bug in sbt-scalafix.
> Don't fail in builds of single sbt plugins

- backend/src/main/scala/sbt/internal/inc/bloop/ZincInternals.scala
- backend/src/test/scala/bloop/logging/RecordingLogger.scala
- frontend/src/main/scala/bloop/bsp/ProjectUris.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/logging/BspServerLogger.scala
- frontend/src/test/resources/cross-test-build-0.6/build.sbt
- frontend/src/test/resources/cross-test-build-0.6/test-project/shared/src/main/scala/hello/App.scala
- frontend/src/test/resources/cross-test-build-0.6/test-project/shared/src/main/scala/hello/Hello.scala
- frontend/src/test/scala/bloop/bsp/BspClientTest.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/bsp/ProjectUrisSpec.scala
- frontend/src/test/scala/bloop/nailgun/NailgunSpec.scala
- frontend/src/test/scala/bloop/nailgun/NailgunTestUtils.scala
- frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
- frontend/src/test/scala/com/martiansoftware/nailgun/BloopThreadLocalInputStream.scala
1. We use our test resource project for the BSP test suite
2. We fix regression showing a syntactic error as a log instead of diagnostic
3. We refactor the nailgun specification so that it passes when run by bloop
More information in the commit messages.
> Publish diagnostics for syntax errors and improve tests

- frontend/src/main/scala/bloop/engine/Feedback.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
Currently, the following error is triggered when specifying a valid
class that is not defined in the project:
```shell
$ bloop run root -m play.core.server.ProdServerStart
[E] Missing main class  in project 'root'
```
Simplify the logic of `findMainClasses()`. The validation logic is
redundant since specifying an invalid main class will be caught at a
later point:
```shell
$ bloop run root -m test
[E] Error: Could not find or load main class test
```
> Interpreter: Allow to run externally-defined main classes

- website/static/bloop-schema.json
See review in https://github.com/scalacenter/bloop/pull/722
> Update schema docs for `sources`

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/main/scala/bloop/logging/BspServerLogger.scala
- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/test/scala/bloop/bsp/BspClientTest.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/tasks/JsTestSpec.scala
- frontend/src/test/scala/bloop/tasks/JvmTestSpec.scala
... and use the correct file URI schema for the files in the diagnostics notifications. More info in the commit messages.
> Re-publish all warnings on BSP server startup

- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/jsenv/NodeJsEnv.scala
- frontend/src/main/scala/bloop/exec/Forker.scala
> Terminate processes gracefully

- frontend/src/main/scala/bloop/engine/Build.scala
- frontend/src/main/scala/bloop/engine/Dag.scala
- frontend/src/main/scala/bloop/engine/Feedback.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/test/scala/bloop/engine/DagSpec.scala
- frontend/src/test/scala/bloop/engine/LoadProjectSpec.scala
- frontend/src/test/scala/bloop/tasks/CompileSpec.scala
Imagine that `bloopInstall` fails to successfully complete. The process
did complete for a subset of the build graph, but not all of it. And now
imagine that the errors are not relevant and the user is willing to
ignore them temporarily. Isn't it frustrating that bloop will fail to do
anything with a `NoSuchElementException` because the build load fails?
This commit tries to improve on this situation by not making it an
all-or-nothing situation. Bloop can now handle missing dependencies in a
configuration file gracefully. To let the user know that there's
something off, though, we emit a warning every time we compile a module
that has a missing dependency (in case, for example, there's a failure
in compilation). However, we do not emit such warning if the user
compiles other modules in …
> Handle build load errors gracefully in the server

- bridges/scala-native/src/main/scala/bloop/scalanative/NativeBridge.scala
- bridges/scalajs-0.6/src/main/scala/bloop/scalajs/JsBridge.scala
- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/JsBridge.scala
- config/src/main/scala/bloop/config/Config.scala
- config/src/main/scala/bloop/config/util/ConfigUtil.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/engine/DagSpec.scala
- frontend/src/test/scala/bloop/exec/ForkerSpec.scala
- frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
- frontend/src/test/scala/bloop/tasks/JsTestSpec.scala
- frontend/src/test/scala/bloop/tasks/JvmTestSpec.scala
- frontend/src/test/scala/bloop/tasks/TestResourcesSpec.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- project/BuildPlugin.scala
Resources are files that are used at runtime, either when testing or
running an application. These files can be generated by the build tool
or be present in a resource directory of a project.
Resource files have been supported in bloop since 1.0, where in sbt and
other build tools we were relying on the resources to be copied by the
build tool to the classes directory. This approach had a problem:
whenever a change is done in an unmanaged resource file (a file that is
controlled by the user, like a `log4j2.properties` file), bloop would
not pick it up until there's a new `bloopInstall` invocation.
This is a known limitation that this commit fixes. The approach to
support resources has changed:
1. A new `resources` field has been added to the JSON file.
2. Resources are not copied to the …
> Add resources to the configuration file

- config/src/main/scala/bloop/config/Config.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/test/resources/cross-test-build-0.6/build.sbt
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
Otherwise test execution fails.
Fixes https://github.com/scalacenter/bloop/issues/658
> Create target path of `-h` ScalaTest test option

- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/tasks/RunSpec.scala
Add a test case that works with the previous implementation.
See discussion in https://github.com/scalacenter/bloop/issues/738
> Prove transitive resources used in aggregated projects

- frontend/src/main/scala/bloop/util/ProxySetup.scala
URL refuse to parse socks protocol.  So replace it by URI.
> Correct socks uri parsing

- bridges/scalajs-0.6/src/main/scala/bloop/scalajs/JsBridge.scala
- bridges/scalajs-0.6/src/test/scala/bloop/scalajs/ScalaJsToolchainSpec.scala
- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/JsBridge.scala
- frontend/src/main/scala/bloop/engine/tasks/LinkTask.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaJsToolchain.scala
- frontend/src/test/resources/cross-test-build-0.6/build.sbt
- frontend/src/test/resources/cross-test-build-0.6/test-project/js/src/main/scala/hello/DefaultApp.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/tasks/JsTestSpec.scala
- frontend/src/test/scala/bloop/tasks/RunSpec.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
> Propagate main class in sbt plugin

- backend/src/main/scala/bloop/reporter/Reporter.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopHighLevelCompiler.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/main/scala/bloop/reporter/LogReporter.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- website/content/docs/installation.md
1. Add project name in compilation logs.
2. Remove classes directory in compilation logs.
3. Add timings about compiler iterations.
Fixes https://github.com/scalacenter/bloop/issues/386
Fixes https://github.com/scalacenter/bloop/issues/258
> Improve compilation reporting to users

- project/BuildPlugin.scala
- project/Dependencies.scala
The python nailgun client allows to run the bloop server when it's an
executable (a script) and not a jar so that running `bloop server` in
systems such as Nix works and doesn't fail with an error.
This mechanism is only a fallback iff the invocation with `java -jar`
failed.
> Fallback to direct server invocation in nailgun client

- bin/install.py
- project/ReleaseUtils.scala
This fix uses the godsend `/usr/libexec/java_home` to detect the java
home for 1.8 and use that one to run `coursier launch` (failing with a
helpful error message if it doesn't find it). The main idea here comes
from @olafurpg and some of the discussion of the bug
In reality, this means that the server must be run with Java 1.8 or it
will fail. This is a good compromise for now until we can ensure that
we are as efficient and correct in other Java versions as we're in Java
1.8. I've tested this in my machine where Java 8 is installed via jenv
(which doesn't set the java home variable directly) and Java 11 was
installed via homebrew casks. I believe this scenario stresses this fix
enough to make it valid.
For now, we only use this approach in Mac OS because libexec/java_home
only exist in …
> Don't fail bloop if Java 11 installed in Mac OS

- .gitignore
- bin/install.py
- build.sbt
- docs/tools/scoop/install.md
- docs/tools/scoop/usage.md
- project/BuildPlugin.scala
- project/Dependencies.scala
- project/GradleIntegration.scala
- project/ReleaseUtils.scala
- website/i18n/en.json
- website/static/scripts/build-tools.js
- website/static/scripts/tools.js
- website/tools.yml
1. Configure a scoop-based installation for Windows Powershell users.
2. Improve the ergonomics of Windows CMD users.
3. Fix several bugs with the installation script and the nailgun script.
4. Fix a bug in the build when running gradle in Windows.
5. Improve the UX of the installation page by persisting the choices to
the session storage.
The fixed tickets are linked in the commit messages.
> Fix installation bugs and add Windows installation

- .drone.yml
- backend/src/main/scala/bloop/ScalaInstance.scala
- backend/src/main/scala/bloop/io/Paths.scala
- bin/install.py
- build.sbt
- config/src/main/scala/bloop/config/Config.scala
- docs/src/main/scala/bloop/docs/Sonatype.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/cli/ExitStatus.scala
- frontend/src/main/scala/bloop/cli/validation/Validate.scala
- frontend/src/main/scala/bloop/engine/Build.scala
- frontend/src/main/scala/bloop/engine/Dag.scala
- frontend/src/main/scala/bloop/engine/Feedback.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/cli/validation/ValidateSuite.scala
- frontend/src/test/scala/bloop/engine/DagSpec.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/exec/ForkerSpec.scala
- frontend/src/test/scala/bloop/nailgun/NailgunSpec.scala
- frontend/src/test/scala/bloop/tasks/CompileSpec.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
- notes/v1.1.2.md
- project/BuildPlugin.scala
- project/build.properties
See https://github.com/scalameta/metals/issues/396 for the issue that
triggered work on this area. Even if recursive dependencies is a fatal
error for bloop, we still handle gracefully and connect successfully
during a bsp connection. Builds that have problems will get:
1. An empty response to `workspace/buildTargets`.
2. A `build/showMessage` per every error found.
> Handle recursive dependencies gracefully

- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
The test is implicit in iteration 4 of the compile bsp test.
Fixes #762
> Report `noDiagnostics` if file doesn't exist

- build.sbt
- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
- project/Dependencies.scala
This bumps the mill dependency to the current version and adds the `publishLocal` step to the `"install"` alias.
> Updated mill version 0.2.6 -> 0.3.5

- .drone.yml
- docs/launcher.md
- docs/server.md
- docs/src/main/scala/bloop/Docs.scala
- docs/tools/homebrew/usage.md
- docs/tools/nix/usage.md
- docs/tools/scoop/usage.md
- docs/tools/universal/usage.md
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/exec/Forker.scala
- frontend/src/main/scala/bloop/testing/TestInternals.scala
- frontend/src/test/scala/bloop/exec/ForkerSpec.scala
- frontend/src/test/scala/bloop/tasks/JvmTestSpec.scala
- project/Dependencies.scala
- website/i18n/en.json
- website/pages/en/setup.js
- website/sidebars.json
- website/static/css/index.css
Information in the commit messages. In a nutshell:
1. Allow users to pass jvm options prefixed with `-J` for test and run as normal app arguments.
1. Support `-J` arguments in the `bloop server` invocations and document them.
1. Read jvm opts from a `.jvmopts` file in the bloop installation directory by default.
Fixes https://github.com/scalacenter/bloop/issues/761
Fixes https://github.com/scalacenter/bloop/issues/565
> Improve handling of `-J` arguments and jvm options

- .drone.yml
- bridges/scala-native/src/test/scala/bloop/scalanative/ScalaNativeToolchainSpec.scala
- bridges/scalajs-0.6/src/test/scala/bloop/scalajs/ScalaJsToolchainSpec.scala
- bridges/scalajs-1.0/src/test/scala/bloop/scalajs/ScalaJsToolchainSpec.scala
- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/engine/Dag.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileResult.scala
- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/test/scala/bloop/bsp/BspClientTest.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/engine/DagSpec.scala
- frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/tasks/CompileSpec.scala
- frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
- frontend/src/test/scala/bloop/tasks/JsTestSpec.scala
- frontend/src/test/scala/bloop/tasks/JvmTestSpec.scala
- frontend/src/test/scala/bloop/tasks/RunSpec.scala
- frontend/src/test/scala/bloop/tasks/TestResourcesSpec.scala
- frontend/src/test/scala/bloop/tasks/TestUtil.scala
- frontend/src/test/scala/bloop/testing/TestFilterSpec.scala
- frontend/src/test/scala/bloop/testing/TestOptionsSpec.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
Superseeds https://github.com/scalacenter/bloop/pull/667
> Compile, test and run several projects in one command

- etc/bash/bloop
- etc/fish/bloop.fish
- etc/zsh/_bloop
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/test/scala/bloop/tasks/JsTestSpec.scala
- frontend/src/test/scala/bloop/tasks/JvmTestSpec.scala
This PR enables
- bloop server to respond tests FQCN in a project to a testsfqcn autocomplete request like `bloop autocomplete --format <shell> --mode testsfqcn --project <project>`
- bash/zsh/fish to autocomplete test names after `bloop test <project> --only`
<details>
<summary>Here are demos</summary>
[![asciicast](https://asciinema.org/a/NaRcg4vNckhD2pYrvmo114hhi.svg)](https://asciinema.org/a/NaRcg4vNckhD2pYrvmo114hhi)
(in this video, autocompletion transformed the command from `bloop` to `blobloop`, but this is not actually happening..., I think this is a problem of `asciinema` and my zsh configuration...)
[![asciicast](https://asciinema.org/a/89AAwTmMzW9gbEILMXnCtBveZ.svg)](https://asciinema.org/a/89AAwTmMzW9gbEILMXnCtBveZ)
[![asciicast](https://asciinema.org/a/rhypFT5yCDGMk5lurkot1zu …
> Implement test autocompletion for bash/zsh/fish

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopIncremental.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
Checks that compiling a project, then introducing an error and then
rolling back to the previous version causes a compiler noop.
> Use transactional classfile manager

- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
...instead of reporting at the end of the compilation.
This commit intends to report as early as possible in the case where
several expensive incremental cycles are triggered. An example of this
case can be found in https://github.com/scalameta/metals/issues/438
What this PR does is conceptually simple:
1. At the end of every incremental cycle, process the previous problems
that comply with any of these requirements:
* Their associated source doesn't exist (bloop clears diagnostics)
* Their associated source has already been processed (bloop does
nothing as problems have already been reported by `logFull`)
* Their associated file was compiled but no problem was registered
(bloop appropriately clears diagnostics)
* `reportAllPreviousProblems` is true. This happens in the first
compilation …
> Report bsp diagnostics in end of incremental cycle

- bin/install.py
- launcher/src/main/scala/bloop/launcher/Launcher.scala
- launcher/src/main/scala/bloop/launcher/core/Installer.scala
- launcher/src/test/scala/bloop/launcher/LauncherSpec.scala
And fix error in logic checking for compatible bloop version.
> Upgrade launcher tests to 1.2.0

- .scalafmt.conf
- backend/src/main/scala/bloop/reporter/DefaultReporterFormat.scala
- backend/src/main/scala/bloop/reporter/Reporter.scala
- backend/src/main/scala/sbt/internal/inc/bloop/ZincInternals.scala
- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
* Pretty print range positions in the cli diagnostics
* Report range positions in diagnostics via BSP
* Deduplicate duplicated diagnostics from scalac
Fixes https://github.com/scalacenter/bloop/issues/787
> Fix range positions in diagnostics

- .drone.yml
- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompilerPluginWhitelist.scala
- frontend/src/test/resources/compiler-plugin-whitelist/bloop-test-plugin/src/main/resources/scalac-plugin.xml
- frontend/src/test/resources/compiler-plugin-whitelist/bloop-test-plugin/src/main/scala/BloopTestPlugin.scala
- frontend/src/test/resources/compiler-plugin-whitelist/build.sbt
- frontend/src/test/resources/compiler-plugin-whitelist/project/build.properties
- frontend/src/test/resources/compiler-plugin-whitelist/project/plugins.sbt
- frontend/src/test/resources/compiler-plugin-whitelist/project/project/build.properties
- frontend/src/test/resources/compiler-plugin-whitelist/sandbox/src/main/scala/hello/App.scala
- frontend/src/test/resources/compiler-plugin-whitelist/whitelist/shared/src/main/scala/hello/App.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
A few months ago, I made [a change to cache compiler plugin classloaders in scala/scala](https://github.com/scala/scala/pull/6314)
via a compiler flag. The compiler flag, when enabled in projects that
make a heavy use of compiler plugins and macros, would yield great
compilation performance improvements. In the analyzed projects, around
15-35% faster compilation.
However, this feature was not enabled by default because caching
compiler plugin classloaders or macro libraries is dangerous when they
are stateful (for example, they define a map/set in a top-level object
but never clear its contents at the end of a compiler plugin). As there
is no way to know a priori if they are stateful or not, we agreed the
best default was to ask users to enable the flag manually.
As the compilation flag …
> Cache compiler plugins with a whitelist by default

- bridges/scala-native/src/main/scala/bloop/scalanative/NativeBridge.scala
- bridges/scalajs-0.6/src/main/scala/bloop/scalajs/JsBridge.scala
- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/JsBridge.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
- frontend/src/main/scala/bloop/engine/tasks/LinkTask.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaJsToolchain.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaNativeToolchain.scala
- frontend/src/test/scala/bloop/ForkerSpec.scala
- frontend/src/test/scala/bloop/JsTestSpec.scala
- frontend/src/test/scala/bloop/JvmTestSpec.scala
- frontend/src/test/scala/bloop/RunSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- project/Dependencies.scala
In https://github.com/scalacenter/bloop/pull/730, I claimed:
> Resources are files that are used at runtime, either when testing or
running an application. These files can be generated by the build tool or
be present in a resource directory of a project.
However, this was not the full story, it turns out that resources are also
required by macros, which happen at compile time, and therefore resources
are required by `compile`.
This patch modifies bloop to use the classpath with resources as the
default from now on for any action in bloop, as all of them require it.
Fixes https://github.com/scalacenter/bloop/issues/763
> Include resources in dependency classpath

- launcher/src/main/scala/bloop/launcher/core/Shell.scala
When running launcher and `bloop` is not on the `PATH` we get the following error:
```
Starting the bsp launcher for bloop...
Jan 15, 2019 12:39:19 PM com.zaxxer.nuprocess.linux.LinuxProcess start
WARNING: Failed to start process
java.io.IOException: error=2, No such file or directory
at com.zaxxer.nuprocess.internal.LibJava8.Java_java_lang_UNIXProcess_forkAndExec(Native Method)
at com.zaxxer.nuprocess.linux.LinuxProcess.start(LinuxProcess.java:109)
at com.zaxxer.nuprocess.linux.LinProcessFactory.createProcess(LinProcessFactory.java:40)
at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
at bloop.launcher.core.Shell.runCommand(Shell.scala:87)
at bloop.launcher.core.Shell.detectBloopInSystemPath(Shell.scala:153)
at …
```
> Disable warnings logged by nuprocess library

- backend/src/main/scala/bloop/reporter/Reporter.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
- notes/v1.2.4.md
Use `offset` instead of `pointer` (which is a short for column
position) to deduplicate error messages.
> Fix aggressive deduplication of diagnostics

- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
At the moment source generators (for example ScalaPB) do not run when doing bloopInstall in mill and since mill and bloop do not share output directories, there are a lot of spurious errors when compiling with bloop caused by the compilation output for the generated sources being missing. 
This changes the mill Config.Project so that it contains the generated sources too.
I have tested this with Metals + VS Code on [this project](https://github.com/DavidGregory084/inc) and the references to the `proto` module in the `common` module seem to work with this change.
> Ensure mill config uses generated sources too

- backend/src/main/scala/bloop/Compiler.scala
This is an attempt to correct race-conditions relating to concurrent
access of a temporary directory called `classes.bak`. The change chooses
a different, unique name (a UUID) for the temporary directory.
Bloop's build is currently failing, so I can't test this change, but
it's very simple. But I'm relying on a review, or some evidence of
passing tests, to confirm that this is the right thing to do.
Hopefully fixes #812.
> Use a guaranteed-unique name for temporary directories

- docs/tools/homebrew/install.md
- docs/tools/nix/usage.md
- docs/tools/scoop/install.md
- docs/tools/scoop/usage.md
- docs/tools/universal/usage.md
The dollar sign should not be copied when I click a "copy" button. At least for one-line commands.
__
Example page with "copy" button" - [link](https://scalacenter.github.io/bloop/setup#scoop).
> Remove command prompt for one-line commands

- frontend/src/main/scala/bloop/engine/ExecutionContext.scala
Note that we can only customize the number of cores dedicated to the
computation thread pool, which is the main thread pool where all
compilation takes place. We usually want to be this pool to have roughly
the same amount of threads as cores supported in the running machine.
> Allow customization of cores via system property

- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
```
[ERROR] Failed to execute goal ch.epfl.scala:maven-bloop_2.10:1.2.5:bloopInstall (default-cli) on project project: Execution default-cli of goal ch.epfl.scala:maven-bloop_2.10:1.2.5:bloopInstall failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal ch.epfl.scala:maven-bloop_2.10:1.2.5:bloopInstall (default-cli) on project project: Execution default-cli of goal ch.epfl.scala:maven-bloop_2.10:1.2.5:bloopInstall failed.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
at …
```
> Fix java.lang.NullPointerException in resources

- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
@jvican 
I've made mistake here https://github.com/scalacenter/bloop/pull/839
```
val resources = Some(resources0.asScala.toList.map(Option(_.getTargetPath)).flatMap(classesDir.resolve))
```
should be
```
val resources = Some(resources0.asScala.toList.map(Option(_.getTargetPath)).flatten.map(classesDir.resolve))
```
> Follow up to #839

- frontend/src/main/scala/bloop/engine/Feedback.scala
https://scalacenter.github.io/bloop/docs/installation/ is returning a 404 HTTP status code and it looks like that it was updated to https://scalacenter.github.io/bloop/setup
> Update URL for installation instructions in bloop frontend missingConfigDirectory error message

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/CompilerCache.scala
- backend/src/main/scala/sbt/internal/inc/javac/BloopForkedJavaUtils.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
Java compilation requires a mechanism to invalidate symbols that does
not depend on deleting class files from the classes directories. The
following commit implements that mechanism for both local and forked
javac compilation.
The mechanism becomes complex when supporting forked javac compilation
since we depend on the javac CLI and we cannot access any public API.
This forces us to implement a clever trick to get the compiler to fail
when a file has been invalidated.
> Invalidate symbols with forked and local javac

- docs/server.md
It seems like the homebrew formula is using the `prefix` for location causing file to be written under `/usr/local/Cellar/bloop/$version`. If this is not intended we need to update the formula to use `var` instead.
> Update homebrew server log path

- docs/build-tools/mill/export.md
- project/Dependencies.scala
With this version change, mill-bloop seems to work with mill 0.3.6-42-d1f1b6 also (latest published "unstable" mill version).
> Updated mill version 0.3.5 -> 0.3.6

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/io/ParallelOps.scala
- build.sbt
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/bsp/BloopLanguageClient.scala
- frontend/src/main/scala/bloop/bsp/BloopLanguageServer.scala
- frontend/src/main/scala/bloop/bsp/BspServer.scala
- frontend/src/main/scala/bloop/cli/Validate.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/main/scala/bloop/util/monix/FoldLeftAsyncConsumer.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
- frontend/src/test/scala/bloop/DeduplicationSpec.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspClientTest.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspConnectionSpec.scala
- launcher/src/main/scala/bloop/launcher/bsp/BspBridge.scala
- launcher/src/test/scala/bloop/launcher/LauncherBaseSuite.scala
- project/Dependencies.scala
- sockets/src/main/java/bloop/sockets/ReferenceCountedFileDescriptor.java
- sockets/src/main/java/bloop/sockets/UnixDomainServerSocket.java
- sockets/src/main/java/bloop/sockets/UnixDomainSocket.java
- sockets/src/main/java/bloop/sockets/UnixDomainSocketLibrary.java
- sockets/src/main/java/bloop/sockets/Win32NamedPipeLibrary.java
- sockets/src/main/java/bloop/sockets/Win32NamedPipeServerSocket.java
- sockets/src/main/java/bloop/sockets/Win32NamedPipeSocket.java
- sockets/src/main/java/bloop/sockets/Win32SecurityLibrary.java
The nitty-gritty is described in the commits. The diff is large because we add the sources of the sockets logic and some of the core lsp4s classes. This migration is useful to implement cancellation correctly and to fix some ongoing problems in future PRs (like local connections not working on Windows).
> Guarantee cancellation upon sudden client dropouts

- frontend/src/main/scala/bloop/bsp/BloopLanguageClient.scala
Synchronize on the output stream that writes out the responses to make
sure that the client receives the BSP server interactions in the same
order they happened. This helps fighting critical violations of the
protocol where `taskFinish` notifications could get before `taskStart`
notifications to the client, or where out-of-order receptions in the
client could produce incorrect user behaviors.
> Send out server BSP responses/notifications in order

- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopLookup.scala
- frontend/src/main/scala/bloop/engine/caches/LastSuccessfulResult.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
Empty classes directories exist uniquely per project and can be shared by any compiler process. To avoid any conflicts, we neither create nor delete empty classes directories and just treat them as mere placeholders of future, valid classes directories.
> Don't create and delete empty classes dirs

- bin/install.py
- project/ReleaseUtils.scala
Avoid conflict with Scoop's own SCOOP env variable by renaming to BLOOP_IN_SCOOP
> Change SCOOP env variable to avoid conflict

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/logging/Logger.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/logging/BspServerLogger.scala
- frontend/src/main/scala/bloop/util/SystemProperties.scala
- frontend/src/test/scala/bloop/DeduplicationSpec.scala
This PR adds a new system property to configure a disconnection time
from a deduplicated compilation process as well as the machinery
required to implement the cancellation.
When a deduplication takes place and an ongoing compilation has not
registered any kind of progress update for a particular time slot (no
log or reporter action, including scalac progress updates), then Bloop
will disconnect the deduplication, cancel the ongoing compilation and
attempt to schedule another fresh compile. This mechanism is done to
avoid any kind of issues that could occur during compilation.
In all the time of testing this feature, I've never encountered a case
where this is necessary. However, it's a safety mechanism that will
allow us to debug misbehaviours if compilations go awry.
Users can modify …
> Cancel deduplication if ongoing compilation looks dead

- .drone.yml
- backend/src/main/scala/bloop/io/Paths.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/io/SourceHasher.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
- frontend/src/test/scala/bloop/DeduplicationSpec.scala
- frontend/src/test/scala/bloop/IntegrationTestSuite.scala
Pipelining was using the client classes directory instead of the generic classes directory, which meant that the IR stores were not put in the right order.
This change also fixes a bug that would show up if a project has several source directories that contain each other. Before this fix, the compiler would fail with repeated definition error.
> Use generic classes dir for the pipelined traversal

- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/test/scala/bloop/DeduplicationSpec.scala
Making more visible the cases where bloop performs a deduplication is better for debugging purposes and will inform users better about what work is the build server doing.
> Log to the user a deduplication is happening

- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/test/scala/bloop/CliSpec.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
Bloop does not support concurrent access of projects in the same
build by two different CLI clients. It does, however, support it for
one CLI client and as many BSP clients as they connect to the build
server. For this reason, this commit implements a way to prevent two CLI
clients from running operations concurrently in the same build.
> Synchronize CLI clients to the same build

- etc/fish/bloop.fish
Was getting the following fish error:
```
/usr/share/fish/vendor_completions.d/bloop.fish (line 57): array indices start at 1, not 0.
if string match -q -- $tokens[-1] $argv[0]
^
in function “__assert_prev_arg_in”
called on standard input
with parameter list “--only -o”
in command substitution
called on standard input
```
when trying to autocomplete project name in `bloop test`.
> Array indices in fish start from 1

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
This will give us more precise scalac options than before because some
plugins/users might add specific options in these two scopes. This is
the scope that the `Keys.compile` task accesses when it calls for the
value of scalac options.
I hope that doing this does not force the compilation of inter-module
dependencies. It should not, at least by some local experimentation, but
if it does we could consider reverting the change.
This was discovered during the compilation of http4s, which after this
change is exported and compiled correctly.
> Scope javac options and scalac options in compile

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
In gradle 5 a default annotation processor was added and it causes java projects not to be built because of the missing directory. I added a manual step that checks for the flag (due to compatibility reasons couldn't use the proper API) and then:
- if the annotation processor is none we remove the whole option
- otherwise if the option for processor exists and it is not none we create the directory
I also added separate test suites for 4.8.1 and 5.3.1 (in 5.3.1 this was broken)
> Add a way to ignore annotation procesor and gradle 5.3.1 test suite

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
Most projects that I've seen have the same entries in `dependsOn` and `aggregate`, which means we see these modules twice in the config files. This is just an OCD-induced change, I have no reasons to say it's impacting performance in any way :)
> Avoid duplication in `dependencies` section

- backend/src/main/scala/bloop/DependencyResolution.scala
- bin/install.py
- docs/cli-reference.md
- frontend/src/main/scala/bloop/cli/Commands.scala
- frontend/src/main/scala/bloop/cli/ReplKind.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/test/scala/bloop/ConsoleSpec.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
- launcher/src/main/scala/bloop/launcher/core/Installer.scala
- launcher/src/test/scala/bloop/launcher/LauncherBaseSuite.scala
- project/Dependencies.scala
Closes #877 
We launch Ammonite REPL by reading the classpath of the requested
project, and then write a Coursier command that can be executed.
This is picked up by Nailgun, see scalacenter/nailgun#11.
I believe that the version of Coursier used by Bloop does not support the `latest.release` functionality. What should be done about this? Also, there's a potential issue in the tests, I'll leave comment on that.
> Add support for Ammonite REPL

- integrations/maven-bloop/src/main/java/bloop/integrations/maven/BloopMojo.java
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
This adds download of source dependencies for project and then appends them to the bloop config.
I have tried the official Maven Api, but that is way too complex to use. Here I use an existing plugin that downloads all source dependencies to local repo and then I resolve all source deps by hand from normal paths.
> Add source dependencies to maven plugin

- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
- project/Dependencies.scala
- project/build.sbt
MVN version updates fix:
```
[info] Done compiling.
[error] java.lang.IllegalArgumentException
[error] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
[error] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
[error] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
[error] 	at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.analyzeClassStream(DefaultMojoAnnotationsScanner.java:214)
[error] 	at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scanDirectory(DefaultMojoAnnotationsScanner.java:198)
[error] 	at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scan(DefaultMojoAnnotationsScanner.java:108)
[error] 	at …
```
> Compile on java9+

- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/Cli.scala
Make sure we don't try to acquire the lock again if the client waiting
for it already disconnected. If that's the case, skip and return a zero
exit status code.
> Fix case where waiting client is cancelled

- backend/src/main/scala/bloop/CompileProducts.scala
- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileDependenciesData.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
Implements a similar fix as
https://github.com/scalacenter/bloop/pull/881 but this time making sure
we remove generated class files in dependent projects from the
transitive invalidations.
> Fix not found type errors during incremental compilation

- project/BuildPlugin.scala
- project/Dependencies.scala
The transitive invoker dependency is an old version that doesn't work with newer maven due to change of maven execution script from bat to cmd extension.
> Add newer version of maven-invoker explicitely to fix windows issues

- frontend/src/main/scala/bloop/Cli.scala
Two changes:
We wait on the CLI lock to be free forever. Use instead a default of 60s 
waiting time and if the other client doesn't exit before that, then we give
up and exit with a error status code.
This is a friendly setting for CI instances that have a shared bloop server
and that commnicate with it via CLI clients. If the server is taken, giving
up and not forcing an infinite wait is good.
Users can tweak the default timeout in seconds via
`-Dbloop.cli-lock.seconds-to-timeout`
CLI clients need synchronization so that they don't modify compilation 
inputs or outputs concurrently. However, the lock we use to synchronize the
clients is not required for non-compiling commands such as `bloop about` or
`bloop autocomplete`, which can work concurrently. Allow those.
> Add CLI lock timeout lock and be more flexible while locking

- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/test/scala/bloop/nailgun/NailgunSpec.scala
As suggested in gitter, this PR changes `bloop about` to show the JVM version and java home bloop is running on:
> Display Java version and home in bloop about

- frontend/src/main/scala/bloop/io/SourceHasher.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
This manifests when a bloop.config.Config has a specific file as well as
a parent directory of the file listed as sources
This test ensures that the tested bloop config has both `src` and `src/main/scala/Foo.scala` listed as sources.
The code creating the `TestProject` is admittedly a little weird, but it appears that the normal path to creating `TestProjects` is populating their sources with a single directory: https://github.com/scalacenter/bloop/blob/ad4c22f59c3f65853b03b9e0f3390fdfca9c2063/frontend/src/test/scala/bloop/util/TestProject.scala#L123
> Add failing test where source files are pulled in multiple times

- backend/src/main/scala/bloop/io/ClasspathHasher.scala
- backend/src/main/scala/bloop/io/Paths.scala
- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
- notes/v1.3.1.md
Two crashes due to excessive open file pointers in my macOS machine have
fired a red alarm that have led me to discover a memory leak in the way
we were listing directories. This memory leak was caused because
`Files.list` returns an stream that must be closed, but I have not seen
that before because I was converting that stream to a Scala iterator
via the automatic Java converters and at the end of that iteration
resources were not correctly cleaned up.
Now we make sure that we always close these resources.
> Fix memory leak in listing directories

- docs/server.md
This PR documents the location of the optional .jvmopts file when bloop is installed via brew in server.md
> Documents the location of the optional .jvmopts file on macOS

- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
Tried working on https://github.com/scalacenter/bloop/issues/928 but we don't have enough information and it's not the first case it fails there. When there is an issue with NPEs while writing config we have no way of detecting where it happens.
> Add debug information to the maven bloop plugin

- docs/build-tools/sbt/export.md
The syntax looked wrong in https://scalacenter.github.io/bloop/setup#generate-configuration-files.
Not sure what the reference should point to...
> Fix link reference in docs

- frontend/src/main/scala/bloop/bsp/BloopBspDefinitions.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/bsp/BspServer.scala
- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
The following commit adds support for a parameter that clients can pass
to bloop so that bloop creates stable client classes directories
(client-specific directories) for a given client. The status quo is to
create client-specific directories that are only valid during a given
session and then they are removed but IntelliJ's model unfortunately
assumes stable classes directories. If we create a client classes
directory per session, IntelliJ needs to update the whole build model
and reindex everything, which is apparentely a very costly action that
can take up more than 5 minutes in certain projects.
For the sake of having a good intellij compatibility story, we add this
option. This option implies that the client (e.g. IntelliJ) is 100%
responsible for managing the contents created inside …
> Enable option for BSP stable classes directories

- config/src/main/scala/bloop/config/Config.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
settings.
This reverts #975 and replaces it with a better and more universal approach.
Gradle `test.systemProperties` actually sets the system properties on the forked test JVM. This patch brings the same behavior to Bloop. Additionally `test.jvmArgs` and memory settings are also exported to JVM args of the test platform.
> Import Gradle test jvm options and system properties to test platform

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
In gradle it is possible to define a dependency to an external file
like this:
dependencies {
runtime files(Jvm.current().toolsJar)
}
Unfortunately such dependencies do not come as ResolvedArtifacts
from the Gradle API, and therefore they were missed in the generated
bloop configuration. This commit fixes importing them.
Fixes #978
> Fix missing dependencies to files referenced directly

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/build.sbt
This commit removes a bit of logic that was inherited from the previous
extractor that was not configuration based and that was not spotted
before. This extra line was adding an unncessary compile dependency
between projects when the project instead had another dependency (e.g.
test, it) on that project.
> Fixes unnecessary dependency in sbt extractor

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
Moves the `out` directory from under the Gradle build output directory to under `.bloop` in Gradle export to prevent Bloop analysis files being removed on `Gradle clean`
> Move `out` directory to under `.bloop` in Gradle export

- docs/server.md
When java is managed by an SDK manager, it may not be in the $PATH when the server is started.
This change document this edge case to avoid duplicates of [#990, Unexpected error when starting server via systemd](https://github.com/scalacenter/bloop/issues/990)
> Add a section about $PATH when using an sdkmanager 

- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/test/scala/bloop/CompileSpec.scala
When a symbol is generated, we removed the rebased read-only path from
the invalidated class files map assuming that an invalidated symbol
used always the read-only classes directory path. However, that's not
always the case -- the paths of an invalidated symbol can also use the
new classes directory and not handling that was an oversight. This
commit just fixes that so that we attempt to both remove the read-only
classes dir path and the write-only classes dir path.
Fixes #972.
> Delete both new and read-only paths for invalidated symbols

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
If java source set is non-empty, a java-then-scala order is used.
This config results in java-then-scala order:
sourceSets {
main {
java {  srcDirs = ['src/java'] }
scala {  srcDirs = ['src/scala'] }
}
}
This config results in mixed order:
sourceSets {
main {
java {  srcDirs = [] }
scala {  srcDirs = ['src/java', 'src/scala'] }
}
}
Fixes #992
> Set proper compile order in projects imported from Gradle

- backend/src/main/scala/bloop/logging/BloopLogger.scala
- backend/src/main/scala/bloop/logging/ObservedLogger.scala
- backend/src/test/scala/bloop/logging/RecordingLogger.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/logging/BspClientLogger.scala
- frontend/src/main/scala/bloop/logging/BspServerLogger.scala
- frontend/src/main/scala/bloop/logging/NoopLogger.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspClientTest.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/logging/BufferedLogger.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- shared/src/main/scala/bloop/logging/Logger.scala
Makes sure that bloop bsp services handle the origin id field set in
certain BSP requests to let clients trace the origin of logMessage,
showMessage or diagnostics.
Fixes https://github.com/scalacenter/bloop/issues/679
> Propagate origin id from BSP requests to loggers

- launcher/src/main/scala/bloop/launcher/Launcher.scala
When the BSP connection is not used anymore, the socket remains open indefinitely. If the application that spawned the connection doesn't terminate immediately after `LauncherMain.runLauncher` returns, this causes a resource leak.
> Close sockets after the BSP connection has been terminated

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/bsp/BloopLanguageClient.scala
1. BSP services that generate output from many projects now map pojects in parallel - reduces service call latency.
2. Writing to an `OutputStream` by single bytes was not the most efficient way of sending out data - replaced by channel. Could go probably further and avoid copying buffers at all if we didn't use `OutputStream`s, but a bigger refactoring would be needed and I don't have the time now ;)
Impact of this change:
Before this change importing our multi-module project took ~13-15 seconds with Intellij IDEA, and Bloop was using 100% of one CPU core for ~ 10 s.
After this change it takes ~ 2.5 s (most of that probably on the IDEA side), and the CPU spike on the Bloop side is hardly noticeable.
> Improve BSP services performance

- backend/src/main/scala/bloop/CompilerCache.scala
- backend/src/test/scala/bloop/CompilerCacheSpec.scala
Passing a WriteReportingFileObject to the original, wrapped
JavaFileManager may cause InvalidArgumentException. To avoid this,
we unwrap the original FileObject.
Fixes #956
> Fix semantics of `isSameFile` in class file manager

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
Previously the `data` and `dataKind` fields in `RunParams` were ignored and the default class in the build target was run. 
Now, if those fields are specified, we use the information (class name, arguments and jvmOptions) to run the correct class. If `dataKind` is not specified, the old approach is used for backward compatibility
> Support running custom scala main class in BSP

- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
Currently, metals is asking for scala main classes and test suites (to provide code lenses) quite often and if the project was not yet compiled, we get a warn for each of the modules in the project like in the image below. 
This PR changes those warns to debug-level messages so they are still discoverable but no longer overwhelm the output.
> Don't warn about main classes in non-compiled projects

- frontend/src/main/scala/bloop/dap/DebugSession.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
In some cases this timeout might be too low (e.g. when the task was not yet started). This seems like a probable cause for failing tests on [metals CI](https://github.com/scalameta/metals/pull/942). Increasing timeout here does not seem to be a major issue, since previous value already was quite arbitrary.
> Increase the debuggee startup timeout

- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/main/scala/bloop/util/monix/FoldLeftAsyncConsumer.scala
- frontend/src/main/scala/bloop/util/monix/WhileBusyDropEventsAndSignalOperator.scala
- frontend/src/test/scala/bloop/FileWatchingSpec.scala
Check the commit messages for more information.
Fixes https://github.com/scalacenter/bloop/issues/980 and a bug bug that
happens with remote development in VS Code.
> Improve file watching corner cases

- docs-gen/src/main/scala/bloop/docs/Sonatype.scala
It looks like Sonatype has moved the artifacts present in `staging` to
another repository called `public`. This commit updates a workaround I
did a few days ago to make our publish CI step work when the Sonatype
breaking change affected us. Now we should query the latest released
version correctly.
Fixes https://github.com/scalacenter/bloop/issues/1054
> Query latest version from `public` Sonatype repository

- project/ReleaseUtils.scala
As someone pointed out on AUR, Java >= 8 is enough, there is no need to install Scala system-wide.
> Don't require scala for the ArchLinux package

- backend/src/main/scala/bloop/ScalaInstance.scala
- backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala
- frontend/src/test/scala/bloop/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/ScalaVersionsSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
https://github.com/scalacenter/bloop/pull/460 initially added support
for Dotty but we removed it recently while experimenting with some
breaking changes in the Zinc compiler interface. Those changes were
afterwards refactored to be non-breaking with the Dotty compiler bridge,
which means Dotty continues to work with Bloop.
However, we must make a change in the Dotty compiler interface to
support invalidation of class files by hooking up into their compiler
symbol loaders. I'll follow up with that change in the Dotty repository.
> Add dotty support back

- .gitignore
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
This is important if somebody already added a SemanticDB plugin, but not all the options required by metals.
Also added a check to not add `-Yrangepos` to Dotty.
> Add all necessary SemanticDB options

- .github/workflows/ci.yml
- launcher/src/main/scala/bloop/launcher/bsp/BspBridge.scala
As a follow up from https://gist.github.com/jvican/a4a081718ac330de3aa734fdfd665085
It seems those threads were keeping the connection alive and not allowing Metals to close.
@jvican Not exactly sure why we didn't run those as deamons, since anything starting Bloop launcher will not be able to kill those threads.
> Set Bloopgun to use deamons

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/test/scala/bloop/LoadProjectSpec.scala
We should not export default Scala SDK for projects that don't use Scala
because these projects may be dependencies of other projects that
do use a different version of Scala. In this case external tools
may put both Scala SDKs on the classpath (the default one from the
Java-only project and the one coming from the dependent Scala project)
and if the default incorrect SDK "takes over", problems can happen.
See https://youtrack.jetbrains.com/issue/SCL-15892
Fixes #1008
> Remove default scala for java-only projects

- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/jsenv/NodeJsHandler.scala
- frontend/src/main/scala/bloop/dap/DebugSession.scala
- frontend/src/main/scala/bloop/dap/DebugSessionLogger.scala
- frontend/src/main/scala/bloop/dap/DebuggeeRunner.scala
- frontend/src/main/scala/bloop/exec/Forker.scala
- frontend/src/test/scala/bloop/ForkerSpec.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/dap/DebugAdapterConnection.scala
- frontend/src/test/scala/bloop/dap/DebugAdapterProxy.scala
- frontend/src/test/scala/bloop/dap/DebugBspBaseSuite.scala
- frontend/src/test/scala/bloop/dap/DebugProtocolSpec.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
- frontend/src/test/scala/bloop/dap/DebugTestClient.scala
- frontend/src/test/scala/bloop/dap/DebugTestProtocol.scala
This makes the `Forker` split the process output on both unix- and windows- style newlines, regardless of the underlying OS.
Motivation here is that we cannot make the assumption on the basis of the underlying OS, because there is no guarantee that the application is intended to run on the same OS it is being developed on.
It changes the current behavior only in cases where the application produces an output with mixed newline style.
> Detect JDI initial notification on Windows

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/CompilerCache.scala
- backend/src/main/scala/bloop/util/JavaRuntime.scala
- backend/src/main/scala/sbt/internal/inc/javac/BloopForkedJavaUtils.scala
- backend/src/test/scala/bloop/CompilerCacheSpec.scala
- frontend/src/it/scala/bloop/CommunityBuild.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/dap/DebuggeeRunner.scala
- frontend/src/main/scala/bloop/data/JdkConfig.scala
- frontend/src/main/scala/bloop/data/Platform.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/Feedback.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/State.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
- frontend/src/main/scala/bloop/util/JavaRuntime.scala
- frontend/src/test/scala/bloop/ForkerSpec.scala
- frontend/src/test/scala/bloop/RunSpec.scala
- frontend/src/test/scala/bloop/nailgun/NailgunSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
So that we can reuse the same JVM used to run/test Java code to compile it
as well. In case a config for a project is Scala.js or Scala Native, Bloop
will pick the default Java home.
To make this possible, we first needed to refactor `JavaEnv` into
more specific abstractions, i.e. `JdkConfig` and `JavaRuntime`.
Fixes https://github.com/scalacenter/bloop/issues/968.
> Use platform.config settings to compile Java code

- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
This fixes a regressions introduced when several changes were done in
this area to implement DAP support in Bloop.
Fixes https://github.com/scalacenter/bloop/issues/1082
> Strip `-J` prefix of jvm arguments before forking

- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/io/Filenames.scala
Fixes #1101. Previously, when project names included classpath
separators like `:` then it was not possible to run/test via IntelliJ.
Now, we replace path separators in the classes output directory with
underscore `_`.
> Avoid classpath separator in classes output directory.

- .github/workflows/ci.yml
Previously, the release job only ran if tests passed. This caused the
release to not run on flaky test failures. Now, the release job runs
regardless if the tests pass or not.
A nice effect of this change is that releases finish faster. We use the
same setup in Metals and have not experienced issues with releasing
unwanted commits. If something lands into master we want to release it
regardless of test results.
> Drop dependency between release and test jobs.

- launcher/src/main/scala/bloop/launcher/bsp/BspBridge.scala
I have seen numerous timeouts in continuous integration when Fury is
starting up Bloop, while Bloop is actually launched successfully some
time shortly afterwards.
This makes a couple of changes to the startup process to try to mitigate
this:
- Increases the timeout from 10s to 30s
- Increases the frequency of checking if Bloop is up (this saves a
little time in what is the slowest part of Fury startup)
- Reduces the frequency of logging the "waiting" messages to once per
second
> Increase the timeout during the launcher to 30s

- build.sbt
- project/Dependencies.scala
Fixes #1109. The shaded bloopgun already depends on scala-library so it
should be safe to also include scala-xml on the classpath.
> Add missing dependency on scala-library in shaded bloopgun

- bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala
- launcher/src/test/scala/bloop/launcher/LauncherSpec.scala
Previously, the Bloop launcher and bloopgun would use a `blp-server`
binary from the local computer to launch Bloop.  This behavior was
especially surprising when using the Bloop launcher since the explicitly
provided version would be ignored.  In the example log below, the Bloop
version v1.3.4 was picked from my local Homebrew installation over the
explicitly provided version number 1.3.4+226-153862a1.
```
$ cs launch ch.epfl.scala:bloop-launcher_2.12:1.3.4+226-153862a1 -- 1.3.4+226-153862a1 --skip-bsp-connection
Starting the bsp launcher for bloop...
Attempting a connection to the server...
No server running at 127.0.0.1:8212, let's fire one...
A bloop installation has been detected either in the PATH or $HOME/.bloop
Starting bloop server at 127.0.0.1:8212...
-> Command: List(sh, …
```
> Don't use blp-server from local installation in bloopgun and launcher.

- docs-gen/src/main/scala/bloop/docs/Sonatype.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
This issue was reported by @dotta a few weeks ago and was able to
reproduce it. This ticket fixes an issue in the sbt-bloop plugin that
adds duplicated artifacts in the resolution field.
> Don't re-add duplicate resolution artifacts in sbt-bloop

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
Previously, the default value of `bloopExportJarClassifiers` was
hardcoded to `None`. This meant that users needed to change build.sbt to
override this value to include downloading of sources.
Now, users can globally configure this value to be
`Some(Set("sources"))` via environment variables
```
export BLOOP_EXPORT_JAR_CLASSIFIERS=sources,javadoc
```
Alternatively, they can achieve the same with a system property
```
sbt -Dbloop.export-jar-classifiers=sources,javadoc
```
This simplifies the "manual build import" step for Metals users, since
users can run `bloopInstall` from the sbt shell without modifying the
build or invoking verbose commands like
```
set bloopExportJarClassifiers in Global = Some(Set("sources"))
```
> Allow `bloopExportJarClassifiers` to be configured via environment.

- backend/src/main/scala/bloop/DependencyResolution.scala
- backend/src/main/scala/bloop/ScalaInstance.scala
- backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala
- frontend/src/main/scala/bloop/engine/caches/SemanticDBCache.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaJsToolchain.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaNativeToolchain.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ToolchainCompanion.scala
- frontend/src/main/scala/bloop/testing/TestInternals.scala
- frontend/src/test/scala/bloop/io/ClasspathHasherSpec.scala
- project/Dependencies.scala
The linker versions are still hard-coded in `Dependencies.scala`, but have
been annotated with sbt's `Provided` scope. When the bridges are resolved
now, the platform-specific libraries have to be included explicitly which
allows us to specify the same version as in the user's build configuration.
Closes #1062.
> Resolve correct linker versions in non-JVM builds

- frontend/src/main/scala/bloop/engine/Interpreter.scala
> Respect --no-color flag

- frontend/src/main/scala/bloop/dap/DebugServer.scala
- frontend/src/test/scala/bloop/dap/DebugAdapterConnection.scala
- frontend/src/test/scala/bloop/dap/DebugAdapterProxy.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
- frontend/src/test/scala/bloop/dap/DebugTestEndpoints.scala
Previously, java-debug library would try to evaluate `toString` method for variables overriding it when servicing the `variables` request. Since code evaluation is not supported, it led to the failure of the whole request.
This changes the library setting to skip evaluation of `toString` methods.
> Don't evaluate `toString` when handling variables request

- integrations/sbt-bloop/src/main/scala-sbt-0.13/bloop/integrations/sbt/Offloader.scala
- integrations/sbt-bloop/src/main/scala-sbt-1.0/bloop/integrations/sbt/Offloader.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
If offloading is not enabled, we use the default from previous versions.
> Disable shared sbt-bloop classes dirs when not offloading

- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
- frontend/src/test/scala/bloop/ForkerSpec.scala
Previously, `JvmForker` passed the full classpath into the `java` invocation via `-cp`, without considering the implications for very long classpaths which break the command line length limits.
Now, it will create a temporary manifest jar to pass on classpath information in a command line-friendly way to the `java` invocation. This will allow us to run commands which exceed OS limits due to the length of the classpath. This will *not* address commands whose argument list to the main class causes it to fail despite shortening the classpath string.
Fixes https://github.com/scalacenter/bloop/issues/1094
Fixes https://github.com/scalacenter/bloop/issues/1084
> Use MANIFEST jar to run commands that exceed OS limits

- buildpress-config/src/main/scala/buildpress/config/Config.scala
- config/src/main/scala-2.11-13/bloop/config/ConfigCodecs.scala
- frontend/src/main/scala/bloop/data/WorkspaceSettings.scala
- project/Dependencies.scala
Previously, Scala collection types in generated jsoniter codecs could be
left empty and the deserialization would not fail. However, this runs
constrary to the semantics in our previous Circe codecs and the
semantics we want to enforce: all fields should be mandatory unless they
are explicitly wrapped on an `Option` type.
This PR enables a new option that @plokhotnyuk introduced in https://github.com/plokhotnyuk/jsoniter-scala/pull/411/files
> Require collection field types in jsoniter codecs

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/BloopParameters.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/BloopPlugin.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/BloopInstallTask.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/ConfigureBloopInstallTask.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
- project/Dependencies.scala
- project/GradleIntegration.scala
Update minimum Gradle version supported to 4.3; remove reflection (no longer have to support < 4.3);
fix Gradle test API download and classpath extraction; and support v6.0. Fixes #1133
Incorporate @pkolaczk #1099 fix for #1092 (hope that's not bad etiquette) as input property handling had to be refactored for v4.3.
Fix JavaDoc artifact resolution - used to always download and discard (default is to not download).
Fix SourceCompatibility and TargetCompatibility for Java - didn't pick up settings.
> Update minimum Gradle version to 4.3 and some fixes

- etc/zsh/_bloop
When loading zsh completion script on Mac OSX the following error occurs:
```bash
_arguments:comparguments:325: can only be called from completion function
```
This change simply omits it. Are there any other proposals?
> Silence error from _arguments:comparguments:325

- bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala
Previously, the Bloop launcher always printed out a large line in the
output:
```
-> Command: List(a.jar, b.jar, ....)
```
This line is now logged at debug level so that it doesn't appear by
default.
> Reduce noise in bloop-launcher console output.

- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
Bloop has manifest classpath entries in Windows going from...
```c:/users/...```
to...
```/users/...```
which doesn't work when using multiple drive letters e.g.
```c:/users/... d:/dev/...```
Changed to produce this...
```/c:/users/... /d:/dev/...```
[reference](https://stackoverflow.com/questions/18659774/how-do-i-handle-files-with-spaces-in-the-classpath-in-manifest-mf)
> Fix Windows drive letter handling in jar manifest

- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/test/scala/bloop/LoadProjectSpec.scala
Previously, the working directory for forked processes was always the
base directory of the project. This caused problems for the Pants
integration since the working directory in Pants is always the workspace
directory. We can't set the project's base directory to the workspace
directory since IntelliJ requires different projects to have unique base
directories.
This commit updates the logic for inferring the working the directory of
a process by checking if the `-Duser.dir=` system property is configured
in the JVM platform configuration. If the property is customized, then
Bloop uses that working directory instead of base directory.
> Infer working directory from JVM -Duser.dir system property.

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
When a file is invalidated from one project to another one, we create a
symbolic link to make sure the invalidation is picked up by downstream
projects. If the link can't be created because the package where it's
being created doesn't exist, Bloop makes sure it creates it.
Fixes the following issue:
```
Failed to create link for invalidated file /private/var/folders/mw/jwr3v0rs4g179tn27dr5b36w0000gn/T/bloop-test-workspace6216784217427414920/target/a/bloop-internal-classes/bloop-cli-hs8t9mOxSEGMFXJXlPH2Sg==/common/Bar.class: /private/var/folders/mw/jwr3v0rs4g179tn27dr5b36w0000gn/T/bloop-test-workspace6216784217427414920/target/b/bloop-internal-classes/bloop-cli-nrOUxfNzRx-hAFm8ovcrqQ==/common/Bar.class -> /private/var/folders/mw/jwr3v0rs4g179tn27dr5b36w0000gn/T/bloop-test-workspace621678421 …
```
> Create parents of invalidated symbolic links

- backend/src/main/scala/bloop/ScalaInstance.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/LoadProjectSpec.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
1. No more `null`s inherited from the old Zinc `ScalaInstance`
2. Better error reporting if loading a project causes an error
Fixes https://github.com/scalacenter/bloop/issues/1142
> Report better errors if project loading fails

- bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala
Previously, bloopgun only supported configuring the working directory
through the `-Duser.dir` system property. Now, it's possible to
configure the working directory as a constructor argument.
This change is binary backwards compatbile.
> Make working directory configurable for bloopgun-cli.

- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
Previously, we used `Path.toString` for generating `Class-Path` entries
of a manifest jar. This encoding works correctly for normal paths but it
fails when the file path has special characters like `+`. To properly
handle such characters in the filepath, we need to URL-encode the file
path. This is necessary in order to use artifacts like
`bloop-backend_2.12-1.4.0-RC1+11-2b1413fb.jar`.
cc/ @wiwa
> URL-encode file paths for manifest jars.

- build.sbt
Previously, nightly build versions were formatted with a plus sign like
`1.3.4+87-GITSHA`.  The plus sign needs to be URL encoded for it to be
used in filenames, for example `1.3.4%2B298-2c6ff971`. Tools that
don't handle this situation properly get "class not found" errors and
are therefore unable to run nightly versions of Bloop.
After this commit, the version number uses a minus sign instead
`1.3.4-98-2c6ff971` so that client tools don't have properly deal with
URL-encoding the filename.
It's fair to say that client tools should fix their buggy handling of
the plus sign in filename. However, I have currently had to fix this
issue in at least three different tools and now I'm facing issues with
the fourth tool. I would prefer to change the version encoding in Bloop
so I don't have to …
> Replace plus sign `+` with minus `-` in version number.

- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
This changes are needed so that user experience for Dotty will be exactly the same as it in Scala 2.
Previously, user would have to add the settings manually.
We only need 2 settings in this case: `-Ysemanticdb` and `-sourceroot`
@jvican Let me know if this makes sense.
> Add options for Dotty to create semanticDB when Metals is present

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- project/Dependencies.scala
Implement BSP endpoint: `buildTarget/jvmTestEnvironment` according
to the new BSP specification.
EXCERPT FROM BSP SPECIFICATION:
The JVM test environment request is sent from the client to the server in order to
gather information required to launch a Java process. This is useful when the
client wants to control the Java process execution, for example to enable custom
Java agents or launch a custom main class during unit testing or debugging
The data provided by this endpoint may change beteween compilations, so it should
not be cached in any form. The client should ask for it right before test exection,
after all the targets are compiled.
- method: `buildTarget/jvmTestEnvironment`
- params: `JvmEnvironmentParams`
```ts
export interface JvmEnvironmentParams(
targets: …
```
> Add BSP endpoint to query jvm test environment

- config/src/main/scala/bloop/config/Config.scala
As a result of this change, Maven and Gradle will add munit and utest as
a framework by default. We do this because there's currently no support
in these build tools to see which test frameworks are enabled and only
export those.
> Add munit framework to default frameworks

- frontend/src/main/scala/bloop/engine/tasks/compilation/CompilerPluginWhitelist.scala
This pull request fixes a bug detecting when a version is blacklisted or
not. The issue was happening because 2.12.10 starts with 2.12.1, so it
was being considered blacklisted.
I would expected codebases on 2.12.10 and forward will run faster after
this change.
> Fix error checking blacklisted versions

- bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala
- bloopgun/src/main/scala/bloop/bloopgun/util/Environment.scala
- launcher/src/main/scala/bloop/launcher/Launcher.scala
The stack size required by many macros such as shapeless is large.
Sometimes, compilations would fail on the bloop side because the stack
size is exceeded. This commit uses a larger default of 1m for the stack
that should remove these issues in the future.
> Add default `-Xss1m` compiler option

- .jvmopts
We recently promoted the `bloop.generate.sbt` setting to user configuration and the name needed to also change to `bloop-sbt-already-installed`.
@jvican Adding it now so I don't forget to do it when releasing.
> Add bloop-sbt-already-installed property for Metals 0.8.0+ versions

- config/src/main/scala-2.10/bloop/config/ConfigCodecs.scala
- config/src/main/scala/bloop/config/Config.scala
- frontend/src/it/scala/bloop/CommunityBuild.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/data/SourcesGlobs.scala
- frontend/src/main/scala/bloop/io/SourceHasher.scala
- frontend/src/test/scala/bloop/DagSpec.scala
- frontend/src/test/scala/bloop/SourcesGlobsCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/io/SourcesGlobsSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- shared/src/main/scala/bloop/io/RelativePath.scala
Fixes #1164.
Previously, Bloop targets could only have either source files or
source directories. This caused problems when integrating with builds
tools like Pants that allow targets to have declare the list of source
files via include/exclude globs.
Now, Bloop targets can specify the list of source files via file globs
using the new "sourcesGlobs" field in the Bloop JSON configuration
section. For example,
```json
{
"sources": ["/path/to/Foo.scala"],
"sourcesGlobs": [
{
"directory": "/glob/directory",
"walkDepth": 3, // optional
"includes": ["*.scala"],
"excludes": ["*Test.scala"]
}
]
}
```
The example above would expand to all Scala source files that are in
depth 3 from the directory "globDirectory" and don't have a filename
that ends with "*Test.scala".
BSP does not support file globs …
> Add new "sourcesGlobs" field to Bloop JSON configuration.

- .jvmopts
Follow up from https://github.com/scalacenter/bloop/pull/1177
Forgot about the prefix and now we can remove the old property.
> Add missing `metals.` for Metals properties

- config/src/main/scala/bloop/config/Config.scala
- frontend/src/it/scala/bloop/CommunityBuild.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/DagSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- project/Dependencies.scala
See https://github.com/build-server-protocol/build-server-protocol/pull/109 for details
I added packagePrefix at project/build target level. Not sure if it should be more granular, and if so, where exactly it should be located as we have sources that is a list of files or dirs but also sourceGlobs. Sources seems to usually contain specific files, attaching packagePrefix to each of these would be quite strange.
> Add support for packagePrefix

- build.sbt
Similar to #1109 #1110 this _should_ fix a `java.lang.NoClassDefFoundError: scala/xml/Node` error encountered when using the launcher in some situations. I haven't figured out when exactly this error occurs and this change is untested.
> Add missing scala-xml dependency in shaded launcher

- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileResult.scala
- frontend/src/main/scala/bloop/io/SourceHasher.scala
- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/test/scala/bloop/io/SourceHasherSpec.scala
To avoid conflicts when leading with Emacs Interlock files, we
whitelist hidden source files from the `SourceWatcher` so that fired
modifications on these files are ignored and from the `SourceHasher` so
that these files are never discovered and hashed during the
`CompileInputs` bundling.
Fixes https://github.com/scalacenter/bloop/issues/1088
> Don't match on hidden source files

- backend/src/main/scala/bloop/reporter/Reporter.scala
- backend/src/main/scala/sbt/internal/inc/HydraSupport.scala
- backend/src/main/scala/sbt/internal/inc/bloop/BloopZincCompiler.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopIncremental.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/ConcurrentAnalysisCallback.scala
- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/main/scala/bloop/reporter/LogReporter.scala
- frontend/src/main/scala/bloop/reporter/package.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
- frontend/src/test/scala/bloop/HydraCompileSpec.scala
Mirrors https://github.com/scalacenter/bloop/pull/1184
This PR should fix the execution of tests with Hydra. It includes two important fixes:
1) Thread-safe analysis callback, which is required by Hydra since several compilation threads may be stepping on each others.
2) Updated the bloop-hydra-bridge version as it contains an important fix to
correctly handle invalidated classfiles.
For more details, please have a look at the commit messages.
Aspects that still need to be improved:
1) Shall we rename `IBloopAnalysisCallback` to something else?
2) A thread-safe Reporter is likely need for correct execution with Hydra. But switching the mutable data structures used in the different Reporter implementations into concurrent ones might be a first good approximation.
> Fix hydra integration and make tests succeed

- backend/src/main/scala/bloop/CompileBackgroundTasks.scala
- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
Before these fixes, using concurrent CLI clients would produce several
bugs. These bugs are completely addressed with these fixes, that I
tested manually.
Fixes https://github.com/scalacenter/bloop/issues/1181
Fixes https://github.com/scalacenter/bloop/issues/1189 (a dupe of the above)
Running the script in the first bug report, which starts 10
background bloop clients to run a main class works perfectly now.
> Fix bugs with non-stable CLI classes directories

- .github/workflows/ci.yml
The Hydra tests are skipped if the hydra.license doesn't exist. If a PR is
opened from an external repo, repositories' secrets cannot be decripted and
hence the hydra.license file should not be created because its content would be
wrong.
> Don't create the hydra.license file for PRs external to the repo

- integrations/sbt-bloop/src/sbt-test/sbt-bloop/hydra-support/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/hydra-support/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/hydra-support/test
The test checks that the generated bloop configuration includes the main Hydra
artifacts.
> Add sbt scripted test for hydra sbt integration

- config/src/main/scala/bloop/config/Config.scala
- config/src/main/scala/bloop/config/Tag.scala
- docs/assets/bloop-schema.json
- frontend/src/it/scala/bloop/CommunityBuild.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/DagSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/build.sbt
This field is used to add tags to the build target described by a given
configuration file. The tags of this target will then be exposed via the
`tags` property of BSP.
Currently, the existing integrations set the `test` tag for test
targets, and the `library` tag for all other targets.
> Add `tags` to Bloop configuration

- frontend/src/test/scala/bloop/HydraCompileSpec.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/hydra-support/project/plugins.sbt
We had a regression in Hydra 2.2.1 and hence it's recommended to use Hydra 2.2.2
with Bloop.
> Bump Hydra version for tests to 2.2.2

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
Previously, the JVM Test Environment request used
`state.commonOptions.workingDirectory` as the working directory,
resulting in IntelliJ using the incorrect working directory when
running tests for workspaces that configure the working directory via
`-Duser.dir=/path/to/cwd`. This commit fixes the issue so that
IntelliJ uses the correct working directory when running tests.
> Use correct working directory in BSP `buildTarget/jvmTestEnvironment`

- bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala
- bloopgun/src/main/scala/bloop/bloopgun/BloopgunParams.scala
- bloopgun/src/main/scala/bloop/bloopgun/util/Environment.scala
- bloopgun/src/main/scala/bloop/bloopgun/util/GlobalSettings.scala
- build.sbt
- docs/server.md
- launcher/src/main/scala/bloop/launcher/Launcher.scala
- launcher/src/test/scala/bloop/launcher/GlobalSettingsSpec.scala
- website/i18n/en.json
Previously, it was only possible to configure JVM options for the Bloop
server via the `$HOME/.bloop/.jvmopts` file. This commit adds a new way
to globally configure Bloop via `$HOME/.bloop/bloop.json`.
The JSON file supports two fields:
* `javaOptions`: which is equivalent to `$HOME/.bloop/.jvmopts`. For
backwards compatibility, Bloop continues to respect `.jvmopts` but for
new usage we should start recommending `bloop.json` instead.
* `javaHome`: to control what Java version the Bloop server should use.
Currently, it's difficult for users to control exactly what Java
version is picked when launching Bloop. For example, Java 11 may get
automatically used by IntelliJ 2020.1 calls the Bloop launcher
because IntelliJ runs on Java 11 itself.
Parse errors in `~/.bloop/bloop.json` cause the …
> Respect global configuration in `$HOME/.bloop/bloop.json`

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/io/ClasspathHasher.scala
- backend/src/main/scala/bloop/tracing/BraveTracer.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopNameHashing.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompilerPluginWhitelist.scala
This change introduces a way to hide some verbose fine-grained zipkin traces with a `bloop.trace.verbose` system property which defaults to `false`. This reduces the number of spans in a given trace around the neighborhood of 80% by culling some traces when the amount of time spent in those traced operations is very low, think microseconds or a few milliseconds in a compile taking a few seconds.
@olafurpg
> Hide fine-grained Zipkin traces behind system property

- docs/build-tools/overview.md
- docs/ides/intellij.md
- docs/ides/overview.md
Previously, the old IntelliJ documentation mentioned 2018.3, which is an
old version. The new docs recommend IntelliJ 2020.1, which has a lot of
improvements to the BSP integration.
> Update documentation for IntelliJ BSP integration.

- backend/src/main/scala/bloop/tracing/BraveTracer.scala
Currently, we manually create a root `TraceContext` in order to set the `debug` sampling flag. This change allows us to directly create a root span instead. What this means practically is that the root span will not have a `parentId` field, instead of the value it would have currently, which is not within the set of `spanId`s, causing certain validations to fail.
> Remove unnecessary TraceContext creation for root span

- bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala
- bloopgun/src/main/scala/bloop/bloopgun/BloopgunParams.scala
Bloopgun was parsing the `--help` flag, and not passing it further to
`bloop.Cli`, which would therefore never display the help.
Fixes #1224
> Don't parse `--help` from Bloopgun

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- project/Dependencies.scala
Depends on https://github.com/build-server-protocol/build-server-protocol/pull/113
Just implements the new endpoint, to currently be exactly the same as jvmTestEnvironment.
Fills in new optional parameters javaHome and javaVersion, currently based on the jvm that bloop is running on. In future we may allow to customize it through Config.Project
> Add buildTargets/jvmEnvironment endpoint

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/dap/DebuggeeRunner.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/test/resources/no-test-frameworks/build.sbt
- frontend/src/test/resources/no-test-frameworks/myProject/src/main/scala/Main.scala
- frontend/src/test/resources/no-test-frameworks/myProject/src/test/scala/Test.scala
- frontend/src/test/resources/no-test-frameworks/project/build.properties
- frontend/src/test/resources/no-test-frameworks/project/plugins.sbt
- frontend/src/test/resources/no-test-frameworks/project/project/build.properties
- frontend/src/test/scala/bloop/TestSpec.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
Bloop used to report an error when running the `test` task against a
project that has an empty list of configured test frameworks. This
behavior is not convenient for targets that do not have any test
framework configured, and for which Bloop cannot infer what project (if
any) is the test variant.
This commit changes the test task, so that an error is reported if it is
run against a project that has the test or integration-test tags, and
that has no test frameworks configured. When run against a project that
is not a test project, and that has no test frameworks configured, the
test task will report a warning indicating that no test frameworks were
found.
> Report test projects without test frameworks

- backend/src/main/scala/bloop/tracing/BraveTracer.scala
This change will allow users to set three properties:
1) `bloop.trace.localServiceName` with the default being `"bloop"` like before
2) `bloop.trace.traceStartAnnotation` if this is set, it will be annotated on every span right after the span is started.
3) `bloop.trace.traceEndAnnotation` if this is set, it will be annotated on every span right before the span is closed.
These additions will make it easier for consumers of zipkin trace data to label the spans as needed for existing data pipelines.
@olafurpg
> Add additional system properties for customizing zipkin traces

- website/i18n/en.json
- website/pages/en/setup.js
- website/siteConfig.js
The recent refactoring of the documentation (see #1209) moved the
installation instructions for every individual build tool supported, so
that the directory structure was different than the one for package
managers.
Unfortunately, this broke the JS which displays the installation step
(the documentation for every build tool was no longer found).
This commit restores the previous directory structure, which is
unfortunately not as flat.
Fixes #1220
> Fix build export installation step

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- project/Dependencies.scala
Previously jvmTestEnvironment was returning classpath containing
path-formatted items i.e `/home/user/lib`. Now they're URI-formatted
like `file:///home/user/lib`
It was specified in BSP 2.0.0-M10
> Make jvmTestEnvironment's classpath URI-formatted

- bloopgun/src/main/scala/bloop/bloopgun/util/Environment.scala
This commit increases the default stack size from 1m to 4m to overcome a
StackOverflowException that we hit on while compiling a Java codebase
using the Lombok annotation processor.
> Increase default stack size.

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspConnectionSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- project/Dependencies.scala
This endpoint is a mirror to jvmRunEnvironment. In current bloop
implementation they return exactly the same data. Accpording to this,
I extracted the code to to common functions, both in tests and
BloopBspServices
> Implement jvmRunEnvironment endpoint

- docs/performance-guide.md
When reading the docs i noticed this link no longer worked
> Change zipkin URL in docs

- config/src/main/scala-2.10/bloop/config/ConfigCodecs.scala
- config/src/main/scala-2.11-13/bloop/config/ConfigCodecs.scala
- config/src/main/scala/bloop/config/Config.scala
- docs/assets/bloop-schema.json
- frontend/src/it/scala/bloop/CommunityBuild.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Platform.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/LinkTask.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileDependenciesData.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
- frontend/src/test/scala/bloop/ConsoleSpec.scala
- frontend/src/test/scala/bloop/DagSpec.scala
- frontend/src/test/scala/bloop/ForkerSpec.scala
- frontend/src/test/scala/bloop/RunSpec.scala
- frontend/src/test/scala/bloop/TestSpec.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
Most build tools use a different classpath for compiling and running JVM
projects. This commit adds fields to represent the runtime classpath of
JVM projects in the Bloop configuration file.
The following fields are added to the JVM platform:
* `classpath`, which represents the runtime classpath of the project.
* `resources`, which represents the resources available to the project
at runtime.
When one of these fields is missing, Bloop will fallback to the field
with the same name in project definition.
Fixes #1233
> Support runtime classpath for JVM projects

- frontend/src/main/scala/bloop/dap/DebuggeeRunner.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
Issue: `jvmOptions` in `ScalaMainClass` have been ignored while running a debug session.
Note: not really sure, if the testing is done elegant enough, or can even be put into already existing `test`.
> Fixed providing jvm options in DAP

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/BloopParameters.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
AFAIK Gradle doesn't support Dotty.  This adds some support in the Bloop Gradle plugin until it does.
On calling `bloopInstall` specific parts of the config are overridden to mimic a Dotty project.
For a specific version of Dotty...
```groovy
bloop {
dottyVersion = "0.21.0-bin-20191031-9e7ec22-NIGHTLY"
}
```
or for the latest snapshot...
```groovy
bloop {
dottyVersion = "latest"
}
```
I haven't got a working Dotty project to test this on but hopefully I've covered the relevant sections.
> Add dotty support to gradle plugin

- config/src/main/scala-2.11-13/bloop/config/ConfigCodecs.scala
The `classpath` and `resources` were swapped, resulting in a wrong
config.
Fixes #1247
> Swap `classpath` and `resources` arguments

- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopAnalysisCallback.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/ConcurrentAnalysisCallback.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
Classfiles originating from Scala recompiled sources would be marked as
invalidated until after the Analysis object is created. This caused
issues with the `BloopForkedJavaCompiler`, which creates invalid
classfiles, since these invalid classfiles would be chosen over the new
ones, thus aborting compilation.
This commit changes the analysis callbacks used by Bloop so that the
generated classfiles are pushed to the classfile manager as soon as they
are known. Thanks to this change, no invalid classfiles will be created
for the recompiled sources.
> Register Scala generated class files before compiling Java

- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
Previously, we would replace the scalac options when Metals was the client.
Now, we make sure the base settings are used.
> Make sure we use all the settings that already exist in the project

- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/cli/Validate.scala
- frontend/src/main/scala/bloop/engine/Feedback.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/caches/StateCache.scala
- frontend/src/main/scala/bloop/util/Environment.scala
- shared/src/main/scala/bloop/io/AbsolutePath.scala
Previously, running `bloop help` or `bloop about` could fail when executed in a workspace that contained invalid `.bloop/*.json` config files. This can for example happen in the `$HOME` directory with `.bloop/bloop.json` global settings.  This commit refactors the `bloop help` and `bloop about` commands so that they print out a message and don't attempt to load the workspace JSON files.
Fixes #1249
> Make `bloop about` and `bloop help` always succeed

- backend/src/main/scala/bloop/CompilerCache.scala
- shared/src/main/scala/bloop/io/AbsolutePath.scala
We were using a forked javac process to compile Java sources in cases
where the `java.home` properties and the JVM platform of a project were
different, but pointed to the same file. Instead of comparing the two
paths to decide whether to fork, this commit compares the two files that
are pointed to by the paths.
> Support links in path to javac

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
Closes #1257 
I think the result is really nice, because:
- I run `~bloopInstall` in the background
- Any time I change a source file, `bloopInstall` is not triggered (those files are not watched by the source generation nor by `bloopInstall`)
- Any time I change a template file,  `bloopInstall` is triggered, and the generated sources are updated, the bloop config is not updated because it is already cached
- If I change the sbt settings, Metals propose me to import the build, and it overwrites the bloop config
- Most of the time I dont even need to reload my sbt shell in the background
> Force source generation for cached 'sbt bloopGenerate'

- bridges/scalajs-0.6/src/main/scala/bloop/scalajs/JsBridge.scala
- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/JsBridge.scala
- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/jsenv/JsDomNodeJsEnv.scala
- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/jsenv/NodeJsEnv.scala
- bridges/scalajs-1.0/src/main/scala/bloop/scalajs/jsenv/NodeJsHandler.scala
- bridges/scalajs-1.0/src/main/scala/org/scalajs/jsenv/nodejs/BloopComRun.scala
- bridges/scalajs-1.0/src/test/scala/bloop/scalajs/ScalaJsToolchainSpec.scala
- build.sbt
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/tasks/LinkTask.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaJsToolchain.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaNativeToolchain.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ToolchainCompanion.scala
- frontend/src/test/resources/cross-test-build-scalajs-1.0/build.sbt
- frontend/src/test/resources/cross-test-build-scalajs-1.0/project/plugins.sbt
- project/Dependencies.scala
This pull request adds partial support for Scala.js 1.0. Linking works already, but I am getting this stack trace when running tests from Bloop:
```shell
$ bloop test pine-js
[E] Referring to non-existent class org.scalajs.testing.bridge.Bridge
[E]   called from core module module initializers
[E] Referring to non-existent method static org.scalajs.testing.bridge.Bridge.start()void
[E]   called from core module module initializers
org.scalajs.linker.interface.LinkingException: There were linking errors
at org.scalajs.linker.frontend.BaseLinker.reportErrors$1(BaseLinker.scala:97)
at org.scalajs.linker.frontend.BaseLinker.$anonfun$analyze$5(BaseLinker.scala:106)
at scala.util.Success.$anonfun$map$1(Try.scala:255)
at scala.util.Success.map(Try.scala:213)
at …
```
> Add Scala.js 1.0 support

- backend/src/main/scala/bloop/io/ParallelOps.scala
- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/main/scala/bloop/bsp/BspServer.scala
- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/engine/State.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompilerPluginWhitelist.scala
This commit fixes a bug in the logic deleting the orphan bsp classes
directories that was not updated when the CLI client classes dir was
moved to behave like just a normal bsp client classes dir.
This bug could have produced important problems such as
`ClassNotFoundException`s when starting a new connection while a bloop
CLI command is running.
I don't think this issue is directly related with the metals connection
issues but it might.
> Don't consider CLI classes directory an orphan directory

- backend/src/main/scala/bloop/tracing/BraveTracer.scala
- backend/src/main/scala/bloop/tracing/TraceProperties.scala
- frontend/src/it/scala/bloop/CommunityBuild.scala
- frontend/src/main/scala/bloop/Bloop.scala
- frontend/src/main/scala/bloop/bsp/BloopBspDefinitions.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/TraceSettings.scala
- frontend/src/main/scala/bloop/data/WorkspaceSettings.scala
- frontend/src/main/scala/bloop/engine/Build.scala
- frontend/src/main/scala/bloop/engine/caches/StateCache.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/test/scala/bloop/BuildLoaderSpec.scala
- frontend/src/test/scala/bloop/TracerSpec.scala
- frontend/src/test/scala/bloop/bsp/BspIntellijClientSpec.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
- frontend/src/test/scala/bloop/io/ClasspathHasherSpec.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
Previously, it was only possible to customize the Zipkin integration globally via system properties.
This PR will make it possible to configure Zipkin integration properties per-workspace via `bloop.settings.json`. The motivation for this change is to make it possible to track compile/test metrics for Bloop only when working in a specific codebase.
> Add workpace settings for Zipkin traces

- build.sbt
It seems that under 2.10 `Config.Platform.Jvm(Config.JvmConfig(javaHome, launcher.getJvmArgs().toList), mainClass, None, None)` is serialized as:
```json
"platform" : {
"name" : "jvm",
"config" : {
"home" : "/usr/lib/jvm/java-11-openjdk",
"options" : [
]
},
"mainClass" : [
],
"classpath" : [
],
"resources" : [
]
},
```
and under 2.12 it is:
```json
"platform": {
"name": "jvm",
"config": {
"home": "/usr/lib/jvm/java-11-openjdk",
"options": [
]
},
"mainClass": [
]
},
```
With the 2.10 version the classpath does not contain the scala library and because of that anything we try fails to run:
https://github.com/scalameta/metals/issues/1805
I don't know the reason why we are keeping the maven plugin at 2.10, but this seemed like a good opportunity to upgrade.
> Update Maven Bloop Scala version to 2.12

- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/test/scala/bloop/TestSpec.scala
Commands like `bloop test foo` which failed because of a compilation
error were reporting a successful exit code, because
`Interpreter.compileAnd` continued the execution using the state before
compilation. This resulted in the failed exit status being lost.
> Keep `compiledState` in `Interpreter.compileAnd`

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
Previously, the Bloop BSP server recursively walked all directory
resource entries and returned individual files. Now, the BSP server
returns the URIs of the directories unchanged and leaves it up to the
client to recursively walk the directories, if necessary.
There's nothing in the BSP spec that says that resource URIs cannot be
directories. The current behavior looses information because client
won't be able to relativize resource items by their enclosing directory.
> Don't expand resource directory entries in BSP server

- integrations/maven-bloop/src/main/java/bloop/integrations/maven/BloopMojo.java
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
* Add some more properties, which may be nonsense just to get it to bloopInstall to run
* toRealPath requires the directory to exist, which it wont always, particularly if a module is just resources and no code.
> Fix bloopInstall in Maven when dirs don't exist

- .github/workflows/ci.yml
- bin/sbt-ci-release.bat
The native image binaries publishing on Windows is currently broken
because of an issue where sbt fails to find
org.scala-lang.modules#scala-xml_2.12;1.2.0!scala-xml_2.12.jar when sbt
is started with `cmd` rather than `bash`.
To workaround this issue, we launch sbt a first time with `bash`, and
then do the publishing with `cmd`.
Why it fails with `cmd` is a mystery to me.
> Workaround Windows publishing issue

- build.sbt
The release was calling the task `sonatypeBundleRelease`, which doesn't
exist (a command with the same name exists, however). To fix it, we call
the command `sonatypeBundleRelease`.
Fixes #1320
> Workaround releasing issue

- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileResult.scala
Previously, `GlobalError` contained only an error message, which means
that the exception causing a `GlobalError`, if any, was lost along with
the information it contains.
This commit adds an optional field holding the underlying exception,
which will be logged when present.
> Carry underlying error in `GlobalError`

- frontend/src/main/scala/bloop/io/SourceHasher.scala
- frontend/src/test/scala/bloop/io/SourcesGlobsSpec.scala
Globs allow us to define the maximum depth to search for source files.
When we reach this maximum depth, the `Files.walkFileTree` will call
`visitFile` on directories that cannot be traversed.
Previously, we were adding these directories to the list of items to
hash, which would cause an exception to be thrown.
> Ensure we don't hash directory when using globs

- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/test/scala/bloop/ConsoleSpec.scala
Fixes #1301 (`bloop console` exits with ClassNotFound exception).
Note, I manually tested 2.13 and 2.12 with this change. I'm not sure this ever worked for 2.11 or 2.10?
> Drop coursier '--scala-version' when launching bloop console 

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
Please forgive if this solution is naive, it appeared to fix my calling project though!
From the gradle java api docs:
```
String getName()
Returns the name of this project. The project's name is not necessarily unique within a project hierarchy. You should use the getPath() method for a unique identifier for the project.
```
This _does_ generate possibly "weird" looking project names with the colons in them, ie `:one:two:three`. I don't _think_ this is a problem, but we could def transform this if that's desired to look nicer. /shrug
> Use Project#getPath instead of #getName

- docs/build-tools/gradle.md
Fixed in 334b096080a11eef7b61cd37e686c00bbd2346b0
> Removed note in gradle docs about duplicate project names

- frontend/src/main/scala/bloop/dap/DebugSessionLogger.scala
Looks like in certain environments where a full VPN is enabled, using
`localhost` might cause discovery problems and might make Bloop fail
connect to the debug JVM. So we replace `localhost` with `127.0.0.1`.
> Change use of `localhost` by `127.0.0.1`

- backend/src/main/scala/bloop/logging/BloopLogger.scala
- frontend/src/test/scala/bloop/BloopLoggerSpec.scala
Previously, the `BloopLogger` would remove the colored prefix of the log
messages when colors were disabled via `--color` or `NO_COLOR`. However,
color that may be present in the log output (inserted by the running
application or a test framework for instance) would not be removed.
This commit preprocesses the log messages so that the ANSI colors are
removed from the log messages.
Fixes #1119
> Strip ANSI color escapes when colors are disabled

- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/testing/TestInternals.scala
- frontend/src/test/resources/custom-test-framework/build.sbt
- frontend/src/test/resources/custom-test-framework/framework/src/main/scala/foo/Framework.scala
- frontend/src/test/resources/custom-test-framework/project/build.properties
- frontend/src/test/resources/custom-test-framework/project/plugins.sbt
- frontend/src/test/resources/custom-test-framework/project/project/build.properties
- frontend/src/test/resources/custom-test-framework/test/src/test/scala/foo/MyTest.scala
- frontend/src/test/scala/bloop/TestSpec.scala
Bloop was collecting all the test fingerprint, and creating a test task
for every matching fingerprint. This meant that test classes would be
run as many times as they have matching fingerprints.
Bloop now follows the same behavior as sbt, which will run the test with
the first matching framework.
Fixes #1358
> Fix #1358: Run test classes only once

- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
When creating a manifest JAR, `JvmProcessForker` would add a trailing
slash to all the directory entries. While this trailing slash is
apparently necessary, it would be added also to entries that already
have a trailing slash. As a result, the path to resources resolved from
a directory entry ending with a double slash would contain this double
slash.
> Add trailing slash only when necessary in manifest

- frontend/src/main/scala/bloop/testing/TestInternals.scala
- project/Dependencies.scala
A fix that prevents test suites to be run twice or more was recently
merged to sbt/sbt, but it hasn't been released yet (see
https://github.com/sbt/sbt/pull/5800).
To avoid waiting for the next sbt release, we manually published the
fixed artifact. This commit makes Bloop use this artifact.
> Use forked test agent

- frontend/src/main/scala/bloop/data/Project.scala
Bloop tries to guess the current working directory to use from the java
options. Before, it'd incorrectly use the first `user.dir` and not look
for further occurrences. It turns out that the JVM will use the last
occurrence of this property instead.
> Select last `user.dir` when inferring cwd

- integrations/maven-bloop/src/main/java/bloop/integrations/maven/BloopMojo.java
- integrations/maven-bloop/src/main/java/scala_maven/ExtendedScalaContinuousCompileMojo.java
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
Currently we only generate config for a maven module if we detect the Scala compiler plugin. With this change, we always generate it, but only add the scala libraries for scala modules. Also try to take into account the compile order from the .pom and any Java compiler args.
I don't think this is perfect by any means (it doesn't compile Neo4j for example due to #1322) , but I think it's better than what we currently have. Might be enough to close #519 though.
> Support for Java Modules

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/BloopInstallTask.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
This changes the way artifacts (jars) are resolved so that it copes with unresolvable configurations which can pop-up in complex Gradle projects.
This is mainly because I was getting issues with [Gradle Crossbuild Scala Plugin](https://github.com/prokod/gradle-crossbuild-scala)
The strict dependencies on main sourceset are no longer needed because the classpath handling is more comprehensive.
> Handle issues in Gradle artifact resolution

- launcher/src/main/scala/bloop/launcher/bsp/BspBridge.scala
Turns out `status.output` was always empty, so we never really got diagnostics about why the connection failed.
> Print logs in case of bsp connection issues

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/syntax.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
Switch from using Gradle Conventions to Extensions to interrogate Gradle. [Conventions being phased out](https://guides.gradle.org/implementing-gradle-plugins/#extensions_vs_conventions)
Override platform JVM options with `Application#applicationDefaultJvmArgs`.  Fixes #1377 
Handle alternative way of specifying mainclass: `Application#mainClass`. Fixes #1375
> Handle Gradle jvm args and mainClass

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/dap/DebugSession.scala
- frontend/src/main/scala/bloop/dap/DebuggeeRunner.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspConnectionSpec.scala
- frontend/src/test/scala/bloop/dap/DebugAdapterConnection.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
- frontend/src/test/scala/bloop/dap/DebugTestClient.scala
- frontend/src/test/scala/bloop/dap/DebugTestEndpoints.scala
- project/Dependencies.scala
A first draft of adding support of remote debugging in bloop.
It seems that a new value for `DebugSessionParamsDataKind ` should be addend to BSP. I'd love your input if this is the way to go and what else needs to be changed or updated.
I have added a "happy path" test so far and I have also done some manual tests using a version of `metals` with necessary changes
> Support remote debugging

- docs/tools/aur/install.md
- docs/tools/aur/usage.md
- Replace outdated AUR helpers by `yay`
- Mention the `bloop-systemd` package
closes #1390
> Fix AUR installation docs

- backend/src/main/scala/bloop/ScalaInstance.scala
- backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala
- frontend/src/test/scala/bloop/ScalaVersionsSpec.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
Fixes https://github.com/scalacenter/bloop/issues/1394
There was recent change, which moved Dotty back to Scala organisation and renamed artifacts to use `scala3` instead of Dotty.
I see there is also one small issue in the zinc fork: https://github.com/scalacenter/zinc/blob/topic/bloop-rebase-next-2.0/internal/zinc-classpath/src/main/scala/sbt/internal/inc/ScalaInstance.scala#L123
I have no idea how to properly update the zinc used in Bloop, I don't see any main branch or how things can be released.
> Update Dotty to Scala 3

- config/src/main/scala-2.10/bloop/config/ConfigCodecs.scala
- config/src/main/scala-2.11-13/bloop/config/ConfigCodecs.scala
- config/src/main/scala/bloop/config/Config.scala
- docs/assets/bloop-schema.json
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Platform.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/test/scala/bloop/RunSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
Previously, Bloop would support only a single JDK configuration per
project, which would apply to both compile-time and runtime. However,
some tools (e.g. Pants) support defining a different JDK configuration
for compile-time and runtime.
To be able to export faithfully builds from these tools, Bloop needs to
support this kind of configuration as well. This commit adds a new
field, `runtimeConfig`, to JVM projects' `platform` configuration, which
has the same schema as the existing `config`.
The `config` is used to configure the compile-time configuration,
whereas `runtimeConfig` is used for runtime. When `runtimeConfig`
doesn't exist, Bloop falls back to `config`.
> Support runtime JDK config

- frontend/src/main/scala/bloop/engine/tasks/compilation/CompilerPluginWhitelist.scala
While testing new Bloop version in Metals I noticed we were getting a warning about unsupported compiler options.
This was coming from CompilerPluginWhitelist, which I missed. I added `3.`, which will ignore all versions starting with `3.`
> Add 3.0 to scalaVersionBlacklist for compiler plugin classloading

- notes/v1.4.5.md
I repurposed the script in Metals to generate the release notes here. Not sure if anyone is interested in putting it into Bloop itself, but the script is available here: https://gist.github.com/tgodzik/e4d4bf84db2f18e5cef143acd6730d5f
> Add release notes for 1.4.5

- docs/assets/bloop-schema.json
The new URL is apparently `https://scalacenter.github.io/bloop/docs/assets/bloop-schema.json`
> Fix broken URL in $id of bloop-schema.json

- docs/build-tools/maven.md
It looks like Bloop is no longer published for Scala 2.10, but it published for Scala 2.12 instead. This edit reflects that change.
> Documentation: update maven plugin version number

- .github/dependabot.yml
- .github/workflows/ci.yml
Curently the CI is broken,  the change was similar in the scalameta repositories.
> Update setup-scala action to v10 and setup dependabot

- project/ReleaseUtils.scala
Follow up from https://github.com/scalacenter/homebrew-bloop/pull/11
homebrew-bloop is being regenerated with the new releases
> Fix brew formula for future releases

- .github/workflows/ci.yml
Based on https://github.com/actions/download-artifact#compatibility-between-v1-and-v2
> Fix incompatibility for actions/download-artifact

- backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala
- project/Dependencies.scala
The new version matches this commit:
https://github.com/scalacenter/zinc/commit/edbe573e75f7da060f9bd64b12d86fcd59c2c811
This commit fixes an issue where Zinc tries to initialize symbols that
are missing from the classpath. There are legitimate situations where
symbols can be missing from the classpath, such as when Bloop's
configuration files originate from Pants with `strict_deps` enabled, for
instance.
See sbt/zinc#949 and sbt/zinc#950
> Bump to latest Zinc

- .github/workflows/ci.yml
Newer versions of the GitHub action `actions/checkout` do not fetch all
tags when cloning, preventing us from computing the current version
number correctly. This can be seen from the most recent releases to
Maven Central, that have as version number `0.0.0-1-<sha>`.
This commit fixes the issue by performing a deep clone.
> Fetch tags when cloning

- frontend/src/main/scala/bloop/testing/TestInternals.scala
- project/Dependencies.scala
While waiting for the release of sbt 1.4.0, we published a fork of sbt's
test-agent. Now that sbt 1.4 has been released with the fix that we
needed, we can safely go back to using the mainline artifact.
See #1364
See sbt/sbt#5800, sbt/sbt#5801
> Go back to sbt test-agent artifact

- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
Tests can be run in parallel since https://github.com/scalacenter/bloop/pull/935/.
> Remove outdated comment

- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/ScalaVersionsSpec.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
-Ysemanticdb flag should be still avialable, but it does no longer work, which is why we needed to change it now.
> Change the semanticdb flag to -Xsemanticdb starting from 3.0.0-M3

- integrations/sbt-bloop/src/main/scala-sbt-0.13/bloop/integrations/sbt/Compat.scala
- integrations/sbt-bloop/src/main/scala-sbt-1.0/bloop/integrations/sbt/Compat.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/meta-builds/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/meta-builds/test
It seems that due to https://github.com/sbt/sbt/pull/6085/files we will no longer resolve sbt artifacts when running with coursier, which is the default.
sbt will instead try to use artifacts from the launcher, which does not seem to work in case of plugins.
There is an existing issue https://github.com/sbt/sbt/issues/6203, but in the meanitime we can force resolution using:
```scala
Keys.reresolveSbtArtifacts := true
```
> Fix issues with meta builds not resolving sbt artifacts

- frontend/src/main/scala/bloop/engine/BuildLoader.scala
Scala 3 in contrast to Scala 2 does not need to download the semanticdb plugin separately, but only to enable the -Xsemanticdb flag.
> Don't show message about unsupported Scala version for Scala 3

- backend/src/main/scala/bloop/ScalaInstance.scala
- backend/src/main/scala/bloop/ScalaInstanceTopLoader.scala
Because the Scala 3 compiler depends directly on `org.scala-sbt:compiler-interface`, it must load the `xsbti.*` classes from the same class loader than Bloop. Otherwise we have `LinkageError` exception.
The current Scala 3 compiler bridge hacks its own class loader to avoid `LinkageError` but this solution is fragile and it won't work with Zinc 1.4.x. This PR makes it possible to remove that hack from the compiler: https://github.com/lampepfl/dotty/pull/10960.
This PR introduces the `ScalaInstanceTopLoader`: the parent of the `ScalaInstance.loader` that loads the `xsbti.*` classes from the Bloop loader.
Similar solutions are already used in:
- https://github.com/sbt/sbt/pull/6199
- https://github.com/lihaoyi/mill/pull/1019
> Add ScalaInstance top class loader

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
Handle `annotationProcessor` keyword in Gradle dependencies
Handle `java.srcDirs` and `resources.srcDirs` being the same
Add a few missing tests to Gradle `bloopInstall` settings
Don't save empty projects settings - cuts down on Bloop JSON project file size
fixes #1441
fixes #962
I don't use either of the above so hopefully this covers all the use cases.
> Gradle enhancements

- bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
When running the `console` command an additional `--out-file` parameter is added by Bloopgun, which Bloop will write an ammonite command to. This command would hover be written as arguments separated by spaces, which makes it not work in case of workspaces containing spaces. Here, I change it to newline to avoid the issue.
Fixes https://github.com/scalacenter/bloop/issues/1448
> Fix issues when starting console within workspaces that include a space

- frontend/src/main/scala/bloop/dap/DebuggeeRunner.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
- frontend/src/main/scala/bloop/testing/TestInternals.scala
- frontend/src/test/scala/bloop/ForkerSpec.scala
To unblock the issue https://github.com/scalameta/metals/issues/2489 in Metals, Bloop must handle `jvmOptions` without the `-J` prefix in the `debugSession/start` request.
For instance the following `scalaMainClass` is correct and Bloop should be able to execute it:
```
"data": {
"class": "ch.epfl.scala.index.server.Server",
"arguments": [],
"jvmOptions": [
"-Djna.nosys\u003dtrue"
],
"environmentVariables": []
}
```
> Handle jvmOptions without -J prefix in debugSession/start request

- shared/src/main/scala/bloop/io/Environment.scala
Previously line separator would be a non-exhaustive match and could throw an exception if an unknown shell was found. Now it defaults to `System.getProperty("line.separator", "\n")`
Fixes https://github.com/scalacenter/bloop/issues/1460
> Fix issue when unknown SHELL was defined

- build.sbt
- project/Dependencies.scala
Fixes https://github.com/scalacenter/bloop/issues/1463
scala-collection-compat is brought in by coursier and since `scala` is added to be ingored when shading, it never ends up properly on the classpath of bloopgun. This fixes the issues by adding the dependency directly. It's binary compatible, so it should not be an issue in case of conflicts.
> Fix issues with scala-collection-compat missing in bloopgun

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/PluginUtils.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
This is a proposed fix to address the issue in https://github.com/scalacenter/bloop/issues/1472
1. Extract and reuse existing function `canRunBloop` to determine if a Gradle sub-project is a bloop capable project or not. 
2. Change all occurrences of  `getAllprojects`  with the newly introduced function.
3. Minor change to replace `map` and then `flatten` with `flatMap`
4. Test
> Integrations: Gradle: Fix: Ignore non bloop capable projects when getting all projects

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/BloopParameters.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/syntax.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
This should fix #1488
There's also a fix for handling latest Dotty version format from the [website](https://dotty.epfl.ch/versions/latest-nightly-base)
Also preparation for changing tests to handle Gradle 7.0 but is blocked by https://github.com/gradle/gradle/issues/17042
> Gradle improvements

- .github/workflows/ci.yml
- backend/src/main/scala/bloop/DependencyResolution.scala
- bloopgun/src/main/scala/bloop/bloopgun/core/DependencyResolution.scala
- docs-gen/src/main/scala/bloop/docs/ReleasesModifier.scala
- docs/contributing-guide.md
- etc/bloop-coursier.json
- frontend/src/test/resources/compiler-plugin-whitelist/build.sbt
- project/BuildPlugin.scala
The bintray repo does no longer work, so let's make sure it's not used. We were already publishing to Sonatype so this should not be an issue.
> Remove all trace of bintray

- .gitmodules
Previously, it was useful for quick interation of the BSP protocol, which is much more stable today.
> Remove unused bsp submodule

- project/Dependencies.scala
2.0.2 was released on Java 9, which breaks on JDK 8
We should most likely stop using nuprocess, it's causing us way to many issues.
> Revert nuprocess to 2.0.1

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/SemVer.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/syntax.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/BloopInstallTask.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/ConfigureBloopInstallTask.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/PluginUtils.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
- project/BuildPlugin.scala
- project/Dependencies.scala
This is an attempt at supporting the Gradle Android plugin.
The Android plugin appears to use its own way of managing sourcesets/variants/flavors etc. so there's not huge amounts of commonality between it and the Java/Scala plugins that can be exploited.  Instead I've duplicated a lot of code from the current handling of Java/Scala plugin.  I think this is actually a good thing as just in the few Android SDK versions I've tested, the API has changed and I think it'll be easier to support if the code paths are separate.
There are a few caveats here...
1) Android uses VariantTransforms to handle dependencies on java only (i.e. none Android) Gradle projects.  These transforms have to be applied when Gradle creates the classpath and the transforms require the project's output jar file to …
> Add Gradle Android plugin support

- frontend/src/main/scala/bloop/dap/DebuggeeLogger.scala
This causes any client to log all output messages twice, one in the official output for example in the editor and the second time in the logs, which can just grow the logs without purpose.
We should still be able to print it under debug flag.
Connected to https://github.com/scalameta/metals/issues/2311
Tested it locally and it works correctly. There is no need for logging all output since everything goes through DAP anyway.
> Do not log debug output on info level

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/BloopInstallTask.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
Don't add `-source` or `-target` javac options if `--release` is present
Don't set `-source` or `-target` from default jvm if not set by Gradle build
Ignore `FileAlreadyExistsException` exceptions on `.bloop` dir creation.  It's a function of parallel export of multiple projects.
> Gradle: handle --release and multi-threaded dir create

- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/test/scala/bloop/nailgun/NailgunSpec.scala
- website/core/Footer.js
Previously the about message would be:
```
bloop v1.4.8-90-77e59d70-20210802-1858
Using Scala v2.12.8 and Zinc v1.3.0-M4+46-edbe573e
Running on Java JDK v1.8.0_292 (/usr/lib/jvm/java-8-openjdk-amd64/jre)
-> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```
now:
```
bloop v1.4.8-90-77e59d70-20210802-1858
Using Scala v2.12.8 and Zinc v1.3.0-M4+46-edbe573e
Running on Java JDK v1.8.0_292 (/usr/lib/jvm/java-8-openjdk-amd64/jre)
-> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center and the community.
```
Since the developers list is not actively updated and there has been a lot of community contributions I think it's a good idea to recognize it in the …
> Recognize the community contributions

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/BloopParameters.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
@tgodzik Very nice job on the Gradle 3 support
This PR handles Scala 3 Gradle projects setup using https://github.com/gradle/gradle/pull/18001
The specific Dotty handling is gone as it's no longer needed
The tests for Scala 3 are commented out until https://github.com/gradle/gradle/pull/18001 is merged and we know what Gradle version it will be released under
Up to you if you want to merge this now and then use the snapshots.  I've tested locally and seems fine.  Shouldn't cause anyone an issue with Scala 2 unless they were using the `dottyVersion` override but then they can stick with an early version of the bloop Gradle plugin.
> Initial Gradle Scala 3 support

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/optional-dependency/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/optional-dependency/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/optional-dependency/test
I don't use SBT much so I may be misinterpreting its dependency scopes but I think `Optional` isn't currently handled properly
Consider project `A` depends on `B` which depends on `C`
Project `B` uses `Optional` scope to depend on `C`
So `C` should feature in the compile classpath of `B` but **not** in the compile classpath of 'A' (as it shouldn't be included transitively)
This was already happening but before this PR there was no **project** dependency from `B` to `C` which Bloop needs to work out that it should compile `C` before `B`.
If I'm wrong on that then don't merge this PR but I think `Optional` should behave exactly like `Provided` because the runtime classpaths aren't currently exported and that's where `Optional` and `Provided` differ.
Relevant …
> support sbt Optional scope in bloopInstall

- frontend/src/main/scala/bloop/io/ServerHandle.scala
It seems `ServerHandle.uri` is only used for logging purposes, no need to parse it as a `java.net.URI`.
In particular, when using Windows named pipes (like `bloop bsp --protocol local --pipe \\.\pipe\foo`), `ServerHandle.WindowsLocal.uri` crashes because of the back-slashes when trying to parse it as a URI.
> Don't unnecessarily parse server handle as URI

- integrations/maven-bloop/src/main/java/bloop/integrations/maven/BloopMojo.java
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/maven-bloop/src/test/resources/multi_dependency/module1/pom.xml
- integrations/maven-bloop/src/test/resources/multi_dependency/module2/pom.xml
- integrations/maven-bloop/src/test/resources/multi_dependency/pom.xml
- integrations/maven-bloop/src/test/scala/bloop/integrations/maven/MavenConfigGenerationSuite.scala
- project/BuildPlugin.scala
- project/Dependencies.scala
Previously, we the Bloop Maven plugin would try to download all jars including ones that come from uncompiled subprojects. Now, we will only download external dependencies.
This was done via several steps:
- `requiresDependencyResolution` was replaced by `requiresDependencyCollection` which doesn't try to resolve the jar, but resolves information about all the tranisitive dependencies using pom
- to download the jars we use aether component `RepositorySystem`
- we will resolve both file and source files, if they exist we will write the correct config for Module, but also update file reference in the Artifact, which is null without resolution (caused by the first point). Thanks to the last step we will be able to get the correct classpath of the project
Additionally, since we no longer …
> Download only external dependencies in multi module Maven projects

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
The plugin wasn't respecting the order of the scala libraries on the classpath so Scala 3 version never got taken
When Gradle 7.3 is out I'll uncomment the tests but they work locally with the snapshot distribution
> Set correct Scala version when multiple scala libraries are on Gradle classpath

- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/maven-bloop/src/test/resources/no_library/pom.xml
- integrations/maven-bloop/src/test/scala/bloop/integrations/maven/MavenConfigGenerationSuite.scala
You can use the Scala Maven plugin without adding any actual Scala dependencies, which will cause the Scala library to be missing.
Previously, we would not be able to compile such project. Now it's possible both to compile and to resolve sources.
Fixes https://github.com/scalacenter/bloop/issues/1020
> Automatically add Scala library if it's not added explicitly

- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/main/scala/bloop/bsp/BloopBspDefinitions.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/data/SemanticdbSettings.scala
- frontend/src/main/scala/bloop/data/WorkspaceSettings.scala
- frontend/src/main/scala/bloop/engine/Build.scala
- frontend/src/main/scala/bloop/engine/BuildLoader.scala
- frontend/src/main/scala/bloop/engine/Feedback.scala
- frontend/src/main/scala/bloop/engine/caches/SemanticDBCache.scala
- frontend/src/test/scala/bloop/BuildLoaderSpec.scala
- frontend/src/test/scala/bloop/bsp/BspIntellijClientSpec.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
Allows the SourceGraph LSIF java plugin to be specified by Metals just like the Scala SemanticDB plugin can be
@olafurpg You mentioned that the output files will have to be deleted by Bloop as the plugin doesn't remove them.  Is this purely for when Java files are deleted so their matching `META-INF/**/JavaClassName.semanticdb` is also deleted?  I haven't done this and I'm not really sure where to start here.  Do you know if there is similar functionality in Bloop already for this - e.g. wiping the equivalent class files when their source files are deleted?  And if so where that is in the code.
> Support Java semanticDB plugin

- README.md
- docs/build-tools/gradle.md
- docs/build-tools/maven.md
- docs/build-tools/mill.md
- docs/build-tools/sbt.md
- docs/debugging-reference.md
- docs/guide/last-step.md
- docs/performance-guide.md
- website/core/Footer.js
I also updated the link to never go outdated.
> Replace all references to the Bloop gitter channel

- project/GitUtils.scala
Previously, describe would return a wrong tag, which wasn't the lastest published tag. Now we lsit tags explicitely and get the last one.
Fixes https://github.com/scalacenter/homebrew-bloop/issues/17
> Fix issues with last tag not being detected properly

- backend/src/main/scala/bloop/BloopComponentsLock.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/dap/BloopDebuggeeRunner.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/data/SourcesGlobs.scala
- frontend/src/main/scala/bloop/engine/caches/ExpressionCompilerCache.scala
- frontend/src/test/scala/bloop/dap/DebugAdapterConnection.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
- frontend/src/test/scala/bloop/dap/DebugTestEndpoints.scala
- launcher/src/test/scala/bloop/launcher/LauncherBaseSuite.scala
- project/Dependencies.scala
Upgrade to scala 2.12.13 to be able to test expression evaluation. The tests were running with Scala 2.12.8 but expression evaluation is only available on Scala 2.12.10 or greater.
Upgrade scala-debug-adapter to 2.0.2, the debug server now needs:
- a set of all the class path entries to be able to map the source files to the class files
- the jvm runtime
- the expression compiler class loader containing the expression-compiler jar and the compiler jars
Add a simple test on expression evaluation.
Warning: After merging this PR, Bloop debug session will no longer be compatible with the current version of Metals. https://github.com/scalameta/metals/pull/2959 in Metals intends to fix this.
> Add expression evaluation for Scala 2.12 and 2.13

- notes/v1.4.11.md
This includes the fix for 2.13.7, so it's important to have it easily available for users.
> Add release notes for 1.4.11 release

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
I don't think there's a nice way to create names on this type of clash. I've ended up just adding a number on the end of the `project-sourceset` name.
I've also excluded tests when the testing jvm is a later version than the Gradle version supports.  See [here](https://docs.gradle.org/current/userguide/compatibility.html).
This does seem to have caused the github diff to go bananas.  There's only 1 new test `worksWithDuplicateTargetNames1` and then I've indented all the others because of adding the check `supportsCurrentJavaVersion`
Fixes #1624
That example should end up with...
| project | sourceset | bloop name |
| - | - | - |
sql|main|sql
sql|test|sql-test-2
sql-test|main|sql-test
sql-test|test|sql-test-test
Another option would have been
| project | sourceset | bloop name |
| - | - | …
> Handle gradle project-sourceset name clashes

- etc/fish-completions
Mainly its fix for #1479 issue.
The problem is that when we don't have all 3 parameters in parsed
`if test -n $parsed[1] -a -n $parsed[2] -a -n $parsed[3]`
after read all vars script will look like this (for example we have only $parsed[1] = fizz)
`if test -n fizz -a -n -a -n` which is not proper syntax
Another small fix (in _testsfqcn) is for redundant `Argument --project: argument missing` in autocomplete list.
Its cause sometimes we call _testsfqcn without --project arg
> Fix fish completions error

- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
Fixes https://github.com/scalacenter/bloop/issues/1627
> [Maven] Make sure correct classifier is used when downloading artifacts.

- config/.js/src/main/scala/bloop/config/PlatformFiles.scala
- config/.jvm/src/main/scala/bloop/config/PlatformFiles.scala
- config/src/test/scala/bloop/config/utils/BaseConfigSuite.scala
Config module is cross published for JVM and JS, which means that config-test is also compiled with both. This is causing compilation errors for `BasicConfigSuite`, although it is never actually used in tests for js, which is why it wasn't failing on CI. This PR is just to get rid of that annoying error.
> Fix JS compilation errors

- frontend/src/main/scala/bloop/data/Project.scala
Fixes the following:
- project was exported and has `platform.jdk.home=${jdk8-home}`
- bloop was started using jdk17
- bloop tries to check if there is a need to pass jdk17 flags for
semanticdb-java
- ${jdk8-home} doesn't have `/release` and we incorrectly mark jdk8
as jdk17
- compile fails with:
```
[W] Unexpected javac output: Unrecognized option: --add-exports
[W] Error: Could not create the Java Virtual Machine.
```
> [Java] Don't pass `--add-export` semanticdb flags to jdk8

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/CompilerCache.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
It's required to correctly support java-semanticdb plugin on jdk17.
Fixes #1651
> Fork JavaCompiler in case if there are `-J` flags

- notes/v1.4.12.md
The release is need for Java support in Metals.
> Add release notes for Bloop 1.4.12

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
I'm in a situation where I want to generate bloop files for all projects for all scala versions.
Unfortunately, if we have the following project graph
```scala
lazy val a = project.settings(crossScalaVersions := List("2.13.0", "3.0.0"))
lazy val b = project.settings(crossScalaVersions := List("2.13.0")).dependsOn(a)
```
and then `+bloopInstall` may fail for `b` when generating for scala `3.0.0`, because it'll then use the `3.0.0` version of `a` and `2.13.0` of `b`.
I have seen errors like this:
```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef...:
[error]    org.scala-lang.modules:scala-collection-compat _3, _2.13
[error]    com.lihaoyi:sourcecode _2.13, _3
[error]    org.typelevel:simulacrum-scalafix-annotations _2.13, _3
[error] …
```
> Continue if `bloopGenerate` fails for a project

- project/Dependencies.scala
I'm [currently seeing](https://github.com/coursier/setup-action/runs/5028748027?check_suite_focus=true#step:15:40) issues with the native Bloop `1.4.2` launcher on Windows (complaining that it can't find the `sun.misc.BASE64Encoder` class, via directories, shaded in coursier-interface).
Updating coursier-interface might fix it (directories should ship with the right config since https://github.com/dirs-dev/directories-jvm/pull/33, I suspect it might be missing in coursier-interface `1.0.4`).
> Update coursier-interface to 1.0.6

- build.sbt
- project/Dependencies.scala
There is already a convetion to duplicate projects for different scala versions and it was much easier to do the same thing for  `(bloopgun, launcher) x (core, shaded) x (2.12, 2.13)`
> feat: publish launcher_2.13 artifacts

- build.sbt
ok, https://github.com/scalacenter/bloop/runs/5159830970?check_suite_focus=true failed because of `releaseLauncher` command which I forgot to delete.
> ci, build: fix release command

- project/build.sbt
CI ended with exactly the same error as described in https://github.com/scalameta/mdoc/pull/445
> build, fix: bump mdoc plugin because of `java.lang.NoClassDefFoundError: scala/tools/nsc/reporters/AbstractReporter`

- frontend/src/test/scala/bloop/BaseCompileSpec.scala
- frontend/src/test/scala/bloop/DeduplicationSpec.scala
- frontend/src/test/scala/bloop/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/TracerSpec.scala
It seems a number of tests have a very low tolerance, especially some test which actually have in-built delays and usually have 1-2 second tolerance. This seems to be a bigger issue on Windows.
> Fix timeouts on Windows tests

- .github/workflows/ci.yml
It seems that the version available on the github page is not the one we can use unfortunately.
> Fix upload artifacts version

- .github/workflows/ci.yml
Benchmark step was failing at least for 2 months - https://github.com/scalacenter/bloop/runs/4675462587?check_suite_focus=true
We can investigate what's going on there but until it's fixed this step can be removed - this action will unblock https://github.com/scalacenter/bloop/pull/1679
> fix: remove benchmark step from CI

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/bsp/ScalaTestSuites.scala
- frontend/src/main/scala/bloop/dap/BloopDebuggeeRunner.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
Related PR can be found here https://github.com/scalacenter/scala-debug-adapter/pull/198
> chore: adjust scala test suites to sbt's implementation.

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
Previously, we removed both generatedClassFile and rebasedClassFile from invalidations, but we only did it for rebased product files such as `.tasty`. Now we do it for both
I am not 100% sure why sometimes invalidations happen for rebased and sometimes for generated files, but that can happen according to the comment above.
What happened here is that the generated files existed, but the rebased one was in the invalidation list, so later on we would skip it.
This was causing the issues in https://github.com/scalameta/metals/pull/3706
> Fix copying tasty files on incremental compilation

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
Previously, the BSP endpoint `buildTarget/inverseSources` was not
implemented, even though Bloop declares itself as supporting this
endpoint.
This commit provides an implementation of this endpoint.
> Implement buildTarget/inverseSources BSP endpoint

- bloopgun/src/main/scala/bloop/bloopgun/util/Environment.scala
This is no longer a supported method of specifying the server properties. Users should instead us `$HOME/.bloop/bloop.json`
> Remove the possibility to read proeprties from.jvmopts

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
This should help with investigations in #1713
> fix: sbt-bloop - add cause to error log if bloopGenerate fails

- build.sbt
- project/BuildPlugin.scala
Fixes the issue that was found by @kpodsiad in https://github.com/scalacenter/bloop/pull/1706#issuecomment-1091992342
> fix: stabilize test project resources generation

- backend/src/main/scala/sbt/internal/inc/bloop/BloopZincCompiler.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopHighLevelCompiler.scala
Previously we created compiler arguments on the Bloop side and it turns out that it's already being done in Zinc, so this way we duplicate some of the options. Now, we just use the user scalacOptions, while Zinc takes cares of the other options.
Fixes https://github.com/scalameta/metals/issues/3766
> Fix duplicate compiler classpath and bootclasspath options

- .github/workflows/ci.yml
I removed `onload` resources generation and then I extracted two additional actions on CI. 
Finer grained CI actions should reduce main tests duration and provide a better experience when debugging CI.
> ci: break CI actions into smaller pieces

- project/ReleaseUtils.scala
Previously it would try to find `bloop.json` in $dir, which did not exists as we were downloading coursier-bloop.json.
Now, we just install specific Bloop version using the default channels, which should work correctly.
> Fix scoop install script

- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
Previously, `bloop clean` would only clear the results cache, but the
class files would be left untouched on the disk. This commit changes
this, so that the `clean` command doesn't exit until the classfiles of
the last result, and the classes directory of the current client are
deleted.
Fixes #1388
> Remove class directories in `clean`

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/dap/BloopDebuggeeRunner.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
- project/Dependencies.scala
The most recent milestone works much better thanks to @adpi2 :tada: !
I plan to release 1.5.1 next, because the clean functionality got fixed.
> Bump scala-debug-adapter with fixes for Scala 3

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/dap/BloopDebuggeeRunner.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
This popped up in https://github.com/scalameta/metals/pull/4078
I will follow up with a quick 1.5.2 release.
> bugfix: Allow to run using DAP in Java only projects

- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/maven-bloop/src/test/resources/test_jars/pom.xml
- integrations/maven-bloop/src/test/scala/bloop/integrations/maven/MavenConfigGenerationSuite.scala
Update: this is indeed a separate issue with the fix provided in https://github.com/scalacenter/bloop/pull/1747/commits/3a1d935f9c37bc8ad26ffdeb79ad367f6302971a
---
_context:_
The problem I saw is related to #1727, but in the case of a test-jar external dependency - it wasn't being added to test scope classpath at all.
~~While tinkering at it, I also noticed that manual translation between Aether and Maven's `Artifact` types is not required, as there seems to be a method for that, used in Maven's own sources.~~ Turns out it's not part of public API so it's better not to use it.
And finally, I added a test to specifically verify that `<...>-tests.jar` is resolved.
I think this "fix" is somewhat different to #1727, and is worth a separate review.
> Fix resolution of test-jar artifacts

- build.sbt
- project/project/build.sbt
It seems these are spurious dependencies (maybe these are there for historical reasons?). sbt-bloop only needs bloop-config, and buildpress is fine with just bloopgun and bloop-shared.
> sbt-bloop and buildpress don't depend on launcher

- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/maven-bloop/src/test/scala/bloop/integrations/maven/MavenConfigGenerationSuite.scala
test-jar dependencies not only have a different suffix for regular jars `-tests.jar`, but they also have a different one for test sources :D `-test-sources.jar` notice that it's `test` not `tests`.
They also need to have a different classifier (`test-sources`).
`resolveArtifact` now takes `sources: Boolean` parameter instead of a wider `classifier: Option[String]` - we only ever use it to download sources, so we can tighten down the method contract.
I would also argue that `resolveArtifact` needs to return `case class ResolvedArtifact(af: Artifact, sources: Boolean, file: File)` so that we don't need to do this string manipulation with jar names, but it would involve larger refactoring than what I'm ready to commit to in this PR.
> Correctly pick up test-jar dependency sources

- backend/src/main/scala/bloop/CompilerCache.scala
- backend/src/test/scala/bloop/CompilerCacheSpec.scala
Previously, Bloop's `CompilerCache` could return instances of
`JavaCompiler` relying on using the local JDK Java compiler API
("unforked" compilation) in cases where the javac options included
options expected to be passed to the runtime system (options starting
with `-J`, eg. `-J-Dfoo=bar`).
This happened, because the compiler instances are cached and the path to
the `javac` binary was used as cache key. This means that if 2 projects
A and B share the same path to the `javac` binary, but only project B
has javac options that should be passed to the runtime system, then
Bloop could use a local compiler to compile project B, because the cache
would have been populated with the local compiler used to compile
project A. See the test cases included in this commit.
This commit fixes this issue …
> Don't give a local compiler when disallowed

- .github/workflows/ci.yml
- build.sbt
- frontend/src/test/resources/compiler-plugin-allowlist/project/plugins.sbt
- frontend/src/test/resources/cross-test-build-scala-native-0.4/project/plugins.sbt
- frontend/src/test/resources/cross-test-build-scalajs-0.6/project/plugins.sbt
- frontend/src/test/resources/cross-test-build-scalajs-1.0/project/plugins.sbt
- frontend/src/test/resources/cross-test-build-scalajs-1.x/project/plugins.sbt
- frontend/src/test/resources/custom-test-framework/project/plugins.sbt
- frontend/src/test/resources/no-test-frameworks/project/plugins.sbt
- frontend/src/test/resources/scala-seed-project/project/plugins.sbt
- frontend/src/test/resources/simple-build/project/plugins.sbt
- project/build.sbt
- project/project/build.sbt
Fixes https://github.com/scalacenter/bloop/issues/1752.
> Stop shading stuff in sbt-bloop plugins

- launcher-core/src/main/scala/bloop/launcher/bsp/BspBridge.scala
- launcher-test/src/test/scala/bloop/launcher/BspBridgeSpec.scala
I'm noticed that this outputStream might produce an unhandled OOM error when it used from Metals (~80MB in memory).
Can be reproduced on long running session with a lot of diagnostics.
> fix: limit the amount of logs that launcher keeps in memory

- docs/build-tools/sbt.md
- project/build.sbt
This is to enable usage of Bloop/Metals in Enterprise environments where only the valid-POM format is accepted for JAR downloads (meaning most SBT plug-ins don't work -- currently making Scala unusable from VS Code at organizations with stricter security policies), for thousands of developers.
--
How this is tested locally:
`publishM2`, then in the target project that uses sbt-bloop, in its `project/metals.sbt` add, e.g.:
```
libraryDependencies += "ch.epfl.scala" % "sbt-bloop_2.12_1.0" % "1.5.2-13-15ded987-20220726-1436"
// only needed if published to local .m2 via publishM2
resolvers += Resolver.mavenLocal
```
More background here - https://github.com/esbeetee/sbt-vspp - more than happy to hop on a video call to discuss - as I appreciate that this is a non-issue for those that have a …
> Add sbt-vspp for publishing the BLOOP SBT plug-in in a Maven-consistent format

- project/Dependencies.scala
Thank you so much for your help with #1766 - the plug-in is now usable in enterprise!
However one of the dependencies did not pass the screening for CVEs - under bloop-backend there is sbt-librarymanagement 1.0.0 (see here for CVE info -- https://mvnrepository.com/artifact/org.scala-sbt/librarymanagement-core_2.12/1.0.0 ). For an upgrade path, I checked 1.0.4 which is the highest in 1.0.x, but its dependency on jsch still has a CVE, so the next one up without dependent CVEs would be a 1.1.x series, of which 1.1.5 is the highest. The latest available overall is 1.7.0 but I imagine depending on that could potentially cause some breakages if e.g. we're using Bloop from SBT 1.4.x and using a librarymanagement from 1.7.x.
I was also wondering if the dep should aso be set as `% "provided"` as …
> Upgrade sbt-librarymanagement to 1.1.5 due to CVEs in its 1.0.x tree.

- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/BloopInstallTask.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
Currently any Gradle Android projects only get a `java` section not a `scala` section in the Bloop json exports because there's no real link between the Android sourcesets and java/scala sourcesets so the `ScalaCompile` info is just floating about.
This PR assumes that if the project has `ScalaCompile` applied to it then that info should be exported.
So https://github.com/dsvdsv/scala-android-plugin is now supported.  It looks dead as it doesn't support later versions of Gradle or Android, but why not.
I've left the test for it commented out as the `GradleRunner` seems to apply plugins in a different order than real-life Gradle so the test fails on configuration.  Testing this on a local `build.gradle` file appears to work.
Hopefully this should solve …
> Support scala android plugin on Gradle

- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopNameHashing.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
Do it in the same way how it's implemeted in zinc - https://github.com/sbt/zinc/blob/189d33bcf6678fcc86e7e3e438c551d6cc51be8a/internal/zinc-core/src/main/scala/sbt/internal/inc/IncrementalCommon.scala#L396-L405
Technically it shouldn't be an issue, if user don't touch clasees then
there is no need to check `removedProducts`.
However, sometimes when I do a lot of switches between branches in
combination with Metals by some reason I'm getting an invalid state of project where some products were
removed and their sources aren't presented in changed files.
> fix: check if products were removed in inc compilation

- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
Previously, if you run `bloop.CompileSpec` locally you might notice that it rewrites `App.scala` in `bloop/frontend/src/test/resources/`.
> fix: avoid resource file updates in test

- bloopgun/src/main/graal/reflection.json
Based on https://github.com/dirs-dev/directories-jvm/blob/aa87fc1705fec69bc7f486dae6910306a50c221a/src/main/resources/META-INF/native-image/dev.dirs/reflect-config.json
Fixes https://github.com/scalacenter/bloop/issues/1718
> bugfix: Try and fix issue with Base64 reflection

- frontend/src/main/scala/bloop/data/Origin.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
- shared/src/main/scala/bloop/io/Paths.scala
- this makes it consistent between old and new JVMs, and makes a bunch of tests happy which among other things diff file timestamps
> Truncate file timestamp in `AttributedPath` to milliseconds

- build.sbt
Copied over from Metals. It ensures that users will not push badly formatted code.
Fixes https://github.com/scalacenter/bloop/issues/1779
> chore: Automatically add hook for validating formatting

- docs/build-tools/gradle.md
Just Gradle documentation updates...
Update supported Gradle version info
Add check for plugin already being applied so build files can have bloop plugin setup and that won't clash with the Metals import as it also applies the bloop plugin
> Update gradle docs

- config/src/main/scala-2.10/bloop/config/ConfigCodecs.scala
- config/src/main/scala/bloop/config/Config.scala
- docs/assets/bloop-schema.json
- frontend/src/it/scala/bloop/CommunityBuild.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/SourceGenerator.scala
- frontend/src/main/scala/bloop/engine/State.scala
- frontend/src/main/scala/bloop/engine/caches/SourceGeneratorCache.scala
- frontend/src/main/scala/bloop/engine/caches/StateCache.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/main/scala/bloop/io/SourceHasher.scala
- frontend/src/main/scala/bloop/io/SourceWatcher.scala
- frontend/src/test/resources/source-generator.py
- frontend/src/test/scala/bloop/DagSpec.scala
- frontend/src/test/scala/bloop/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/SourceGeneratorBspSpec.scala
- frontend/src/test/scala/bloop/SourceGeneratorSpec.scala
- frontend/src/test/scala/bloop/io/SourceHasherSpec.scala
- frontend/src/test/scala/bloop/io/SourcesGlobsSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
- integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
- integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- project/BuildPlugin.scala
This commit changes the Bloop project definition to add a new field,
`sourceGenerators`, which can be used to define source generators.
Source generators are parts of the build that are run when Bloop gathers
the sources of a project (either when queried via BSP or when
compiling).
Source generators are configured with globs matching input files, an
output directory, and a program to run. When the inputs or known outputs
of a source generator change, the source generator is automatically
re-run. When there are no changes, the result of a source generator is
cached.
The command to execute to run a source generator will be built from the
configured `argv`, followed by the output directory and the input files.
> Add support for source generators in Bloop

- frontend/src/main/scala/bloop/Cli.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
Bloop will only report `Boxed error`, see https://stackoverflow.com/questions/17265022/what-is-a-boxed-error-in-scala
I guess there might be a better place to put this. I wound up with some `ClassDefNotFoundError` and the likes when debugging
> show stack traces of `Error`s thrown in asynchronous code

- frontend/src/main/scala/bloop/engine/BuildLoader.scala
Previously, we would not download semanticdb even if it was backpublished. Now, we will try to download, but not print any warning if it's unsupported.
> bugfix: Try to download semanticdb even if it might not be supported

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspTestSpec.scala
- add `TestRun` and `TestRuns` structures to aggregate all produced `TestSuiteEvent.Results`.
- propagate all test results back up to service
- use test results to return `bsp.StatusCode.Error` on failed tests (Fixing #960)
- ensure that the compilation before test finished with `StatusCode.Ok`
> Improve `test` BSP service

- backend/src/main/scala/bloop/task/Task.scala
- backend/src/test/scala/bloop/task/TaskSpec.scala
Reported by @kpodsiad
Prevosuly, even if a task was completing in defined duration the fallaback effect were anyway exectured.
> fix: bloop.task.Task - avoid materializing fallback task in timeoutTo

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspTestSpec.scala
Hey again, this is a followup to #1769 . There, I was stuck for a long while on the new tests for the `test` BSP service.
It failed like this:
```
[warn] Skipping test for a because compiler result is empty
``` 
@tgodzik made the tests green, and merged it. thanks again.
So then, imagine my surprise when I saw the same error with bloop 1.5.4 when trying to run tests through BSP. 
So I dug a bit further and discovered that when running tests bloop will (naturally) first compile, and then run tests. The problem is that the `State` produced by the compilation is not propagated to the test code, and the previous state is used instead. So if the code hadn't been compiled before for instance, test will see no class files.
For this PR I did a slight revert to the test code in the first commit …
> Fix test BSP service by not using stale state

- .github/workflows/ci.yml
- backend/src/main/scala/bloop/reporter/Reporter.scala
- bin/sbt-ci-release.bat
- frontend/src/main/scala/bloop/logging/BspServerLogger.scala
- frontend/src/test/resources/compiler-plugin-allowlist/project/build.properties
- frontend/src/test/resources/compiler-plugin-allowlist/project/project/build.properties
- frontend/src/test/resources/cross-test-build-scala-native-0.4/project/build.properties
- frontend/src/test/resources/cross-test-build-scalajs-0.6/project/build.properties
- frontend/src/test/resources/cross-test-build-scalajs-0.6/project/project/build.properties
- frontend/src/test/resources/cross-test-build-scalajs-1.0/project/build.properties
- frontend/src/test/resources/cross-test-build-scalajs-1.0/project/project/build.properties
- frontend/src/test/resources/cross-test-build-scalajs-1.x/project/build.properties
- frontend/src/test/resources/cross-test-build-scalajs-1.x/project/project/build.properties
- frontend/src/test/resources/custom-test-framework/project/build.properties
- frontend/src/test/resources/custom-test-framework/project/project/build.properties
- frontend/src/test/resources/no-test-frameworks/project/build.properties
- frontend/src/test/resources/no-test-frameworks/project/project/build.properties
- frontend/src/test/resources/scala-seed-project/project/build.properties
- frontend/src/test/resources/simple-build/project/build.properties
- project/Dependencies.scala
- project/build.properties
- shared/src/main/scala/bloop/reporter/Problem.scala
Needs https://github.com/lampepfl/dotty/pull/15565 to actually do anything. Although it's not working currently and I have no idea why. Just putting this here to test and tie all together.
Shoot, I just realized I opened this up on a branch and not in my fork 😬 sorry about that.
> feat: capture diagnostic code from Problem

- project/Dependencies.scala
It brings:
- [Better log points](https://github.com/scalacenter/scala-debug-adapter/releases/tag/v3.0.3)
- More logs to understand the flakiness of some unit tests in Metals
- A few bug fixes
> Bump scala-debug-adapter to 3.0.4

- frontend/src/main/scala/bloop/Cli.scala
It seems that https://github.com/scalacenter/bloop/issues/1847 is hanging on trying to lock the out object and since the println here is not really useful I think it's fine to remove and check if that helps.
The stack trace mostly shows a lot of thread stuck on that println actually.
> bugfix: Remove potentially problematic println

- .scala-steward.conf
- build.sbt
- project/Dependencies.scala
javaDebug is brought in by scala-debug-adapter, so no need to define it here.
Nailgun version should fixed, since it's the one Bloop works with (dropping the fork would be awesome.)
Release-early should be replaced by sbt-ci-release so don't want to change the version and risk regression. Especially since it's not actively maintained.
> chore: Remove java-debug and ignore updates for nailgun, release-early

- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
Seems that the socket might already be closed at that point and an exception is caused causing frequent flaky tests.
> bugfix: Don't fail test if socket was already closed

- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspConnectionSpec.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/dap/DebugBspBaseSuite.scala
It seems despite the randomness it can fail quite often, so instead we should retry.
Ideally we would specify 0 and use the system suggested port, but there is no way sensible way to propagate that to the tests.
> bugfix: Retry test if socket was taken 

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/test/scala/bloop/GenericTestSpec.scala
- frontend/src/test/scala/bloop/TestSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
Previously, Bloop would inspect all projects to try and find test classes. This is not necessary, because only classes that live in test projects should be run.
This commit filters out test projects from the analysis, so that it runs faster.
> Discover test classes only in test projects

- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
Previously, we would always timeout after 35 seconds, because that was the timeout set in startDebugServer. Now, we forward the task up to the test and wait the amount specified in each test.
> refactor: Use the actual timeouts defined for tests in DebugServerSpec

- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopStamps.scala
Previously we would use last modfied stamps for classfiles (and other products) and hashes for jars. Now, we use hashes for both, but only if the modified time changed.
Should help with https://github.com/scalameta/metals/issues/4623
> improvement: Change the stamps to timewrapped ones

- project/BuildPlugin.scala
This isn't used at all and in the future if we really want to use this
we can revisit it and pull it back out. For now, all the cleanup we can
get makes thing easier to understand
> refactor: remove unused cloneKafka stuff.

- .github/workflows/ci.yml
It seems that if we build with the newer version and try to run on ubuntu 20 it will fail with missing `GLIBC_2.34'
I updated my local ubuntu version and it seems to work, but it might be problematic for some users with older version.
> chore: downgrade release ubuntu version

- .scala-steward.conf
- project/build.sbt
Locally I'm having issues ever since I merged in #1940. This
reverts that update and locks the version for now. After ripping
stuff out and cleaning up I'll dig further into this.
> fix: revert sbt-jmh update

- .jvmopts
This was added so Metals wouldn't add a metals.sbt. Now that we are no longer
dogfooding we don't need this set and instead _want_ metals to create this.
> fix: update jvmOpts to not mention bloop-sbt-already-installed

- build.sbt
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileResult.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- project/Dependencies.scala
So this isn't used very much at all, only for the Show typeclass, and
that's what was breaking here due to the introduction of `Cord`. I think
my little hack is fine, it' just creates the cord out of the result of
the `shows` method. However, I'm not 100% sure, so let's run the tests
and see. I also removed scalaz concurrent because from what I can tell,
it wasn't being used and with the new version, it's not there anymore.
Supersedes #1938
> chore(deps): bump scalaz to 7.3.7

- docs/build-tools/sbt.md
Just quick PR to fix one typo in `sbt.md`.
> Correct typo in sbt.md

- .github/workflows/ci.yml
- bin/set-up-keys.sh
- build.sbt
- project/BuildPlugin.scala
- project/build.properties
- project/build.sbt
This pr changes the way we do releases and migrates us away from the
forked sbt-release-early that's no longer maintained and is also
bringing in some old versions of scala-xml which will be problematic
when we try to update our sbt stuff.
Plus this simplifies the release a little bit. The one difference is
that we'll now be publishing actual `-SNAPSHOT` into sonatype snapshots.
Refs: https://github.com/scalacenter/bloop/issues/1680
> refactor(ci): migrate to sbt-ci-release

- .github/workflows/ci.yml
- bin/sbt-ci-release.bat
I actually have no idea if this is the cause or not, but the windows native image is [failing](https://github.com/scalacenter/bloop/actions/runs/3786069067/jobs/6436982906) with what you see below:
```
[error] com.oracle.svm.core.util.UserError$UserException: Main entry point class '@C:\Users\RUNNER~1\AppData\Local\Temp\native-image-classpath14131537784930832467.txt' not found.
[error] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:313)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
[error] 	at …
```
> fix(ci): ensure release sbt version is the same as the build

- .github/workflows/ci.yml
This will get rid of some of the warnings we're seeing in CI
> chore(ci): try to bump node to lts

- build.sbt
This is failing in the dependency job and testing locally I
can't actually get these to resolve anymore either. Not
sure if Twitter is just nuking their maven instance or what
but I don't even think these are used, so we just get rid of
them.
> chore: remove twitterIntegrationProjects

- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaJsToolchain.scala
Trying to figure out why the ScalaJS tests are so flaky. When doing that I realized we had an invalid version in here that wasn't able to resolve since 1.4.0 doesn't exist. This may help if we ensure that it can actually be resolved.
> fix: ensure valid scalajs-logging version in ScalaJsToolchain

- backend/src/main/scala/bloop/task/Task.scala
- backend/src/main/scala/bloop/util/Java8Compat.scala
- backend/src/test/scala/bloop/task/TaskSpec.scala
- docs-gen/src/main/scala/bloop/docs/ReleasesModifier.scala
- docs-gen/src/main/scala/bloop/docs/Sonatype.scala
- frontend/src/main/scala/bloop/bsp/BloopLanguageClient.scala
- frontend/src/main/scala/bloop/bsp/BloopRpcServices.scala
- frontend/src/main/scala/bloop/engine/ExecutionContext.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/util/monix/BloopBufferTimedObservable.scala
- frontend/src/test/scala/bloop/bsp/BspClientTest.scala
- frontend/src/test/scala/bloop/dap/DebugAdapterProxy.scala
- launcher-test/src/test/scala/bloop/launcher/LauncherBaseSuite.scala
These are mainly low-hanging fruit related to deprecations.
> refactor: take care of a bunch of warnings

- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopHighLevelCompiler.scala
Previously, when the compiler threw a StackOverflowException Bloop would hang and nver return a results. Now, it logs the proper error and translates the exception.
Related to https://github.com/VirtusLab/scala-cli/issues/1781
> bugfix: Catch and log StackOverflowError

- frontend/src/main/scala/bloop/cli/CommonOptions.scala
- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
fixes https://github.com/scalameta/metals/issues/5025
- change mutable PrettyProperties to wrapper over immutable Map
- adjust forker's implementations logic so they are not even aware of env parameters. They're handled one step before
I was thinking about some tests but immutable data structure should be just enough to prevent such cases in the future
> fix: do not expose mutable env properties in State

- .github/workflows/ci.yml
For some mysterious reason, traversing the `src.zip` of JDK Temurin 11.0.18 installed by `actions/setup-java` is very very slow. It takes up to 40 second, the first time, and then it takes about 500 ms. That's why the `DebugProtocolSpec` times out.
But if I install the exact same JDK with `coursier/setup-action`, the issue disappears. Similarly, if I manually download and extract the JDK, it fixes the issue. So it seems there is something wrong with `actions/setup-java`, about how it installs this JDK, but I don't know exactly what.
Switching to `coursier/setup-action` solves the issue.
> Fix timeout in DebugProtocolTests

- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
It seems that the genericClassesDir is not being used at all by the compiler, so cleaning orphan directories in it was not achieving anything.
We might need to figure out how to use `genericClassesDir` and whether it needs to be used at all, but for now this fixes the issue of large .bloop directory.
> bugfix: Properly clean up orphan directories for internal classes

- backend/src/main/scala/sbt/internal/inc/bloop/ZincInternals.scala
Currently Bloop reports java errors as always being at the start of the line.  Now it includes the column as well.
I think this worked at one point but maybe got lost in the move away from the Zinc fork?
I don't know why Zinc reports the column of the error in the `offset` field instead of the `pointer` field as the code assumed - maybe it's an issue with Zinc?  Anyway - I don't see a problem in checking both fields.
I've tested this locally with Java code and Metals now underlines the correct error range.
> Report java error column

- backend/src/main/scala/sbt/internal/inc/bloop/BloopZincCompiler.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopIncremental.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopStamps.scala
Previously, when hashing would fail the whole compilation would also fail and while this seems incredibly rare let's try to guard ourselves here.
Connected to https://github.com/scalacenter/bloop/issues/2053
It's the safest option, we could also try another stamp in this case, but I think there is something wrong with that jar
> improvement: Don't fail on hashing, but use a random hash

- docs/contributing-guide.md
Remove a trailing full stop on a command to avoid copy/paste errors. 
Add prerequisites to documentation updates.
> Update the developer documentation.

- build.sbt
- frontend/src/test/scala/bloop/BuildLoaderSpec.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
- project/BuildPlugin.scala
- project/Dependencies.scala
Previously, we would use a commited semanticdb jar for tests in frontend, however this caused two issues:
- semanticdb would be always out of date
- scala version updates would require also bumping semanticdb manually and fetching the jar
Now, we use the latest semanticdb plugin always, which should work properly.
> improvement: Automatically include semanticdbjar for tests

- launcher-test/src/test/scala/bloop/launcher/LauncherSpec.scala
The tests work on my machine despite not having python on path, so most likely this is no longer valid as the launcher uses snailgun.
> chore: Remove unused python check

- notes/v1.5.7.md
I figured we haven't had a release for a while and a lot of the improvements of Scala debug adapter are not being used.
> chore: Add release notes for Bloop 1.5.7 release

- frontend/src/main/scala/bloop/engine/caches/SemanticDBCache.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
Previously, we wouldn't produce semanticdb files for older version of Scala since we wouldn't find the correct artifact if we stopped publishing for a particular version.
Now, we try and find the latest version that still supported that Scala version.
This is similar to the change we did in Metals in regards to the presentation compiler interface, where we would fetch old mtags for unsupported scala version and this way always support a particular version.
Will do a similar thing for our Metals sbt plugin if it makes sense.
> improvement: Try and find latest supported semanticdb version

- frontend/src/test/scala/bloop/SourceGeneratorSpec.scala
Previously, if python was not available on PATH we would fail the tests the source generator tests, since Python is used to simulate source generators. Now, we check both python and python 3 executables first, if none of them exists then we ignore the tests. This will pop up on CI if source generators are broken.
> chore: Make source generator tests more resilient

- docs/build-tools/overview.md
Fury was completely redone and no longer works with Bloop. The link for Metals was crazy old.
> docs: update overview.md with corrections

- notes/v1.5.8.md
Quick follow up to have the last JDK 8 compatible version.
> chore: Release notes for Bloop 1.5.8

- frontend/src/main/scala/bloop/logging/BspServerLogger.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspConnectionSpec.scala
Previously, we would only print the logs when using Bloop from CLI. We still will need to add `-verbose` to compile params to get this behaviour
> improvement: Send debug logs to BSP client

- bridges/scalajs-1/src/test/scala/bloop/scalajs/ScalaJsToolchainSpec.scala
This is consistently failing with messages like:
```
[error] Test bloop.scalajs.ScalaJsToolchainSpec.canLinkScalaJsProject failed: java.util.concurrent.TimeoutException: Futures timed out after [45 seconds], took 46.973 sec
```
My naive hope is that just bumping this might make this test less flaky.
> refactor(test): bump maxDuration in js tests

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/io/ParallelOps.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
This might cause the compiler to never work again until restart. It seems that the reason might be that one of the files is locked, but this is highly difficult to reproduce.
Connected to https://github.com/scalacenter/bloop/issues/1989
> improvement: Don't fail during copying

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
As a power user I often use `bloopInstall` from already opened sbt session as it is much faster than `Metals: Import Build` (warm JVM with sbt, etc.). However, there is one main advantage that `Metals: Import Build` has - it runs sbt with `-Dbloop.export-jar-classifiers=sources`.
Even though it is possible to configure bloop's sbt plugin to download sources, by [tweaking build.sbt](https://scalacenter.github.io/bloop/docs/build-tools/sbt#download-dependencies-sources) I don't consider it as a viable option because:
- not everybody uses metals, hence bloop which is default build server
- not everybody uses bloop as their default build server
Not having sources for dependencies results in really bad UX in Metals, as they can't e.g. go to the definition of given class. They instead fail …
> feat: fallback to `source` and `javadoc` classifiers when exporting projects from sbt

- frontend/src/main/scala/bloop/logging/BspServerLogger.scala
I was experimenting with @lrytz with code actions for Scala 2 and manged it working this way. There will need to be some more changes, but this ones we can already merge.
> bugfix: Handle compiler position that is not a range

- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
Currently Bloop uses `-targetroot:javac-classes-directory` to specify the `targetroot` dir for the `scip-java` plugin, which means  Bloop delegates to the plugin to work out the correct dir to place the semanticdb files in.
`scip-java` has to use the internal JDK API to perform the substitution which requires `--add-exports` and I see no way round that  - hence in this PR Bloop specifies the exact classes directory
> specify scip javac plugin targetroot exactly

- notes/v1.5.10.md
I wanted to include the recent changes around the bridges before the next Metals release.
> docs: Add release notes for 1.5.10

- bridges/scalajs-0.6/src/test/scala/bloop/scalajs/ScalaJsToolchainSpec.scala
We did it previously for 1.x since the bridge compilation already might take up most of that time.
> chore: Increase test maximum duration for ScalaJsToolchainSpec for 0.6

- build.sbt
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
Previously, we were always expecting scala JS plugin to find the correct version of Scala JS, however I think for Scala 3 it's not a plugin, which is causing the version field to be empty. Now, we look for the scala-js library instead and default to the latest known scala js version.
@sjrd would this be a correct assumption?
> bugfix: Never set empty Scala JS version from sbt

- bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala
- launcher-test/src/test/scala/bloop/launcher/GlobalSettingsSpec.scala
On Windows with scala-cli I got something like:
```
java.io.IOException: Cannot run program "C:\Program Files\Microsoft\jdk-17.0.7.7-hotspot\bin\java" (in directory "d:\MojeProgramy\bloop-core"): CreateProcess error=2, Nie mo?na odnale?? okre?lonego pliku
```
> Add support for absolute paths in Bloopgun error handling

- backend/src/main/scala/bloop/tracing/BraveTracer.scala
- backend/src/main/scala/bloop/tracing/TraceProperties.scala
- docs/performance-guide.md
- frontend/src/main/scala/bloop/data/TraceSettings.scala
- frontend/src/test/scala/bloop/BuildLoaderSpec.scala
- frontend/src/test/scala/bloop/TracerSpec.scala
Previously, tracing was enabled by default and user could get stack traces logged by the zipkin trace. Now, we require setting `bloop.tracing.enabled` property.
Tracing is not used heavily currently, so this should not be an issue.
Fixes https://github.com/scalacenter/bloop/issues/2108
> improvement: Disable tracing by default

- frontend/src/main/scala/bloop/testing/TestInternals.scala
- frontend/src/test/scala/bloop/TestFilterSpec.scala
Often, when copying the failed test path from Jenkins CI or Gradle Enterprise webpage, the path copied might contain leading or trailing space(s). Pasting the failed test path into the `-o` switch requires carefully removing the space from both ends.  
Example:
` bloop test project-it -o ' a.b.c.Test' --config-dir=../.bloop`
This command would not run the test `a.b.c.Test`
This PR fixes the annoyance by trimming the path before matching the pattern.
> improvement: trim spaces when filtering the only tests that should be run

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/util/JavaRuntime.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/JavaVersionSpec.scala
Previously, if we compiled with a Bloop running an newer JDK we would not see any errors even when using methods belonging to a newer JDK. Now, we automatically add -release flag, which makes sure that we will fail any compilation that should not pass with an older JDK (if specified in configuration)
This is needed for incorporating the forks.
> feature: Automatically add -release option when needed

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
improvement over https://github.com/scalacenter/bloop/pull/2118, `javadoc` is not necessary and causes too much stuff to be downloaded
> chore: don't use javadoc classifier as default for bloopInstall

- docs/build-tools/sbt.md
After #1973, you should use `Value(None)` instead of `None` but the docs haven't been updated.
> Update sbt `bloopGenerate` docs to use `Value(None)`

- integrations/sbt-bloop/src/sbt-test/sbt-bloop/cross-compile-test-configurations/test
Looks like a bug that was present long time ago in sbt. I think it might be related to https://github.com/sbt/sbt/issues/5501
Running update manually fixes things.
> bugfix: Fix sbt integration tests

- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
Previously, we would just print the error message, but since this error is usually complex, we always need a full stack trace. Now, we just print the full stack trace. This means metals will also get the full exception in those cases without the need to configure anything.
> chore: Add full error stack trace

- frontend/src/main/scala/bloop/dap/BloopDebuggee.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
Previously, we would use the default config, which would not always be correct. Now, we use runtime config with a fallback to normal platform config.
> bugfix: Make sure proper runtime classpath is used when debugging

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/runtime-dependency/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/runtime-dependency/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/runtime-dependency/test
Previously, we would not save runtime jars which could lead to users not being able to run their programs.
Now, we export runtime classpath properly from sbt.
Related to https://github.com/scalacenter/bloop/issues/1606 though I want to check out if it will also work via DAP
> bugfix: Export runtime jars correctly from sbt

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/non-compiling/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/non-compiling/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/non-compiling/src/main/scala/Obj.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/non-compiling/test
Previously, I used fullclasspath for getting the runtime classpath, but I forgot this causes sbt to always compile on bloopInstaall.
Now, I changed to use the same mechanism we use for compile classpath and added a test to make sure this doesn't show up again.
> bugfix: Don't use fullclasspath in sbt plugin

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
Previously, we would get soemthing like:
```
Cause: Incomplete(node=Some(Task(_)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(Task(_)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(Task(_)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(Task((taskDefinitionKey: ScopedKey(Scope(Select(ProjectRef(file:/tmp/sbt_14ffb38d/no-compile-incremental/,no-compile-incremental)), Select(ConfigKey(runtime)), Zero, Zero),fullClasspath)))), tpe=Error, msg=None, causes=List(Incomplete(node=Some(Task(_)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(Task((taskDefinitionKey: ScopedKey(Scope(Select(ProjectRef(file:/tmp/sbt_14ffb38d/no-compile-incremental/,no-compile-incremental)), Select(ConfigKey(runtime)), Zero, Zero),dependencyClasspath)))), tpe=Error, msg=None, …
```
> chore: Print better errors when bloopInstall failed

- bridges/scalajs-1/src/main/scala/bloop/scalajs/JsBridge.scala
Previously, this would be set to error, which would mean Metals would show it to the users more prominently. Now, we change it to warn, which means it's still present, but since this might be actually be related to non compiled code, it's prominence is reduced,
Fixes https://github.com/scalacenter/bloop/issues/2211
> improvement: Change information about test framework to warn

- backend/src/main/scala/bloop/io/ParallelOps.scala
- backend/src/main/scala/bloop/logging/BloopLogger.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/testing/TestInternals.scala
- shared/src/main/scala/bloop/logging/Logger.scala
It seems we don't get that properly forwarded to Bloop otherwise.
> bugfix: Print copying error together with stacktrace

- frontend/src/main/resources/logback.xml
- frontend/src/main/scala/bloop/Server.scala
Some overall minor changes. Looks that next we will have to port the socket changes, which require JVM 17. We should be fine to do it, with maybe bloop-rifle needing a release output flag.
> refactor: Further backports from bloop-core

- notes/v1.5.14.md
I want to release this one since we have a warning showing up that might be annoying for some people. The warning is about using too old JVM while in fact it's the same JVM version as required.
> chore: Add release notes for Bloop 1.5.14

- project/BuildPlugin.scala
It seems based on the last errors that the actual path is just the directory, we still need to resolve the actual artifact, which has the same name as the artifact.
> bugfix: Fix the location of downloaded artifacts

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/CompilerCache.scala
- backend/src/main/scala/bloop/util/JavaRuntime.scala
- backend/src/main/scala/sbt/internal/inc/BloopZincLibraryManagement.scala
- backend/src/test/scala/bloop/CompilerCacheSpec.scala
- frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
- frontend/src/test/scala/bloop/BuildLoaderSpec.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
- frontend/src/test/scala/bloop/testing/ProjectBaseSuite.scala
- shared/src/main/scala/bloop/io/AbsolutePath.scala
- shared/src/main/scala/bloop/logging/Logger.scala
Fix #2268 
We should cache the `ScalaInstance` to reuse classloaders as much as possible but we should take into account the `ClasspathOptions` of a project when we create the `ScalaCompiler`.
Tested on Dotty: compilation :heavy_check_mark: auto-completion :heavy_check_mark:
> Fix classpath options

- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/test/scala/bloop/DeduplicationSpec.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspSbtClientSpec.scala
This might be a bit opinionated and I'm not 100% sure on the reason this was done in the first place, but this changes the current behavior around reporting start and end compilations for no-ops. This still retains the compile report if it was a no-op and also still checks the diagnostics and reports them, but skips the task start/end.
Originally this was added in a commit without any context... but there was a comment that said:
> // When no-op, we keep reporting the start and the end of compilation for consistency
However, I'm not really sure that consistency matters here. In reality this ends up creating a bunch of noise on the client side, especially when these tasks turn into LSP progress notifications that aren't useful for the user to see. You can see more context about this change …
> refactor: don't send task start/end for no-op compilations

- backend/src/main/scala/bloop/ClientClassesObserver.scala
- backend/src/main/scala/bloop/CompileBackgroundTasks.scala
- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/dap/BloopDebugToolsResolver.scala
- frontend/src/main/scala/bloop/dap/BloopDebuggee.scala
- frontend/src/main/scala/bloop/dap/DapCancellableFuture.scala
- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/test/scala/bloop/dap/DebugAdapterConnection.scala
- frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
- frontend/src/test/scala/bloop/dap/DebugTestEndpoints.scala
- project/Dependencies.scala
The new 4.x version of the scala-debug-adpater brings:
- pretty stack traces
- runtime evaluator (scalameta-based evaluation on runtime values)
- hot code replace
See the [release notes](https://github.com/scalacenter/scala-debug-adapter/releases/tag/v4.0.0) for more information.
For the hot code replace we need Bloop to call the `onClassUpdate` callback each time some classes change or new classes are created. This PR implements it by introducing the `ClientClassesObserver`. It compares the new `CompileAnalysis` with the previous one to know which classes need to be reloaded and then it calls the `onClassUpdate` callback.
> Update scala-debug-adpater to 4.x and add support for hot code replace

- backend/src/main/scala/bloop/Compiler.scala
Changing how java version is parsed to get rid of an unwanted warning:
` WARN  Bloop is running with 1.8.0_382 but your code requires 1.8.0_382 to compile, this might cause some compilation issues when using JDK API unsupported by the Bloop's current JVM version`
> fix: correctly parse java version

- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/main/scala/bloop/bsp/ProjectUris.scala
- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileBundle.scala
- frontend/src/main/scala/bloop/engine/tasks/toolchains/ScalaNativeToolchain.scala
fixes https://github.com/scalameta/metals/issues/5745
> fix: allow for spaces in project name

- README.md
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/bsp/TestConstants.scala
This fixes build-server-protocol/build-server-protocol#205 when importing from bloop by reporting the `target/` folder of each project as an outputPath.
In my case I am using it with bloop-maven-plugin.
> Implement BSP buildTarget/outputPaths

- backend/src/main/scala/bloop/ScalaInstance.scala
- backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- project/Dependencies.scala
This change allows build tools to supply bridge JARs themselves, so that the Bloop server doesn't have to fetch them itself later on. This allows to fetch those JARs from non-standard repositories, that the Bloop server doesn't know about.
Needs https://github.com/scalacenter/bloop-config/pull/20
> Take into account build tool-supplied bridge JARs

- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
Previously in some cases when deduplicating bloop would report the `previousSuccessfulProblems` in which case bsp clients like metals could have their diagnostics overwritten with outdated ones (so here we use `previousProblems` instead).
> Fix reporting after deduplicating compilations

- backend/src/main/scala/bloop/Compiler.scala
The flags should not be used together and might cause unexpected issues
> bugfix: Don't add -release flag if target is already present

- backend/src/main/scala/bloop/reporter/Reporter.scala
- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
> fix: Only consider scala source files when lifting fatal errors

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/io/ParallelOps.scala
- backend/src/main/scala/bloop/util/BestEffortUtils.scala
- frontend/src/it/scala/bloop/CommunityBuild.scala
- frontend/src/main/scala/bloop/bsp/BloopBspDefinitions.scala
- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/data/WorkspaceSettings.scala
- frontend/src/main/scala/bloop/engine/BuildLoader.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileDependenciesData.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileResult.scala
- frontend/src/test/scala/bloop/BuildLoaderSpec.scala
- frontend/src/test/scala/bloop/DagSpec.scala
- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspIntellijClientSpec.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
- frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
- frontend/src/test/scala/bloop/testing/BloopHelpers.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
* dotty: https://github.com/lampepfl/dotty/pull/17582
* metals: https://github.com/scalameta/metals/pull/5219
This commit allows bloop to support the hopefully-upcoming Scala 3 best effort compilation for Metals, it being enabled with the other Metals options.
Best Effort is meant to be a set of Scala 3 compiler options that allow the errored, but typed programs, to be able to be serialized into a TASTy aligned format (Best Effort TASTy), and later to reuse those typed program trees in both the dependent projects, and in the presentation compiler.
~~Those best effort tasty files are always serialized to a seperate directory, which in this PR is managed by bloop.~~ It is worth noting that the best effort compilation may fail, similarly to the regular compilation.
~~The best effort …
> Support Scala 3's Best Effort compilation

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/test/scala/bloop/bsp/BspTestSpec.scala
Adds support for TestParamsData kinds as defined in the scala extension of BSP. This allows clients to specify which test classes / tests to run
Relevant bsp documentation:  https://build-server-protocol.github.io/docs/extensions/scala#testparamsdata-kinds
Fixed a bug? in the TestTask.discoverTestSuites where it did not filter on which test should should
run when explicitly passing list of test classes (fully qualified)
Included tests for running specific test suites, and tests within suites
> Add support for BSP TestParamsData kinds

- frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
Previously, if `--best-effort` option was set, every project would be compiled in the best effort mode, including those using scala 2. This first commit fixes the `CodeLensLspSuite` test. `DebugProtocolSuite` might have been broken by 7154823d8acdd3ceb05bd5000d62d869515851a7 (before that merge it works), <s>but I am still investigating that (or maybe the broken metals test should change?) </s>
> Fix recent regressions not allowing Metals to pass its tests 

- cli/src/main/scala/bloop/cli/Directories.scala
This way at least Scala CLI will be able to restart the old server without an issue and not start a totally new one. For Bloop core unfortunately people might need to stop it manually
> refactor: Keep daemon socket used by Scala Cli

- build.sbt
I noticed that otherwise this gets published as ch.epfl.scala:cli_2.13:2.0.0 which is maybe too short a name and doesn't say what it is best.
> chore: Rename cli to bloop-cli

- etc/bloop-coursier.json
It's used as a template during the releases
> bugfix: Update bloop-coursier.json

- build.sbt
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/Interpreter.scala
- frontend/src/main/scala/bloop/engine/SourceGenerator.scala
- frontend/src/main/scala/bloop/engine/caches/SourceGeneratorCache.scala
- frontend/src/test/resources/source-generator.py
- frontend/src/test/scala/bloop/FileWatchingSpec.scala
- frontend/src/test/scala/bloop/SourceGeneratorBspSpec.scala
- frontend/src/test/scala/bloop/SourceGeneratorSpec.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
This allows us to rerun source generators if the scripts change.
Fixes https://github.com/scalacenter/bloop/issues/2386
> improvement: Add option to watch unmanaged inputs

- bloop-rifle/src/main/scala/bloop/rifle/BloopServer.scala
This was raised on discord and it seems when we fail to parse the output of `about` everything will break.
This is because there is a server running and we will not restart it and the output of about command will again we wrong when we reask.
Now, we should try to exit it first in that case since msot likely the server is broken.
> bugfix: Try to stop bloop if unable to run about

- backend/src/main/java/bloop/rtexport/Copy.java
- backend/src/main/java/bloop/rtexport/Export0.java
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/rtexport/Export.scala
- backend/src/main/scala/bloop/rtexport/RtJarCache.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopHighLevelCompiler.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
When `-release 8` is added we need an existing rt.jar to use for the code to compile, this is already done by sbt and mill.
Copied from https://github.com/com-lihaoyi/mill/tree/6cf6ce1129a74f50af5048cf75e1dee747d6b92e/main/api/src/mill/java9rtexport
> bugfix: Create rt.jar when compiling for JDK 8

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/reporter/ObservedReporter.scala
- backend/src/main/scala/bloop/reporter/Reporter.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/main/scala/bloop/reporter/LogReporter.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/bsp/BspSbtClientSpec.scala
resolves: https://github.com/scalameta/metals/issues/6656
> fix: report compile progress when no-op after unsuccessful compilation

- frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
We need to report all problems if a BSP client just connected to the server and never compiled. `reportAllPreviousProblems` will be set to true in that case.
However, if previously we had an error, which was reverted and got back to the state before the error, we will get a successfull noop compilation, which will not produce any problems.
In this case we don't want to republish everything again, since diagnostics will contain the error which was reverted.
Connected to https://github.com/VirtusLab/scala-cli/issues/2226 where CLI always connected anew.
> bugfix: Don't republish old errors on successful compilation

- notes/v2.0.2.md
I broke coursier.json since I needed to update it manually. I can't update it since sha will be different, so instead I need to do another release.
> docs: Add Bloop 2.0.2 release notes

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/bsp-enabled/bar/src/test/scala/Bar.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/bsp-enabled/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/bsp-enabled/foo/src/main/scala/Foo.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/bsp-enabled/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/bsp-enabled/test
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/non-compiling/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/runtime-dependency/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/scala-js/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/scala-js/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/working-dir/build.sbt
- project/Dependencies.scala
I noticed we have to work around it in a number of places and might be useful in the scala3 repo for example.
We didn't do it previously to keep the sbt version as low as possible, but it should be fine for users of older sbt to use older plugins (will be done automatically in Metals)
> improvement: Respect bspEnabled when generating bloop config files

- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/test/scala/bloop/JavaVersionSpec.scala
Previously, we would automatically generate our own rt.jar from the Bloop's JDK, however this would put all the current JDK classes into that jar, which means some things might compile while they should not. This limitation is present both in Mill and sbt. We would only fail on added methods.
Now, we try to locate rt.jar if javaHome is set, so we can use it explicitely.
> bugfix: Use proper rt.jar if it exists

- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/test/scala/bloop/JavaVersionSpec.scala
Otherwise compilation will fail.
Showed up in https://github.com/scalameta/metals/issues/6829 unfortunately after I did the release 
Fixes  https://github.com/scalameta/metals/issues/6829
> bugfix: Don't add -release flag for Scala 2.11

- build.sbt
- project/Dependencies.scala
Fixes https://github.com/scalacenter/bloop/issues/2479
Fixes https://github.com/scalacenter/bloop/issues/2478
> chore: Replace original jsonrpc4s

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/util/BestEffortUtils.scala
- backend/src/main/scala/sbt/internal/inc/bloop/BloopZincCompiler.scala
- docs/contributing-guide.md
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
Fix to https://github.com/scalameta/metals/issues/6628
Usually it was fine to always put betasty files at the end of the classpath, but in the reproduction for some reason despite the code being correct, those files were still being used, which resulted in an incoherent state in bloop (we obtained only betasty files on what was being considered non-best effort compilation). This lead to trying to apply incremental compilation there, producing singular betasty files, and losing information about symbols from other files, producing errors.
The fix is very simple, but so far I have been unable to properly add any tests for it, as the `backgroundTasks` do not seem to be run in the tests suites.
> Remove betasty directory on successful compilation backgroundTasks

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/wartremover/bar/src/test/scala/Bar.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/wartremover/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/wartremover/foo/src/main/scala/Foo.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/wartremover/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/wartremover/test
Otherwise this doesn't work, looks like Bloop and sbt's working dir have a mismatch?
Fixes https://github.com/scalacenter/bloop/issues/1421 finally
> bugfix: Make absolute path from relative plugin paths

- backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala
- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-bridge/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-bridge/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-bridge/test
This is needed to fully compile Dotty right now.
> improvement: Use sbt bridge defined by the user

- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopIncremental.scala
- backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopNameHashing.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
Previously, we would ask zinc to compile even a file that was removed and I think this was causing https://github.com/scalameta/metals/issues/6478
Now, we invalidated all changed sources, but only compile new ones.
> bugfix: Compile only existing classes

- .github/workflows/ci.yml
I missed it since it was capitalized differently and uploading artifacts failed
> chore: Fix variable refering to older macOS

- frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- frontend/src/test/scala/bloop/testing/BaseSuite.scala
This seems to work fine locally and on graalvm. I have no idea yet why the test fails, but I want to debug it separately
> chore: Ignore test on linux for the time being

- frontend/src/main/scala/bloop/data/ClientInfo.scala
- frontend/src/main/scala/bloop/engine/State.scala
- frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
- frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
- shared/src/main/scala/bloop/logging/FlushingOutputStream.scala
- shared/src/main/scala/bloop/logging/Logger.scala
Somehow this was an issue on linux and JDK 17, but not sure why not others.
I also fixed getting stdout to get it redirected to the logger, my previous change did not fully fix it.
>  bugfix: Use last modified time instead of creation time for detecting orphaned directories

- backend/src/main/scala/bloop/Compiler.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
Related to https://github.com/scala/scala3/issues/22026
> bugfix: Catch fatal errors when persisting zinc analysis

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/util/BestEffortUtils.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/test/scala/bloop/bsp/BspMetalsClientSpec.scala
Also fixes an issue with best effort compilation not being properly cached, if recompiled from successful compilations.
@tgodzik About the main issue fixed here, I misdiagnosed that issue yesterday (I mentioned a race condition, not what was happening - the issue is consistent, the way I tried to reproduce it with adding and removing a class in another class was not), but thankfully, it's a simple fix.
About the second thing raised [here](https://github.com/scalameta/metals/issues/6628#issuecomment-2497836757), that sounds like an actual race condition I'm not sure is exclusive to best effort (like you mentioned) and one I'm not sure I would be able to fix quickly, but it seems to me like a later recompilation would fix that.
> Fix issue with BE compilations incorrectly reusing successful artifacts

- integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/use-pipelining/bar/src/test/scala/Bar.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/use-pipelining/build.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/use-pipelining/foo/src/main/scala/Foo.scala
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/use-pipelining/project/plugins.sbt
- integrations/sbt-bloop/src/sbt-test/sbt-bloop/use-pipelining/test
Bloop will not be able to compile the project otherwise as the options containg paths from sbt.
Fixes https://github.com/scalameta/metals/issues/6999
> bugfix: Drop pipelining options coming from sbt

- notes/v2.0.6.md
I am thinking of a new Metals release, so I would include the recent fixes
> docs: Add release notes for Bloop v2.0.6

- backend/src/main/scala/bloop/io/ParallelOps.scala
- backend/src/test/scala/bloop/io/ParallelOpsSuite.scala
This should help with the FileAlreadyExistsException that we are getting which is most likely caused by multiple threads writing at the same time. Blocking at origin file doesn't make much sense since it's the target that may fail, which is wrting.
Attempt at https://github.com/scalacenter/bloop/issues/2549
@Gedochao once this is merged we should try a snapshot version
> bugfix: Synchronize on target instead of origin when copying

- bloop-rifle/src/main/scala/bloop/rifle/internal/Operations.scala
This must have been a leftover of some earlier PoC. It's best to log and throw a proper exception in those cases
Fixes https://github.com/scalacenter/bloop/issues/2550
> bugfix: Remove ??? from Bloop rifle and log properly

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/io/ParallelOps.scala
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala
- frontend/src/test/scala/bloop/RunSpec.scala
- frontend/src/test/scala/bloop/util/TestProject.scala
Only jars and directories are excepted. In case of resources it will most likely be always a directory.
> bugfix: Don't add single files to classpath

- frontend/src/test/scala/bloop/dap/DebugProtocolSpec.scala
It seems to be very fragile and we sometimes get additional things printed out.
> chore: Mark 'restarted session does not contain JDI output' as flaky

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/io/ParallelOps.scala
- frontend/src/test/scala/bloop/RunSpec.scala
This was raised on bloop channel on discord.
> bugfix: Also copy resources on noop

- backend/src/main/scala/bloop/Compiler.scala
- backend/src/main/scala/bloop/util/BestEffortUtils.scala
This was caused by the custom hashing mechanism used for best effort compilations where we would needlessly hash the inputs twice - once before compilation (to see if it is necessary), and once after (to save the results). If a file was resaved during the compilation, by the end of it the hash input would be outdated and unreleted to the hash output, so bloop would cease recompilations until next change in the source file, leading to incoherent, leftover errors.
So now, we decouple the output hashing from the input hashing, and only hash the outputs after the compilation, and inputs always before the compilation. In theory, this could cause an unnecessary recompilation if a file is re-saved after reading inputs, but before compiling, leading to a needless compilation, but this is the case …
> Best-effort: fix issue with frequent file saves leading to leftover errors

- build.sbt
- frontend/src/main/scala/bloop/data/Project.scala
- frontend/src/main/scala/bloop/testing/TestNGFrameworkDependency.scala
- frontend/src/test/scala/bloop/LoadProjectSpec.scala
- frontend/src/test/scala/bloop/bsp/BspTestSpec.scala
- frontend/src/test/scala/bloop/util/TestUtil.scala
- project/Dependencies.scala
connected to: https://github.com/scalameta/metals/issues/6826
Should bump mill version after https://github.com/com-lihaoyi/mill/pull/4506 to get single test cases support.
> feat: add sbt.testing.Framework implementation for TestNG on classpath when needed

- backend/src/main/scala/bloop/Compiler.scala
Previously it was done in backgroundTasks, which could cause issues when combined with the hashing mechanism, itself in the main thread (blocking on compilation thread). This race condition could cause the iterator on the files to throw an error, and downstream compilations would switch to the best effort mode, even if the compilation should be successful.
> Best-effort: Move betasty directory cleaning into the compilation thread

- frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
- frontend/src/test/scala/bloop/ForkerSpec.scala
During our transition from IntelliJ to Metals, we discovered that some environment variables from our usual dotenv file (specified with envFile in launch.json) were missing in the debuggee processes. It turns out that Bloop silently removes ones with empty values.
> fix: empty environment variables are not handled in process forkers

- backend/src/main/scala/bloop/BloopClassFileManager.scala
- frontend/src/test/scala/bloop/BaseCompileSpec.scala
This PR addresses an (#2647) issue where Bloop allows compilation to succeed incorrectly after package renaming, due to lingering empty directories left behind after class invalidation.
When classes are invalidated (e.g., due to package renames or source changes), Zinc/Bloop correctly removes the class files, but the empty directories they lived in are left behind. These directories can cause wildcard imports to resolve even though the actual classes are no longer present, leading to confusing or incorrect compile results.
This change enhances `BloopClassFileManager` to remove all empty directories recursively after class files are deleted. It walks up the directory tree from the location of each removed file, cleaning up any now-empty directories. This ensures that stale packages are …
> Remove empty package directories after class invalidation.

- frontend/src/main/scala/bloop/Cli.scala
This should not happen, but I saw it in some logs.
> bugfix: Fix null pointer with sessions in CLI
