scalacenter/bloop

.gitmodules

Proxy friendlier, nicer to people working at bigcorps like myself :)

Git submodules: prefer https over ssh urls

---

backend/src/main/scala/bloop/DependencyResolution.scala
backend/src/main/scala/bloop/ScalaInstance.scala
backend/src/test/scala/bloop/ScalaInstanceCachingSpec.scala
build.sbt
frontend/src/main/scala/bloop/Project.scala
frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
frontend/src/main/scala/bloop/exec/ProcessConfig.scala
frontend/src/main/scala/bloop/testing/DiscoveredTests.scala
frontend/src/main/scala/bloop/testing/TestInternals.scala
frontend/src/main/scala/bloop/testing/TestServer.scala
frontend/src/main/scala/sbt/SerializableFingerprints.scala
frontend/src/test/scala/bloop/engine/DagSpec.scala
frontend/src/test/scala/bloop/tasks/CompilationHelpers.scala
frontend/src/test/scala/bloop/tasks/CompilationTaskTest.scala
frontend/src/test/scala/bloop/tasks/TestTaskTest.scala
project/BuildPlugin.scala
project/Dependencies.scala

Add support for forked test execution

---

frontend/src/main/scala/bloop/Bloop.scala

This reverts commit 74ce7cd0df022a9533e95cb20170081b12261ca5.

Revert "Remove `Bloop` shell"

---

.gitmodules

Fixes #169 
@jvican Is that the naming scheme that you had in mind for the branches in the submodules?

Sync nailgun

---

frontend/src/main/scala/bloop/Server.scala

Depends on #183 and scalacenter/nailgun#1, to be updated when scalacenter/nailgun#1 gets merged.

Set nailgun port to 8212

---

project/GitUtils.scala
project/ReleaseUtils.scala

The `release` step of CI currently fail with:
```
[error] (frontend/*:updateHomebrewFormula) org.eclipse.jgit.api.errors.TransportException: git@github.com:scalacenter/homebrew-bloop.git: UnknownHostKey: github.com. RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48
```
It appears that the fix is to change the configuration of the ssh session so that it doesn't verify the key of the host it tries to connect to. This is what this patch does.

Fix `UnknownHostException` while releasing

---

.drone.yml
bin/ci-clone.sh

And do shallow clones of the submodules

Do the recursive cloning ourselves

---

.drone.yml

Don't clone unless we're build a PR

---

.drone.yml
bin/add-coursier.sh

I invoke the god of coursier to make my CI faster.
Before we were blocked by
https://github.com/coursier/coursier/issues/388, but we work around that
issue by adding the coursier plugin to the global plugins directory so
that all the sbt builds get it.

Add coursier PLEASE

---

project/project/build.properties

End the pain: the continuation

---

README.md

Not sure why the shell prefixes became wrong again... I thought my last PR was merged.

Fixed installation instructions (again)

---

website/config.toml

Fix broken links in the website

---

project/BuildPlugin.scala

Re-fix base URL in website

---

frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala

Probably merged by mistake with #170.

Fix `IntegrationTestSuite`

---

website/content/faq/_index.md
website/layouts/shortcodes/partial.html

Add `Edit on GitHub` links

---

bin/install.py
frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
frontend/src/test/scala/bloop/bsp/BspClientTest.scala
project/ReleaseUtils.scala

See first commit for more information.

Fix regression in parallel compilation

---

website/content/docs/bloop-basics.md
website/content/docs/how-to-use-bloop.md
website/content/docs/installation.md
website/content/docs/integration-guide.md
website/content/docs/understanding-bloop.md

I'm also looking for a better title than "Understanding bloop". Do you
have any idea?

Elaborate on the "Understanding bloop" page

---

bin/install.py
project/ReleaseUtils.scala

Translated using `futurize`.
@valencik I don't know much about Python, is this the way to go?

Make install script compatible with Python2 and 3

---

integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala

I don't know how this passed the CI...

Fix master by using sbt.IO

---

frontend/src/main/scala/bloop/io/SourceWatcher.scala

From https://stackoverflow.com/questions/2979383/java-clear-the-console.

Clear screen before each watch iteration

---

.drone.yml
frontend/src/main/scala/bloop/io/SourceWatcher.scala

For some reason, Drone doesn't seem to update the drone commit
message... Let's do it manually.

Fix clearing of screen in SourceWatcher + drone insanity fix

---

bin/detect-community-build.sh
integrations/sbt-bloop/src/main/scala-sbt-0.13/bloop/integrations/sbt/Compat.scala
integrations/sbt-bloop/src/main/scala-sbt-1.0/bloop/integrations/sbt/Compat.scala
integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
project/BuildPlugin.scala

I mistakenly forgot to add the project to the bloop configuration
directory, meaning that all class files effectively go to the same
classes directory.

Add the project to the classes dir path

---

frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala

I suspect that the errors comes from the project under test being
compiled before by another test, therefore having a previous result and
violating our assumptions in this test.

Tentative fix for `FileWatchingSpec`

---

project/Dependencies.scala

Uses the improvement merged in scalacenter/nailgun and referenced in
https://github.com/facebook/nailgun/issues/112.

Use nailgun that doesn't throw closed socket

---

frontend/src/main/scala/bloop/cli/Commands.scala
frontend/src/main/scala/bloop/engine/Interpreter.scala
frontend/src/test/scala/bloop/testing/TestFilterSpec.scala

Fixes https://github.com/scalacenter/bloop/issues/327.

Rename `--filter` to `--only` | `-o`

---

build-integrations/sbt-1.0/project/build.properties

See https://github.com/sbt/sbt/issues/3871.

Use latest 1.1.1 to include bugfix for assembly error

---

website/content/docs/bloop-basics.md
website/content/docs/configuration-format.md

* Remove unnecessary heading in design goals page
* Fix quotes issue and elaborate on scripting tools

Fix quotes issue in docs and remove one heading level

---

frontend/src/main/scala/bloop/logging/BspLogger.scala

this should fix https://github.com/scalacenter/bloop/issues/450

report column instead of line at column position in bsp

---

frontend/src/main/scala/bloop/Project.scala
project/Dependencies.scala

To avoid conflict with scalafmt in the sbt universe.
Fixes #453.

Upgrade metaconfig

---

.gitignore

It would make my life a little bit easier :smile: Pretty please :bowing_man:

Add Ensime's config and cache files to .gitignore

---

backend/src/main/scala/bloop/DependencyResolution.scala
bin/install.py
build.sbt
frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
frontend/src/main/scala/bloop/testing/TestInternals.scala
frontend/src/test/scala/bloop/engine/DagSpec.scala
frontend/src/test/scala/bloop/nailgun/BasicNailgunSpec.scala
frontend/src/test/scala/bloop/nailgun/NailgunTest.scala
project/BuildPlugin.scala
project/Dependencies.scala
project/ReleaseUtils.scala

Fixes:
```
[E] Boxed Error
[T] java.util.concurrent.ExecutionException: Boxed Error
...
[T] Caused by: java.lang.NoSuchMethodError: coursier.CachePath.localFile(Ljava/lang/String;Ljava/io/File;Ljava/lang/String;)Ljava/io/File;
[T]     coursier.Cache$.localFile(Cache.scala:47)
```

Update Coursier to 1.1.0-M3 and add explicit Scalaz dependency

---

backend/src/main/scala/bloop/io/Timer.scala
build-integrations/sbt-0.13-2/.jvmopts
build-integrations/sbt-0.13-2/.sbtopts
build-integrations/sbt-0.13-2/build.sbt
build-integrations/sbt-0.13-2/project/Integrations.scala
build-integrations/sbt-0.13-2/project/build.properties
frontend/src/main/scala/bloop/Project.scala
frontend/src/main/scala/bloop/engine/Build.scala
frontend/src/main/scala/bloop/engine/Dag.scala
frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
frontend/src/test/scala/bloop/engine/LoadProjectSpec.scala
frontend/src/test/scala/bloop/logging/RecordingLogger.scala
project/BuildPlugin.scala

Fixes https://github.com/scalacenter/bloop/issues/62.
Lichess needs to go into an independent sbt 0.13 build because the dependencies of the play plugin conflict fatally with `sbt-maven-plugin` used by apache/spark.

Add lichess to our community build and optimize loading

---

frontend/src/test/scala/bloop/engine/FileWatchingSpec.scala

Don't embed the number of watching dirs we expect

---

integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-configurations/build.sbt

This just adds a test case for an already existing feature.
/cc @tues
Closes #515.

Ensure that export of custom configuration works

---

project/Dependencies.scala

To fix bug reports https://github.com/brettwooldridge/NuProcess/issues/87.

Upgrade nuprocess to 1.2.3

---

backend/src/main/scala/bloop/reporter/DefaultReporterFormat.scala

Closes #536 
Haven't tested it yet, but let's see what the CI thinks about it.

Append line and column to the default reporter

---

backend/src/main/scala/bloop/DependencyResolution.scala

This allows to resolve bridge artefacts that have been published
to Bintray: https://bintray.com/scalacenter/releases

DependencyResolution: Add Bintray resolver

---

config/src/main/scala-2.10/bloop/config/ConfigEncoderDecoders.scala
config/src/main/scala-2.12/bloop/config/ConfigEncoderDecoders.scala
config/src/main/scala/bloop/config/Config.scala
frontend/src/main/scala/bloop/Project.scala
frontend/src/main/scala/bloop/engine/Interpreter.scala
frontend/src/main/scala/bloop/engine/tasks/ToolchainCompanion.scala
integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala
integrations/mill-bloop/src/main/scala/bloop/integrations/mill/MillBloop.scala
integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
project/BuildPlugin.scala

@jvican I think it would be more intuitive to allow users to specify up to one main class in the configuration file (i.e. `Option[String]` instead of `List[String]`).

Add ability to set default main class

---

project/Dependencies.scala

Upgrade to latest nailgun version

---

build.sbt
project/BuildPlugin.scala
website/content/docs/installation.md

closes #563 
@jvican please review

Set the maven plugin to the Scala 2.10 version

---

README.md

Let's give Tim (@tindzk) a warm welcome as a maintainer! Tim, feel free
to approve and merge whenever you have accepted the invitation to join
the bloop-team in GitHub, and thanks for all your work filing tickets
and improving the Scala.js and Scala Native integrations, among other
things.

Add Tim to the list of maintainers

---

.drone.yml
build.sbt

Addresses https://github.com/scalacenter/bloop/issues/606

Publish the gradle plugin for Scala 2.12

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala

Filter project deps with JavaPluginConvention in Gradle

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/BloopInstallTask.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala

Also always add the main source set to the classpath from project dependencies.

Add the main source set to the classpath of other project source sets

---

frontend/src/main/scala/bloop/Cli.scala
frontend/src/main/scala/bloop/engine/Feedback.scala
frontend/src/test/scala/bloop/nailgun/BasicNailgunSpec.scala

Fixes https://github.com/scalacenter/bloop/issues/603

Add better feedback if configuration directory is missing

---

.drone.yml
backend/src/main/scala/bloop/Compiler.scala
backend/src/main/scala/sbt/internal/inc/bloop/CompileMode.scala
backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopHighLevelCompiler.scala
bin/detect-community-build.sh
frontend/src/main/scala/bloop/engine/caches/ResultsCache.scala
frontend/src/main/scala/bloop/engine/tasks/CompilationTask.scala
frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala
frontend/src/main/scala/bloop/engine/tasks/compilation/CompileResult.scala
frontend/src/test/scala/bloop/tasks/CompilationTaskTest.scala
frontend/src/test/scala/bloop/tasks/IntegrationTestSuite.scala
frontend/src/test/scala/bloop/tasks/TestTaskTest.scala
frontend/src/test/scala/bloop/tasks/TestUtil.scala

Check commit messages for more information on the fixes required to make this
happen.

Enable pipelined community build

---

website/content/docs/configuration-format.md

* fix link path to json schema
* fixes #619

#619 Fix path to JSON schema in the docs

---

project/build.sbt

This has been a common error among our contributors, so we better have
specific logic in our build to save them some time.
/cc @Qi77Qi & @shwin

Do better at notifying of missing git submodules

---

bin/install.py

I'm not a python developer, I hope it's not too much outside of pythons standards.
The openurl lib from python can already read `http_proxy` and `https_proxy` so nothing is needed there.

#698 - Support proxy in coursier instalation

---

website/content/docs/installation.md

Should be review by an systemctl expert. #701

#701 - install doc - systemctl enable directly the systemd file

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala

Fixes https://github.com/scalacenter/bloop/issues/700

Return correct platform for BSP Scala targets

---

frontend/src/main/scala/bloop/engine/Interpreter.scala
frontend/src/test/resources/cross-test-build-0.6/test-project/jvm/src/main/scala/hello/ShowCwd.scala
frontend/src/test/scala/bloop/tasks/RunSpec.scala

Set cwd to project's base directory

---

website/pages/en/index.js

Use the correct link to Metals home page.

Correct link to Metals

---

bin/install.py

As recommended by the comment in https://github.com/scalacenter/bloop/issues/770
Fixes #770

Remove leading '%` to fix problem invoking bloop

---

bin/install.py
notes/v1.2.2.md
project/Dependencies.scala
project/ReleaseUtils.scala

Check the release notes for more details.

Cut release v1.2.2 with macOS bugfix

---

backend/src/main/scala/bloop/DependencyResolution.scala
backend/src/main/scala/bloop/ScalaInstance.scala
backend/src/test/scala/bloop/ScalaInstanceCachingSpec.scala
backend/src/test/scala/bloop/ScalaInstanceSpec.scala
build.sbt
frontend/src/main/scala/bloop/Server.scala
frontend/src/main/scala/bloop/data/Project.scala
frontend/src/main/scala/bloop/engine/tasks/toolchains/ToolchainCompanion.scala
frontend/src/main/scala/bloop/testing/TestInternals.scala
frontend/src/test/scala/bloop/ClasspathHashingSpec.scala
frontend/src/test/scala/bloop/CompileSpec.scala
frontend/src/test/scala/bloop/util/TestProject.scala
frontend/src/test/scala/bloop/util/TestUtil.scala
launcher/src/main/scala/bloop/launcher/core/Installer.scala
launcher/src/test/scala/bloop/launcher/LauncherSpec.scala
notes/v1.2.2.md
project/Dependencies.scala

Complete release notes and sync with latest nailgun.

Prepare for v1.2.2 release

---

bin/install.py

Show correct default for install.py '--dest' option

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala

This applies the default Eclipse plugin from gradle that downloads the dependencies locally and links them in the bloop configuration.

Export source dependencies from Gradle builds

---

frontend/src/main/scala/bloop/io/SourceWatcher.scala
frontend/src/test/scala/bloop/FileWatchingSpec.scala

Because of the semantics of the `bufferTimed` operator in Monix, bloop could be overflown with file watcher events and be irresponsive sometimes to legit file watcher events. This commit ensures this doesn't happen anymore by filtering out empty file watcher events.

Prevent overflowing of file watcher events

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/ConfigureBloopInstallTask.scala

Seems that previously we added all artifacts as inputs which cause project jars to be added also. This caused issues when projects were not compiled, since the jar would not exists.
This PR makes sure that we don't add artifact dependencies from other projects.

Do not include project jar dependencies in Gradle

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala

This simply wires up the logic, which was already there.
Addresses #683

Implement buildTarget/scalaMainClasses

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
frontend/src/main/scala/bloop/engine/tasks/TestTask.scala
frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala

 Implement buildTarget/scalaTestClasses

---

docs/contributing-guide.md

Since user should not be worried about this error its nice to have it
mentioned

Update contributing guide

---

frontend/src/main/scala/bloop/engine/Interpreter.scala

Since there are warning messages in findMainClasses and
findFullyQualifiedTestNames which will look very ugly in autocomplete
(check issue #894 to see the result) we are passing NoopLogger
to make sure that no warnings are printed in autocomplete.

Don't print warnings when autocompleting in zsh

---

frontend/src/main/scala/bloop/engine/tasks/compilation/CompileGraph.scala

The compile bundle can throw if there is some IO error when, for
example, hashing sources or classpath entries. To protect us from that,
we make sure that we catch any exceptions in its computation and we
translate it to our compile result representation so that the user can
now about it.

Catch exceptions when computing the compile bundle

---

notes/v1.3.0-RC1.md

I am currently working on the release notes. I'm cutting RC1 to let
users try it out while I work on them. They will be updated after the
release and will make it for v1.3.0 too, which will be merged soon.

Add release notes for v1.3.0-RC1

---

frontend/src/main/scala/bloop/cli/Commands.scala
frontend/src/main/scala/bloop/engine/Interpreter.scala
frontend/src/main/scala/bloop/engine/tasks/Tasks.scala

Should address #903. Just something I figured on my own, hope this is the right approach.

Add parallel test execution support

---

project/build.sbt

I've tried to set-up the project, my terminal provided a link to the site that gave me 404 error code so I've decided to fix it.

Change docs link

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala

Split -encoding and its value into two separate scalac arguments

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
project/Dependencies.scala

Export JVM platform options from Gradle project

---

config/src/main/scala/bloop/config/Config.scala
integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala

This allows for some limited configurability of most common test frameworks.

Import Gradle test system properties to test framework config

---

backend/src/main/scala/bloop/ScalaInstance.scala
backend/src/test/scala/bloop/ScalaInstanceSpec.scala
frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
frontend/src/main/scala/bloop/data/Project.scala
frontend/src/main/scala/bloop/engine/Interpreter.scala
frontend/src/test/scala/bloop/BuildPipeliningSpec.scala

Fixes https://github.com/scalacenter/bloop/issues/880

Identify Java-only projects inside Bloop

---

frontend/src/main/scala/bloop/engine/tasks/TestTask.scala

Fix typo in TestTask.scala

---

frontend/src/main/scala/bloop/engine/Dag.scala

Previously, the `Dag.dagFor` method exhaustively explored all possible
paths in the input `dags: List[Dag[T]]`. For large dependency trees,
this exhaustive walk can take a long time to run. Now, we cache the
recursive call to `dagFor` so that it completes faster.

Avoid pathological performance in `Dag.dagFor`.

---

frontend/src/main/scala/bloop/dap/DebugSession.scala

Previously, this exception was ignored only when debuggee was cancelled but it can also happen when it terminates on it own.
This prevents the exception from being propagated to the debug client when debuggee already finished

Ignore socket closed exception when debuggee exited

---

frontend/src/main/scala/bloop/engine/Dag.scala

Previously, a BSP compile request would not respond when compiling a
workspace with a large number of targets. The profile pointed at
`Dag.reduce`, which is a recursive method traversing the dependency
graph between targets.
This commit adds a cache to the recursive loop in `Dag.reduce`, making
the BSP compile requests respond as expected in the same large
workspace.

Add caching to recursive loop in `Dag.reduce`, fixes #1043.

---

integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala

Adds empty check for scalac options to avoid NPE (#928)

---

project/ReleaseUtils.scala

All the AUR packages' files are downloaded in the same directory, and can be kept for some time.
The problem is that the installer script has always the same name, so if an old version of `install.py` is still there the package manager might try to use it and fail with a wrong checksum :cry: 
Besides, `install.py` could be used by another package and cause conflicts.
This PR solves this by downloading `install.py` to `install-bloop-$version.py` :smiley:

Fix ArchLinux package cache issues

---

frontend/src/main/scala/bloop/dap/DebugSession.scala

This prevents a race condition between `launch` and `configurationDone` requests. 
Currently, the former is waiting for the debuggee to become attachable before starting a new debug session, while the latter tries to subscribe to the debug session immediately upon receiving the request.
This suspends handling of the `configurationDone` request until we attach to the debuggee

Delay handling the configurationDone request until debuggee attached

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala

Previously, the `buildTarget/scalacOptions` request had bad runtime
performance when processing workspaces with large classpaths. Now, we
cache the result of `AbsolutePath.toBspUri` speeding up
`buildTarget/scalacOptions` by ~30x in one experimental benchmark.
```diff
- before
+ after
- [Trace - 03:10:30 PM] Received response 'buildTarget/scalacOptions - (3)' in 64937ms
+ [Trace - 04:23:27 PM] Received response 'buildTarget/scalacOptions - (3)' in 3825ms
```

Cache calls to `AbsolutePath.toBspUri`, fixes #1089.

---

frontend/src/main/scala/bloop/engine/tasks/CompileTask.scala

@jvican: Here's my attempt to address the thread in https://github.com/scalacenter/bloop/pull/1070#discussion_r340926145
Note: this will conflict with that PR. It's more as a placeholder for a discussion. I don't expect it to be merged as-is.

Doc cleanup clean up previous result

---

project/Dependencies.scala

Fixes https://github.com/scalacenter/bloop/issues/1059

Sync up with Zinc to get Dotty rendered problems

---

backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopLookup.scala

Guard expensive log statements against `logger.isVerbose`

---

bin/install.py

Fixes: https://github.com/scalacenter/scoop-bloop/issues/5

Quote the full path for bloop in the generated bat file

---

frontend/src/main/scala/bloop/util/ProxySetup.scala

Fixes https://github.com/scalacenter/bloop/issues/1128. 
I would have written test(s) but there is currently none for this class and was not sure if worth it to go through the work of implementing them.

Ignore invalid proxy URIs on settings

---

.gitignore
integrations/sbt-bloop/src/main/scala-sbt-0.13/bloop/integrations/sbt/Offloader.scala
integrations/sbt-bloop/src/sbt-test/sbt-bloop/no-compile-incremental/build.sbt
integrations/sbt-bloop/src/sbt-test/sbt-bloop/no-compile-incremental/project/plugins.sbt
integrations/sbt-bloop/src/sbt-test/sbt-bloop/no-compile-incremental/project/project/plugins.sbt
integrations/sbt-bloop/src/sbt-test/sbt-bloop/no-compile-incremental/test

Fixes https://github.com/scalacenter/bloop/issues/1158

Fix an issue with non existing compileIncremental key

---

build.sbt
project/build.sbt

Follow up from https://github.com/scalacenter/bloop/pull/1170#issuecomment-585672947

Use `dynverSeparator` as recommended in sbt-dynver readme

---

frontend/src/test/scala/bloop/RunSpec.scala
integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
integrations/sbt-bloop/src/sbt-test/sbt-bloop/working-dir/build.sbt
integrations/sbt-bloop/src/sbt-test/sbt-bloop/working-dir/changes/build.sbt
integrations/sbt-bloop/src/sbt-test/sbt-bloop/working-dir/project/plugins.sbt
integrations/sbt-bloop/src/sbt-test/sbt-bloop/working-dir/test

Implements the approach discussed in the ticket.
Fixes #1167

Use right working directory to run app or tests from sbt

---

backend/src/main/scala/bloop/tracing/BraveTracer.scala

For certain debug use cases, we would like the Zipkin traces submitted to override sampling settings on the server by setting the `debug` flag on a trace.
This change will allow users to set a `zipkin.trace.debug` property for this purpose.

Add debug sampling flag option for Zipkin traces

---

bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala

Previously if Java was not available on PATH, the launcher would fail and not start the Bloop server. Now we revert to java home if that was the case.

Fallback to java home if it was not available on PATH

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala

If refresh project fails it looks like this:
Not sure what is the ideal error reporting mechanism. Exception seems to work reasonably well. Most of endpoints in case of error still return success with empty result and just log the error.
Some return `JsonRpcResponse.invalidRequest`, but it doesn't seem to work, the request shows as successful. JsonRpcResponse.error requires RequestId which is not available.

Report error when refreshProjectsCommand fails

---

docs/build-tools/sbt.md

This pr just fixes a couple typos in the sbt section that I noticed today while reading.

Fix a couple typos in the sbt section

---

docs/contributing-guide.md
docs/debugging-reference.md
docs/ides/metals.md
docs/ides/overview.md
docs/performance-guide.md
docs/server.md
website/sidebars.json

This pr update a couple metals-related things in the docs and other various typos. I'll add a few comments explaining some of the changes.

Update various typos and metals docs

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala

Takes advantage of compileClasspath/runtimeClasspath split.

Use runtime classpaths in Gradle

---

frontend/src/main/scala/bloop/engine/Interpreter.scala
frontend/src/test/scala/bloop/FileWatchingSpec.scala

File watching was not supported for projects that define their source
list as globs, because the `SourceWatcher` was directly collecting the
sources from the eponymous field in the configuration files.
The source watcher now respects globs when collecting sources and
directories to watch.

Support globs in file watching

---

frontend/src/main/scala/bloop/testing/TestServer.scala

Invoke done on sbt test runners

---

project/ReleaseUtils.scala

It turns out that the "single binary" generated by `coursier install` is a launcher script `bloop` + the graalvm-compiled binary `.bloop.aux`, that's why we need a directory for the Bloop installation.
Question :upside_down_face:
Some users found the systemd service useful, and it doesn't cost much to add it back (even if its use is questionable). Should I add the service file to `ReleaseUtils#installationArtifacts()`? (with some logic so that it only ends up in the arch package)

Fix ArchLinux package for v1.4+

---

docs/contributing-guide.md

I had to follow that guide to set up the Scala Native environment on my machine.

Add Scala Native environment setup guide to contributing guide

---

bloopgun/src/main/scala/bloop/bloopgun/Bloopgun.scala

This a fix for the regression in https://github.com/scalacenter/bloop/pull/1203
The additional catch in sysproc caused the exception not to be thrown further.

Make sure we try to revert to JAVA_HOME if java is not on PATH

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala

Project dependency discovery and classpath creation reworked to handle classpath ordering issues and project sourceset identification issues.
Add [TestFixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures) functionality.
Add [ScalaCompilerPlugins](https://docs.gradle.org/current/userguide/scala_plugin.html#sec:scala_compiler_plugins) functionality. Fixes #1312
Cope with lazily defined archives. Fixes #1311
Remove irrelevant artifacts populating resolution modules
Bump max version compatibility to Gradle 6.5

Improve gradle dependency detection

---

notes/v1.4.2.md
project/Dependencies.scala

This commit upgrades to the Zinc version that has a fix for #1296.
Fixes #1296

Bump Zinc version

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala

Exports any Gradle source set, that has a Test task relating to it, as a test project with test tag and test frameworks
Fixes #1335

Recognise Gradle integration tests as test projects

---

integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala

Not sure if it was ever correct or is this a regression, but the test project fails without specifying the dependency.

Add main dependency to a test project for Maven Bloop plugin 

---

integrations/maven-bloop/src/main/java/bloop/integrations/maven/BloopMojo.java
integrations/maven-bloop/src/main/scala/bloop/integrations/maven/MojoImplementation.scala

Added missing sourceDir and improve error message

Add `sourceDir` mojo parameter to maven plugin

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
frontend/src/main/scala/bloop/dap/DebuggeeRunner.scala
frontend/src/main/scala/bloop/engine/Interpreter.scala
frontend/src/main/scala/bloop/engine/tasks/Tasks.scala
frontend/src/main/scala/bloop/exec/JvmProcessForker.scala
frontend/src/main/scala/bloop/testing/TestInternals.scala
frontend/src/test/scala/bloop/ForkerSpec.scala
frontend/src/test/scala/bloop/dap/DebugProtocolSpec.scala
frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
frontend/src/test/scala/bloop/util/TestUtil.scala
project/Dependencies.scala

Issue: https://github.com/scalacenter/bloop/issues/1264
PR to BSP: https://github.com/build-server-protocol/build-server-protocol/pull/118

Start debug session with user-provided environment variables

---

backend/src/main/scala/bloop/tracing/BraveTracer.scala

Previously, Bloop would create a new instance of `AsyncReporter` for
every task. Each and every of these reporters would create new threads,
which would never be stopped.
This commit caches the `AsyncReporter`s so that they can be reused and
we keep a single instance per reporting server.
Fixes #1385
cc/ @wiwa

Reuse Zipkin reporter between tasks

---

config/src/main/scala-2.10/bloop/config/ConfigCodecs.scala

This should fix issues caused by https://github.com/scalacenter/bloop/pull/1387
It seems circe has an error in which it will print all empty Option values and that is especially problematic with things that should be printed as objects. So currently the generated jsons will contain:
```
"platform" : {
"name" : "jvm",
"config" : {
"home" : "/usr/lib/jvm/java-8-openjdk-amd64/jre",
"options" : [
"-Duser.dir=/home/tgodzik/Documents/metals/tests/slow/target/e2e/sbt-bloop-import/min-sbt-version"
]
},
"mainClass" : [
],
"runtimeConfig" : [
],
"classpath" : [
],
"resources" : [
]
},
```
And runtime config cannot be parsed back as it's supposed to be an object and should not really be defined unless it contains `home` and `options`. Tested this locally and it seems to work, however we never run …

Fix issues config issues on sbt 0.13

---

project/ReleaseUtils.scala

Follow up from https://github.com/scalacenter/homebrew-bloop/pull/13
Thanks again @ElfoLiNk !

Update brew formula to fix a warning

---

frontend/src/main/scala/bloop/logging/BspServerLogger.scala

Remove 'code' property of bsp.Diagnostic

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala

Handles root project having a duplicate name of a sub project. Fixes: #1505
Reduces fully qualified names of duplicate projects to minimum namespace required to make them unique e.g.
`a-b-c-Foo` and `a-b-c-d-Foo`
becomes
`c-Foo` and `d-Foo`
Updates max test version to Gradle 7.0.  Some Gradle configurations are deprecated (or made non-consumable) so those tests are excluded and another added.

Gradle duplicate project name fix and tests for v7.0

---

frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala

Might be possible that using later scalaJs version will help out here.

Try to fix flaky `fin test classes` test

---

integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala
integrations/sbt-bloop/src/sbt-test/sbt-bloop/meta-builds/build.sbt
integrations/sbt-bloop/src/sbt-test/sbt-bloop/meta-builds/project/plugins.sbt

[SbtBloop] Fix source dependencies for meta-build

---

project/Dependencies.scala

Show static variables in stack frame (see https://github.com/scalacenter/scala-debug-adapter/pull/46)

Bump scala-debug-adapter

---

backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala

Fixes https://github.com/scalacenter/bloop/issues/1549#issuecomment-903242035

Fix support for Scala 3.1

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala

Should fix https://github.com/scalacenter/bloop/issues/1132

Take into account --verbose flag when creating a logger

---

bin/sbt-ci.sh

There seems to be an issue with the normal sbt script on windows.

Use sbt extras script under sbtx alias

---

.github/workflows/ci.yml
project/Dependencies.scala
project/GradleIntegration.scala

Such as https://github.com/scalacenter/bloop/runs/3487999013?check_suite_focus=true

Cache Gradle API to avoid download issues

---

bin/release_notes.sc
docs/contributing-guide.md
notes/v1.4.9.md

I also added some utility scripts to generate the notes from and a description of the release process.

Add release notes for v1.4.9

---

docs/build-tools/maven.md
docs/tools/universal/install.md

Related to https://github.com/scalacenter/bloop/issues/1573

Update Maven and Coursier documentation

---

integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala
integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/ConfigureBloopInstallTask.scala
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala

1) Add test for Scala3 (using Gradle nightlies) and make functionality support by Gradle version clearer.
2) Refactor the way ArchiveTasks are queried for their contents.
3) Make artifact resolution more lenient
I can't reproduce either issue in #1566 but 2 and 3 may solve both of them 🤷

Gradle improvements

---

backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala
frontend/src/test/scala/bloop/ScalaVersionsSpec.scala
project/Dependencies.scala

Fixes https://github.com/scalacenter/bloop/issues/1598

Update zinc fork with the newest fixes

---

frontend/src/main/scala/bloop/dap/BloopDebuggeeRunner.scala
project/Dependencies.scala

This fixes the issues with classpath manifest jars.

Bump scala-debug-adapter to 2.0.11

---

backend/src/main/scala/bloop/DependencyResolution.scala
backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala
backend/src/main/scala/sbt/internal/inc/HydraSupport.scala
bloopgun/src/main/scala/bloop/bloopgun/core/DependencyResolution.scala
build.sbt
docs-gen/src/main/scala/bloop/docs/Sonatype.scala
frontend/src/main/scala/bloop/engine/caches/SemanticDBCache.scala
frontend/src/main/scala/bloop/exec/Forker.scala
frontend/src/test/scala/bloop/ConsoleSpec.scala
frontend/src/test/scala/bloop/HydraCompileSpec.scala
launcher/src/main/scala/bloop/launcher/BloopServerVersion.scala
launcher/src/test/scala/bloop/launcher/LauncherBaseSuite.scala
project/Dependencies.scala
project/project/build.sbt

The former is more stable, has less dependencies, and is enough for our needs here.

Use coursier-interface rather than coursier

---

frontend/src/test/scala/bloop/HydraCompileSpec.scala

Fix regex used for HydraCompileSpec

---

frontend/src/test/scala/bloop/HydraCompileSpec.scala

I will ignore the tests for now as I don't have time to deal with the failures, no idea why the fixes do not work.
cc @dotta

Ignore hydra tests

---

frontend/src/main/scala/bloop/data/Project.scala

Adds module exports for Sourcegraph lsif-java plugin when the JVM is >= 17
As suggested - I've used the `JAVA_HOME/release` file to get the build target's JVM version or fallback to Bloop's JVM if the build target has no JVM specified.
`JAVA_HOME/release` seems to be available on all my installed JDKs across Windows and WSL
I've copied the version compare code from `scala.util.Properties#compareVersions` which is unfortunately not public.  I'd put this code in a util helper class but I don't think it's worth it until it's going to be used in other places as well.
`com.google.gson.internal.JavaVersion` only offers comparison to the running JVM - the rest of the code is private.

Add exports for Semanticdb plugin on Java 17

---

backend/src/main/scala/bloop/CompilerCache.scala

CompierCache - fix patmat

---

frontend/src/main/scala/bloop/data/Project.scala

Fixes https://github.com/scalacenter/bloop/issues/1656
Checked it locally and this seems to work.

Allow Java versions with a suffix

---

bloopgun/src/main/scala/bloop/bloopgun/util/GlobalSettings.scala

Use JAVE_HOME for server

---

.github/workflows/ci.yml
bin/install.py
bin/release_notes.sc
bin/run-benchmarks.sh
docs/contributing-guide.md
docs/performance-guide.md
integrations/gradle-bloop/src/test/scala/bloop/integrations/gradle/ConfigGenerationSuite.scala
launcher-test/src/test/scala/bloop/launcher/LauncherSpec.scala
project/ReleaseUtils.scala
website/pages/en/users.js
website/siteConfig.js

Closes https://github.com/scalacenter/bloop/issues/1649

Switch primary branch to main

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala

My mistake, request's kind should be `"scala-test-suites-selection"`

fix: update BloopBspServices.scala

---

project/Dependencies.scala

Bump debug adapter library to 2.2.0

---

frontend/src/main/scala/bloop/bsp/BloopRpcServices.scala

Follow up to #1759
I thought that it was fixed in https://github.com/scalacenter/bloop/commit/2baf28a633805211eb9b26b62a350e4224750b3d
but it seems that I got confused in locally published bloop versions.

fix: empty parameters json parsing

---

frontend/src/main/scala/bloop/engine/caches/SourceGeneratorCache.scala
frontend/src/test/scala/bloop/SourceGeneratorSpec.scala

Previously, Bloop would not store the state of source generators after
their run, which would cause them to always be re-run, even when there
are no changes.

Store source generators' states

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala
frontend/src/test/scala/bloop/bsp/BspConnectionSpec.scala
frontend/src/test/scala/bloop/bsp/TestConstants.scala
project/Dependencies.scala

chore: set canDebug capabilities to true

---

.github/workflows/steward.yml
.scala-steward.conf

We might want to migrate to a new bot later on since I can't find access to this one, but let's test it out first.

chore: Try to setup Scala Steward

---

frontend/src/test/scala/bloop/dap/DebugServerSpec.scala
project/Dependencies.scala

Update scala-debug-adapter to 3.0.5

---

build.sbt
project/BuildPlugin.scala
project/Dependencies.scala
project/build.sbt

This does a few different things:
- removes no longer needed deps
- removes a couple defs/Keys that are no longer used
- deduplicates settings entries
And just general cleanup

refactor(build): a bit of build cleanup

---

frontend/src/test/scala/bloop/ScalaVersionsSpec.scala
frontend/src/test/scala/bloop/util/TestUtil.scala

This just cheery picks a couple of the commits from https://github.com/scalacenter/bloop/pull/1749 that I wanted in here. Then I'll close that seeing we've updated to setup-java already.

Small test improvements

---

backend/src/main/scala/bloop/BloopClassFileManager.scala
frontend/src/main/scala/bloop/bsp/BloopBspServices.scala

Fixes https://github.com/scalacenter/bloop/issues/2056

bugfix: Remove backup directory after compilation

---

backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopAnalysisCallback.scala

bugfix: Fix infinite recursion

---

notes/v1.5.11.md

We need to release a new version since the last broke incremental compilation.

docs: Add release notes for 1.5.11

---

.github/workflows/release-website.yml

bugfix: checkout all submodules on website release

---

frontend/src/main/scala/bloop/bsp/BloopBspServices.scala
frontend/src/test/scala/bloop/bsp/BspBaseSuite.scala
frontend/src/test/scala/bloop/bsp/BspProtocolSpec.scala
frontend/src/test/scala/bloop/bsp/TestConstants.scala

DependencyModules is an improvement on DependencySources

Implement BSP buildTargetDependencyModules

---

.github/workflows/ci.yml
project/BuildPlugin.scala

I started doing things manually, but that doesn't seem like a great way forward.

chore: Try to fix the release

---

frontend/src/main/scala/bloop/data/Project.scala

fix for: https://github.com/scalameta/metals/issues/6024

fix: incorrect directory in debug tests for scala-cli

---

.github/workflows/ci.yml

bugfix: Fix issues after change of the github action behaviour

---

.sbtopts

https://github.com/sbt/sbt/issues/7463

bugfix: Fix another issue this time with sbt 1.9.8

---

frontend/src/main/scala/bloop/reporter/BspProjectReporter.scala

Caused https://github.com/VirtusLab/scala-cli/issues/2829

bugfix: Don't show error message if nothing needs to be send, but end was processed

---

docs/build-tools/gradle.md

Fixes https://github.com/scalacenter/bloop/issues/2309

chore: Fix link to setup

---

frontend/src/main/scala/bloop/bsp/ProjectUris.scala

fix for: https://github.com/scalacenter/bloop/pull/2311#discussion_r1558063599
I think that `split("&")` is unnecessary here, since the build target `uri` is an identifier and shouldn't really be ever modified to encode more information.

fix: correctly decode project name from build target uri

---

.scala-steward.conf
benchmarks/src/main/java/pl/project13/scala/jmh/extras/profiler/ForkedAsyncProfiler.java
benchmarks/src/main/java/pl/project13/scala/jmh/extras/profiler/NoResult.java
benchmarks/src/main/java/pl/project13/scala/jmh/extras/profiler/ProfilerUtils.java
benchmarks/src/main/scala/bloop/logging/BloopLoggerBenchmark.scala
project/BuildPlugin.scala
project/GithubRelease.scala
project/GithubReleasePlugin.scala
project/build.sbt

Both of the dependencies don't seem to be available on maven central which is why the build is currently failing
For JMH I fixed the compilation by inlining some missing classes and fixing enum. I am not 100% sure if that is correct, but seems to work ok.
For github release I just inlined the one file.

bugfix: Fix CI by updating JMH and inlining sbt-github-release

---

backend/src/main/scala/bloop/BloopClasspathEntryLookup.scala
frontend/src/main/scala/bloop/logging/ScribeAdapter.scala

I recently swa this and realized this might actually cause some issues, however not idea what test would be good to verify it.

bugfix: Fix wrong comparison as reproted by the compiler

---

.github/workflows/ci.yml

Looks like I forgot to do that.

chore: Update Java version for releases

---

bin/release_notes.scala
notes/v2.0.0.md

I also rewrote the script to use Scala CLI

docs: Add release notes for Bloop 2.0.0

---

.github/workflows/ci.yml

bugfix: Change name for release artifacts

---

cli/src/main/scala/bloop/cli/util/OsLibc.scala

Fixes https://github.com/scalacenter/bloop/issues/2403

bugfix: Check is lib and /usr/sbin paths exists before listing

---

backend/src/main/scala/bloop/BloopClassFileManager.scala
backend/src/main/scala/bloop/Compiler.scala

Fixes https://github.com/scalacenter/bloop/issues/2415

bugfix: Make sure tmp directories are removed

---

notes/v2.0.3.md

Figured the improvement with bspEnabled will be useful in the compiler

docs: Add release notes for 2.0.3

---

project/Dependencies.scala

Looked inocent, but it actually broke everything, not sure why.

chore: Revert shapeles update

---

backend/src/main/scala/bloop/Compiler.scala
frontend/src/test/scala/bloop/BaseCompileSpec.scala
frontend/src/test/scala/bloop/bsp/BspCompileSpec.scala

Context https://github.com/scala/scala3/issues/20041

bugfix: Treat -Werror the same as -Xfatal-warnings

---

project/Dependencies.scala

@tgodzik Could you cut a release of bloop with this?

deps: bloop-config 2.3.0 -> 2.3.1

---

backend/src/main/scala/bloop/io/ParallelOps.scala
frontend/src/test/scala/bloop/RunSpec.scala

This is current behaviour that Scala CLI follows and I think it makes sense. If users report issues we can always add a configuration option.

bugfix: Don't copy resources in directories starting with a dot

---

etc/fish-completions

Fixes https://github.com/scalacenter/bloop/issues/2583
Turns out there is a method for it.

bugfix: Fix fish completions for test suite

---

backend/src/main/scala/bloop/io/ParallelOps.scala
frontend/src/test/scala/bloop/RunSpec.scala

This might help with https://github.com/scalacenter/bloop/issues/2629
Also adds a test for an edge case with multiple files with the same name.

improvement: Retry copying when AccessDeniedException is encountered

---

frontend/src/test/scala/bloop/RunSpec.scala

Looks like the tests there are flaky and it might be related to the user's issue.

chore: Print logs when run test fail

---

.github/workflows/ci.yml
.gitignore
backend/src/main/scala/bloop/DependencyResolution.scala
backend/src/test/scala/bloop/DependencyResolutionSpec.scala

Connected to https://github.com/scalameta/metals/issues/7293

improvement: Try to fallback to locally available coursier to work around potential issues

---

frontend/src/main/scala/bloop/Cli.scala

This will cause to create new CLI directories, which might be removed prematurely

bugfix: Remove session after task finished

---

backend/src/main/scala/bloop/ScalaInstance.scala

Fixes https://github.com/scalacenter/bloop/issues/2711#issuecomment-3229114156

improvement: Make Scalac jar discovery more flexible
